M7R0
I%a_r_$"#S""!6",
I&f_tg_$"#]!#5F&,
I.filemeas_name7"F&,
I(eqrxnId7$%#r6G%#r7GF&,
I'vigridF%F&,
I*dC_MCPAdt%#r8GF&,
I$vw0F%F&,
I$KF_$"#5F%F&,
I+listoutput7("""""#""$""%""&""'F&,
I*precision%'doubleGF&,
I(type_up7(F%F%F%F%F%F%F&,
I%a_a_$F7!"#F&,
I)diffdata7($F%F%FI$F7F*FIFIFIF&,
I$ws_$""(!""F&,
I(dmRNAdtF0F&,
I(noutputF?F&,
I$vicF;F&,
I&rate7**%%f_tgGF:)%'C_MCPAG%$n_HGF:,&)%$K_GGFWF:FUF:FN%&DNA_aGF:F&,
I-time_intvoutF7F&,
I0equilibriumeqns=F&%&falseGE\[l#F:,&%(CS_MCPAGF:*&%#KFGF:)FV%#nFGF:FNF;,&%%mRN
AGF:FSFNF&,
I#Dt$F:!"$F&,
I'nopt_vF%F&,
I&rate3*&FenF:%$a_aGF:F&,
I"T$"&:'HFFF&,
I)dDNA_adt,&%#r1GF:%#r3GFNF&,
I+nreactions"")F&,
I)bio_name7/%'mu_maxGFWFZ%$K_MG%#YcGFio%$a_rG%$rhoG%#wsGF`oF^o%&f_CO2GFTF&,
I)tot_time$"(,++"FeoF&,
I)_UIUtilsy6,%)_WindowsG%0_EvalWithLabelsG%(_ToDotmG%0VariableManagerG%,wbAddLi
bRefG%/wbRemoveLibRefG%.GetWorkbookDBG%2GetWorkbookTempDBG%3UpdateExplorerTreeG
%2ClearSessionCacheG6%%+trampolineG%"_G%1BuiltinInterfaceG,GI(:-26522GQJC:\Prog
ram~Files\Maple~2017\lib\maple.mlaF&GI(:-26523GFarGI(:-26524GFary6(%4ListActive
VariablesG%5AddToVariableManagerG%:RemoveFromVariableManagerG%3ListSavedVariabl
esG%*extravarsG%+hiddenvarsG6+%,typesummaryG%/libtypesummaryG%-valuesummaryG%2s
avedVariableInfoG%*mergeSetsG%)dagnamesG%/SavedVarsCacheG%-SavedVarsLibG%1Saved
VarsModTimeG(t+6%>'%'formatG<%-%*identicalG6#%#tvG-F]t6#%%typeG-F]t6#I&valueG6$
%*protectedG%(_syslibGFet>'%$libG%'stringGQ!F&>'%%sizeG%'posintG"#D6%%"xG%&name
sG%"rG6"6"C%>8%-%&minusG6$<$-%'anamesG6#.%'activeG-%#opG6#T%T'@'/9$Fbt>8&-%$map
G6$f*6#FduFhu6$%)operatorG%&arrowGFhu/F\w-Fhv6$7#-%%evalG6$9$F;/._F&F`uT$FhuFhu
6&F`u9&F]sT-F[v/F\wFet>F^w-F`w6$f*FcwFhu6$FewFfwFhuFgwFhuFhu6&F`uFdxF_sT/F[v>F^
w-F`w6$f*FcwFhu6$FewFfwFhu7%-%(convertG6$F^xF\uFhw-FivFiwFhuFhu6(F`uFdxF]sFexF_
sF]yF[v@%09%F]u-T+6&F^w-T)6%F[zF\wFdxF\wFdxF^wFhuFhu60%6_thismoduledefinitionGF
&FjrI*extravarsG/%+modulenameGI0VariableManagerG/FfzF_qF[sI+hiddenvarsG/FfzFgzF
irI3ListSavedVariablesG6$I(:-26539GFar/%'_localG%,_n616659488GFasI*mergeSetsG6$
I(:-26546GFar/F_[l%,_n617170096GF]sI,typesummaryG6$I(:-26542GFar/F_[l%,_n617169
976GF_sI-valuesummaryG6$I(:-26544GFar/F_[l%,_n617170056G6#F%/FfzFgzGI(:-26537GF
arGI(:-26538GFarGF][l<"Fez<"Fjz+GFh[lGI(:-26543GFarGF]\lGI(:-26545GFarGFc[lGI(:
-26547GFarGI(:-26548GFarGI(:-26549GFarGI(:-26550GFarb6#%+thismoduleGF\sF&FerF&F
&F&F&F&FhzGI(:-26526GFarGI(:-26527GFarGI(:-26528GFarGI(:-26529GFarGI(:-26530GFa
rGI(:-26531GFar%GI(:-26532GFarGI(:-26533GFarGI(:-26534GFarb6#F^]lF\r6"FaqFj]l6#
QYinternal~package~of~utilities~for~Maple's~user~interfaceFj]lFj]lFj]lF&Fht,
I&rate4*&%&DNA_rGF:FhpF:F&,
I&rate2,$*.FepF:)FV,&FWF:F:F:F:FXFN,&FfpF:FVF:FNFenF:FgpFNFNF&,
I$viqF%F&,
I"Df*6#'%"fG<(%&arrayG%%listG%$setG%*algebraicG%)equationG%*procedureG6.%$OprG%
&IndexG%"dG%"iG%"nG%$solG%"gG%$idxG%"FG%#_FG%'Index2G%5f_is_a_math_functionG6#%
aoCopyright~(c)~1993~by~the~University~of~Waterloo.~All~rights~reserved.G6"C+@&
09#F:Y6$Q=expecting~1~argument,~got~%1Fb`lFf`l-Fbt6$9$.<&F]_lF^_lF__lFa_lO-F`w6
$9!F\al>8$-%,D/_procnameG6$Fbal.8%-%)userinfoG6(F>.Fg^l%*Applying~GFdal%$to~GF
\al@%/Fial%%NULLGFb`l@*/Fial7"OF\al-%1tools/membertypeG6$.-%$AndG6$%(numericG-%
$NotG6#FauFialYQBindices~must~be~positive~integersFb`l4-Fbt6$Fial.-F^_l6#%(inte
gerGC$@*-Fbt6$F\al.%5PDEtools/D/structureGC%>8*-Ffv6$F%F\al@*/FcdlFg^lFb`l'Fcdl
.-%#@@G6$-F]t6#Fg^l%)anythingG>8+-%"$G6$F:-Ffv6$F;Fcdl'Fcdl.-F[el6$-%*specindex
G6$F_elFg^lF_elC$>6$Fcdl8(-Ffv6#Fcdl>Fael-%$seqG6$-Fcel6$8'Fafl/FjflFcdl'Fcdl.F
[fl>FaelFbfl@$-%)assignedG6#FaelC&>Fial-%+D/sort_idxG6#7$Fael-Ffv6#Fial>Fdal&Fg
^l6#Figl>Fcdl-Ffv6#F\alO-%%subsG6$/8,Fdal-.FfhlFcfl4-Fbt6$F\al.<$%"*G%"+GC$>6$8
&8.-%-D/assuming_1GFjgl@'0FdilFialO-&Fbal6#-Ffv6#Fdil6#9"3/-%-D/assuming_2GFjgl
QCNotZeroDollarDifferentiationIndiceFb`l'F\al.%)constantGOF%C%@$3'F\al.-F\cl6$%
'symbolG%@D/procedure_or_applyable_moduleG-Fhbl6$.-Fcel6$FjclF`_lFdilC$Z%>Fcil-
%'D/diffG6&FbalF\alF\al.8/Fb`lYFb`l@$0Fcil%%FAILGO-F\x6$FcilF:@%'-%+attributesG
6#FbalFidl>FcilFi\m>Fcil&F]blF]hlO-Fchl6$/FfhlFcil-FhhlF`hl-Fbt6$F\al.F_ilO-F`w
6$FdalF\al-Fbt6$F\al.F^ilC$>Fcdl-%-selectremoveG6%FbtF\alFgjl@%/&Fcdl6#F:F:O-%'
subsopG6$/F%FdalFc]mO*&Fd^mF:-Fdal6#&Fcdl6#F;F:OFg^m2F:-%%nopsGFjgl@%3'F\al.-F
\cl6$Fa[m-F`cl6#Fb[m4'(%#D/GF\al.Fb[m@%-%#isG6$F\alFgjlOF%C$>Fial-FfglFjglO-Fh^
m6$/F%F\hlFc]mO-&Fg^l6#&FialFe^m6#-&Fg^l6#-Ffv6#&Fial6#;F;Fc_mF`hl@.5-FbtFe`m/-
%*traperrorG6#Fc`m%%trueGOF%Fd]mOFh]mFj]mC%>8)F%?(FjflF:F:-Fd_mF`hlFcbm>Fhbm,&-
F\x6$FhbmF:F:-Fh^m6$/Fjfl-Fdal6#-Ffv6$FjflF\alF\alF:OF]cm-Fbt6$F\al.%"^G@%-Fbt6
$-Ffv6$F;F\alFgjlO*(F^dmF:-Fdal6#-Ffv6$F:F\alF:)Fddm,&F^dmF:FNF:F:O-Fchl6$FehlF
c]m5/F\alF]bl-Fbt6$F\al.%*D/partialGYQ2function~expectedFb`l-Fbt6$F\al.%)functi
onGC%-F[bl6(F?F]bl%9function~case:~applying~GFdalF_blF\al@,/Fddl.%"@GC%?&FcdlF
\alFcbm@$5Fgdl-Fbt6$FcdlF_emYFbem-F[bl6%FMF]bl%-Composition~G@'-%0D/isnonmathfu
ncGFcdmO-F^fm6$Fddm-Fdal6#-%$D/@G6#-Ffv6$;F;FjbmF\al4-%$hasG6$F\alFg^lO*&-F^fm6
$Fbdm-F^fmFcgmF:F_gmF:C$>Fcdl-F`w6$w,6#FduFb`l6"Fb`l@$3Fcem4-Figm6$FddlFg^l7#F_
hlFb`lFb`lFb`l6#F:6%7&Q/>lib/src/D.mplFb`l"$E#"%f")"%J#)7&F`imFaim"%n")"%E#)7&F
`imFaim"%<#)"%B#)F\im@$4-Figm6$FcdlFg^lOF\hm/Fddl.Fbgm@%3/FjbmF:FjfmOF:O-Fdal6#
-F^fm6#F_hl/Fddl.F[elC$-F[bl6%FMF]bl%5repeated~applicationG@*5/FddmFdal-Fbt6$Fd
dmF_emYFbemFjfmOF\al/F^dmFNO*$-F^fm6$Fbdm-F[el6$FddmFNFN-Fbt6$F^dm.FauO*&-F^fm6
$Fbdm-F[el6$FddmFgdmF:-Fdal6#Fe\nF:/Fddl.%&DESolGO-%(D/DESolGF`hl-Fbt6$Fddl.-F[
el6$F`emF_elC%>Fafl-Ffv6$7$F%F;F\al>Fcdl-&Fg^l6#-Fffl6$Fhfl/Fjfl-Ffv6$7$F%F:F\a
lFijmO-Fdal6#-F\x6$FcdlF:@%/FdalF]blC)-F[bl6%F>F]bl%Bclean~up~nested~applicatio
ns~of~DG>FaflF:>FcdlF\al?(Fb`lF:F:Fb`l-Fbt6$FcdlFeem@)/-Ffv6$F%FcdlF]blC$>Fafl,
&FaflF:F:F:>FcdlFbfl-Fbt6$Fe_nFidlC$>Fafl,&FaflF:-Ffv6$Fh]nFcdlF:>FcdlFbfl-Fbt6
$Fe_nF_em@'-%.D/hasbadindexG6#Fe_nYQ=univariate~function~expectedFb`l-%.D/all1i
ndexedG6$Fe_n.FjflC$>Fafl,&FaflF:FjflF:>FcdlFbfl[Fcan@$3-Fbt6$FcdlFj\n1-%,DESol
/orderGFcflFaflO-%*D@@/DESolG6$FaflFcdl-F[bl6&FMF]bl%7inner~most~operand~is~GFf
^n@%/FaflF%OFf^nO-Fchl6$/.8--F[el6$Fg^lFafl-FibnFe^nC)-F[bl6%F>F]bl%Gclean~up~n
ested~applications~of~D[i,j]G>FialFigl>FcdlF\al?(Fb`lF:F:Fb`lFa_n@)Fd_n@'-Fg`n6
#&Fg^lFjglYQ7function~is~univariateFb`l/<#Fial<#F:C$>Fial6$FialF:>FcdlFbflFcanF
c`nC'>FfhlFcdl>Fafl-FfvFh`n>FcdlFbfl@$3333/-Ffv6#FdalFial'FialF`\n'Fcdl.Fa[m4-%
'memberG6$Fial<#Fafl'-Fh^m6$/F%Fcdl.-FcdlFb`l.%8PDEtools/known_functionGZ%C$>Ff
hl-F\\m6&FdalFcdlFcdlF^\m@$'FfhlFa`mO-&Fg^l6#Fafl6#FfhlFb`lYFb`l>Fial6$FialFafl
F[`n@'FgcnYF[dnF\dnC$>Fial6$Fial-Fcel6$F:F``n>FcdlFbflFcanFcan>Fial-Ffgl6#7#Fia
l>FdalF\hlO-Fh^m6$Fj^m-FhhlFe^n@$-F[gmF`hlOF\al@$-Fbt6$F\al%%nameGC(-F[bl6%F>F]
bl%=Either~a~name~or~a~procedureG@%-Fbt6$F\al%(indexedGC$>FcdlFddl>FaelF_hlC$>F
cdlF\al>FaelFbbl>Fcil(F``mFcdl-F[bl6&F>F]bl%,Looking~forGFcil@&-Fbt6$FcilFa`mC$
-F[bl6%F>F]bl%:Applying~pre-defined~ruleG@'/FdalFg^lO-Fcil6$FeblFael/Fc_mF:O-Fc
il6$FialFaelO-&Fg^lFham6#-Fcil6$7#FbamFael'Fcdl.-%#OrG6$Fb[m-F]t6-_Fb`l%(fourie
rG_Fb`l%+fouriercosG_Fb`l%+fouriersinG_Fb`l%+invfourierG_Fb`l%'hankelG_Fb`l%(hi
lbertG_Fb`l%+invhilbertG_Fb`l%(laplaceG_Fb`l%+invlaplaceG_Fb`l%'mellinG_Fb`l%*i
nvmellinGC%-F[bl6&F>F]blFiin(%&diff/GF\alZ%>Fcil-F\\m6&FbalF\alFcdlF^\mFb`lYFb`
l@$Fb\mOFe\m-F[bl6%F>F]bl%5No~pre-defined~rulesG@$30F_\mFcbm-Fbt6$F\al.Fb_lC$>F
cil-%,D/procedureG6$F\alFial@$Fb\mOFe\mFg^mFb`lFb`lFb`l6$FgtFht,
I'ncompoF?F&,
I3debugger/no_outputFinF&,
I+currentdirf*6#'%"sG<$F\uFa[m6#Ffu6#%inCopyright~(c)~2001~by~Waterloo~Maple~In
c.~All~rights~reserved.G6"C%@)5/9#F%-Fbt6$9$.F\u>8$-%&iolibG6$"#F9"-Feen6$F^`o7
'._Ff_o%'bindirG._Ff_o%(datadirG._Ff_o%(homedirG._Ff_o%)mapledirG._Ff_o%+toolbo
xdirG>Fa`o-Fc`o6%Fe`o-%+kerneloptsG6#F^`o&Ff`o6#;F;FN3/F^`o._Ff_o%-worksheetdir
G-%5IsWorksheetInterfaceG6#._Ff_o%)StandardG>Fa`o-Fc`o6%Fe`o-I*interfaceG6$FgtF
htF^boF_bo>Fa`oFb`o>%(libnameGFecoFa`o6#%NQueries~and/or~changes~the~current~di
rectory.G6#FecoFf_o6$FgtFht,
I+switchlist7#%$sw1GF&,
I(sprintff*6"F_do6#%^oCopyright~(c)~1994-1998~by~Waterloo~Maple~Inc.~All~rights
~reserved.GF_do-Fc`o6$F79"6#%YPrints~expressions~to~a~string~based~on~a~format~
string.GF_doF_do6$FgtFht,
I$T_C$"#BF%F&,
I(bio_val7/$F)F%Fdo$F7FeoF^eo$F<FNFEF#$"#7FNFL$"##*FFF6$FbpFNF(F&,
I,file_rnames7*%'xrate1G%'xrate2G%'xrate3G%'xrate4G%'xrate5G%'xrate6G%'xrate7G%
'xrate8GF&,
I$Yc_F_eoF&,
I,maxspmeas_vF%F&,
I%n_H_FdoF&,
I+type/localw,6$%%exprG%$typG6"6"Fgfo@'/9#F:3-Fbt6$9$.Fa[m0F_go-%$catG6#F_go/F[
goF;3F\go-Fbt6$F_go-.Ffhn6#9%Y6$QPexpecting~at~most~one~argument,~but~received~
%1Fgfo,&F[goF:FNF:FgfoFgfoFgfo6#F;6'7&Q8>lib/type/src/local.mplFgfoF="#b"$L$7&F
dhoF>"#u"$C$7&FdhoF?"#%*"$R"7&FdhoFbp"$k""$T#7&FdhoF7"$^#"$>$Fht,
I)nroutputFbpF&,
I'nparam"#8F&,
I)opt_nameF,F&,
I&rate8,$*0FepF:Fc^lF:FXFNFe^lFNFenF:FgpFN,&F:F:*,FipF:FjpFNF`oF:F^oF:)FV,&F`oF
:FNF:F:F:FNFNF&,
I+listsolids7'F:F;F=F>F?F&,
I&dir_fQIC:\Users\sanew\Desktop\BRNSPackage-MT_SKF&F&,
I2PackageManagementy6$%(pmemberG%)pexportsG6.%-pcompletionsG%.ReadUsersMindG%&p
listG%%noteG%'unnoteG%*assigned?G%(gassignG%%keysG%(unwith?G%-with_indexedG%-ex
ecUserInitG%/execSystemInitG$GI(:-21411GFarGI(:-21412GFar.GI(:-21413GFarGI(:-21
414GFar7"/FfzFbjoGI(:-21416GFarGI(:-21417GFarGI(:-21418GFarGI(:-21419GFarGI(:-2
1420GFarGI(:-21421GFarGI(:-21422GFarGI(:-21423GFarGI(:-21424GFarb6#F^]lFgjo6"Fd
joFe\p6#Q=Package~management~utilitiesFe\p6%%%withG%'unwithGI)packagesG6$FgtFht
Fe\pF&6$FgtFht,
I&valuet+6%F[_l%#~$G>'%2valuateinertnamesG%*truefalseGFcbm6-%$ansG%-inertindexe
dG%-inertsymbolsG%/inertfunctionsG%"NG%5inertfunctions_namesG%"jG%7non_inert_pa
ckage_nameG%0package_commandG%+percentageG%$tmpG6#%aoCopyright~(c)~1992~by~the~
University~of~Waterloo.~All~rights~reserved.G6"C-@$-%(hastypeG6$9$<%-%0CALCULUS
1OBJECTG6$.F^_l.F__l-.%%EvalG6$.F_el/Fe_p.%&rangeG-.%$IntG6$Fe_p/Fe_p;.%"=GF_`p
O-__%(StudentG%*Calculus1G%&ValueG6#Fj^p@%9&C$>6$8%8'-F`^m6%Fbt-%'indetsG6$<$-F
`w6$Ffv-Fcap6$Fj^p.%&tableGFj^p.<$FfhnFfemFfhn>6$F^ap8&-F`^m6%FbtF^ap.F^in>6%F^
apF`bpF_ap6%<"Fgbp-Fcap6$Fj^p.Ffem@$/6%F_apF^apF`bp6%FgbpFgbpFgbpOFj^p>8$Fj^p>F
_ap-%%map2G6%FfvF%F_ap@$3Fj`p0F_bp6$FgbpFgbpC'>8--Fey6$Q"%F&Fa[m>F^ap-%'selectG
6$f*6#%"uGFd^p6$FewFfwFd^p3'-Ffv6$F%Fj^p.Fa[m/-%*substringG6$Fjdp;F:F:T#Fd^pFd^
p6$F`^pF\dp-%&unionG6$F^ap-Fbdp6%FbtF_apFcbp>F`bp-Fbdp6$f*FedpFd^p6$FewFfwFd^p/
-F_ep6$Fj^pFaepFbepFd^pFd^pFcepF`bp>F^ap-F`w6$%.value/indexedGF^ap@$0F^apFgbp>F
acp-F\x6$FacpF^ap>F_ap7#-Ffv6#F_ap>8)-F`w6$f*6#FduFd^p6$FewFfwFd^p@%'Fj^p.<$F^i
nFfemFjdpFj^pFd^pFd^pFd^pF_ap@$0F_gp7"C$>F_gp-F`w6$%-value/defineGF_gp@$FjgpC)>
8.-F`w6$%$rhsGF_gp>F_ap-Fbdp6$f*FedpFd^p6$FewFfwFd^p33'Fj^pFcbp/-Fd_mFh`pF:'-Fc
hl6$FbepFjdp-.F\cl6$.%(packageG-.%*satisfiesG6#f*6#%"vGFd^p6$FewFfwFd^p-Feen6$F
j^pFbepFd^pFd^p6$Fa^pT%Fd^pFd^p6&F\^pF_gpFa^pFdhpF_ap@$0F_apF[hpC&>8(-Fd_mF]gp>
F_ap-%&ArrayG6$;F:F[[qF_ap?(8*F:F:F[[qFcbmC&>8,&F_ap6#Fc[q>8+-Fchl6$F_gp-Ffv6$F
%Ff[q>Fdhp-%@tools/GetEvaluatedPackageExportG6$Fj[q-Ffv6#Ff[q@%0FdhpFbblC$>Ff[q
-w,6$%-package_nameG%-command_nameGFd^p6"Fd^p.&Fj^p6#.9%Fd^pFd^pFd^p6#F;6$7&Q3>
lib/src/value.mplFd^p"$5""%nS"%MT7&Fg]qFh]q"%+T"%HT6$Fj[qFdhp>Fg[q/Fg[qFf[q>Fg[
qFbbl>F_ap7#-Fffl6$Fg[q/Fc[qFa[q>F_ap-F`w6$f*FedpFd^p6$FewFfwFd^p@%/-FghpFh`p._
Fd^p%$sumG-Fh^m6$/F;f*Fd^pFd^p6$FewFfwFd^p-Fa_q6#9"Fd^pFd^pFd^pFj^pFj^pFd^pFd^p
Fd^p7$F\gp-Ffv6#F_gp>6$FdhpF_ap-F`^m6%F_`pF_ap./%*%assumingG%)assumingG@$0FdhpF
[hp>Facp-&Fchl6#._Fd^pF\x6$FdhpFacp>Facp-F\x6$FacpF_ap@$3Fj`p0F`bpFgbpC$>F`bp-F
`w6$%-value/symbolG-Fbdp6$f*FcgpFd^p6$FewFfwFd^p-Figm6$FbepFj^pFd^pFd^p6$Fg]pFa
cpF`bp@$Fcaq>Facp-F\x6$FacpF`bp@'/FacpFj^pFj^p3/Facp.Facp'Facp.%/last_name_eval
G-F\x6#FacpFacpFd^pFd^pFd^p6#F;Fft,
I-bnddata_downFCF&,
I.file_in_names7(FenF_^lFV%$CO2GF\oFboF&,
I&rate1*,FepF:Fc^lF:FXFNFe^lFNFenF:F&,
I+dCS_MCPAdtF/F&,
I&vpor0F_eoF&,
I$nF_FbeoF&,
I*depth_max$F7FNF&,
I'varea0FicqF&,
I,Typesettingy6[q%*_pexportsG%#mnG%#miG%#moG%$mioG%&mtextG%'mspaceG%#msG%'mglyp
hG%%noneG%%mrowG%&mfracG%&msqrtG%&mrootG%'mstyleG%'merrorG%(mpaddedG%)mphantomG
%(mfencedG%)mencloseG%%msubG%%msupG%(msubsupG%'munderG%&moverG%+munderoverG%.mm
ultiscriptsG%,mprescriptsG%)mscriptsG%'mtableG%$mtdG%$mtrG%+mlabeledtrG%+malign
markG%,maligngroupG%(mactionG%(mparsedG%+mambiguousG%*mverbatimG%*mcompleteG%&m
failG%,mprintslashG%(mprimedG%)mpatternG%(matomicG%&maddrG%'memptyG%+msemantics
G%)mmaple1dG%&ParseG%(TypesetG%)ToMathMLG%+FromMathMLG%5QueryCompletionRulesG%+
NeedsBraceG%,EntitySplitG%-EntitySplit0G%$ASMG%2ProcessIniOptionsG%.GetIniOptio
nsG%5ParseToMathMLContentG%6PresentationToContentG%*AddAtomicG%-RemoveAtomicG%1
ProcessRuleTableG%7StripDefaultAttributesG%&HTML5G%-CheckBindingG%*delayDiffG%0
delayDotProductG%2delayCrossProductG%.delayGradientG%/delayLaplacianG%%TypeG%#E
VG%#ADG%&_HoldG%-_HoldToInertG%0_HoldToInertRecG%.RuleAssistantG%0EnableParseRu
leG%1DisableParseRuleG%/QueryParseRuleG%2EnableTypesetRuleG%3DisableTypesetRule
G%1QueryTypesetRuleG%5EnableCompletionRuleG%6DisableCompletionRuleG%5SpecialFun
ctionRulesG%)SuppressG%+UnsuppressG%)SettingsG%&StateG%4UseSymbolForTypesetG%5C
onvertSymbolOnParseG6it%+ModuleLoadG%(mcomseqG%(margseqG%$varG%'varseqG%'vartbl
G%)mdisplayG%(minertcG%(AllTagsG%/GlobalToExportG%3SemanticAttributesG%7Semanti
cAttributeTableG%:SemanticAttributeDefaultsG%,NonSemanticG%,CanBeAtomicG%(Scrip
tsG%&TSexpG%)ColorMapG%0ProcessColorMapG%,ColorToNameG%:StripDefaultAttributesR
ecG%9ProcessEscapedCharactersG%.SemanticTableG%0NormalizeAtomicG%0StripFormatti
ngG%2AllowedAutoAtomicG%$ATBG%7ProcessCompletionRulesG%0CompletionRulesG%3AddCo
mpletionRulesG%6RemoveCompletionRulesG%&RulesG%(AddRuleG%3DisabledParseRulesG%5
DisabledTypesetRulesG%8DisabledCompletionRulesG%5SuppressDependenciesG%'SetTblG
%:ProcessOperatorDuplicatesG%4OperatorConversionsG%-UseOpTypesetG%,ConvOpParseG
%.GlyphToStringG%.StringToGlyphG%+PrefixListG%3DisplayPrefixTableG%1ParsePrefix
TableG%0UnicodeToEntityG%/OperatorDupMapG%1OperatorParseMapG%6OperatorMultiPars
eMapG%3OperatorParseKnownG%;OperatorStringTranslationsG%1OperatorInversesG%5Ope
ratorEquivalencesG%(InverseG%+InverseMapG%*LeftFenceG%+RightFenceG%*BothFenceG%
+QuotePairsG%*SeparatorG%.VertSeparatorG%)AllFenceG%*UglyFenceG%.LeftOnlyFenceG
%*ConvFenceG%'INTNEGG%'INTPOSG%)RATIONALG%&FLOATG%'HFLOATG%(COMPLEXG%'STRINGG%%
NAMEG%'MEMBERG%)TABLEREFG%'DCOLONG%)CATENATEG%&POWERG%%PRODG%'SERIESG%,EXACTSER
IESG%$SUMG%%POLYG%#FNG%)EQUATIONG%(INEQUATG%'LESSEQG%)LESSTHANG%$ANDG%$NOTG%#OR
G%$XORG%(IMPLIESG%$SEQG%%LISTG%&RANGEG%$SETG%'ASSIGNG%(STATSEQG%&TABLEG%(HASHTA
BG%%HASHG%'RTABLEG%'ZPPOLYG%'UNEVALG%%PROCG%&PARAMG%&LOCALG%(LEXICALG%$FORG%#IF
G%%STOPG%&ERRORG%'RETURNG%&BREAKG%%NEXTG%'BINARYG%$TRYG%%READG%%SAVEG%$USEG%'SD
POLYG%'MODDEFG%'MODULEG%(GARBAGEG%(FOREIGNG%(CONTROLG%%DBUGG%(NumericG%)CNumeri
cG%%NameG%*AlgebraicG%(BooleanG%+RelationalG%(funcargG%(FuncArgG%*StringMapG%'t
InertG%#FIG%+ProcMspaceG%+ITimesReplG%(KeywordG%(NewLineG%)SupPrimeG%,InlinePri
meG%-LinkExternalG%$AsmG%4ExportNameToiMEMBERG%/IsOverloadProcG%3GetOverloadBin
dingG%.CheckEquationG%*NumFormatG%-NumFormatterGFg_l%)doprimedG[qGI':-5563GQKC:
\Program~Files\Maple~2017\lib\update.mlaF&G6$Fgt/FfzF[dqG6$Fgt/FfzF[dqG6$Fgt/Ff
zF[dqGI':-5567GF[drGI':-5568GF[drG6$Fgt/FfzF[dqGI':-5570GF[drGI':-5571GF[drGI':
-5572GF[drG6$Fgt/FfzF[dqG6$Fgt/FfzF[dqGI':-5575GF[drGI':-5576GF[drGI':-5577GF[d
rGI':-5578GF[drGI':-5579GF[drGI':-5580GF[drG6$Fgt/FfzF[dqGI':-5582GF[drG6$Fgt/F
fzF[dqG6$Fgt/FfzF[dqGI':-5585GF[drGI':-5586GF[drGI':-5587GF[drGI':-5588GF[drGI'
:-5589GF[drGI':-5590GF[drGI':-5591GF[drGI':-5592GF[drGI':-5593GF[drGI':-5594GF[
drGI':-5595GF[drGI':-5596GF[drGI':-5597GF[drGI':-5598GF[drGI':-5599GF[drGI':-56
00GF[drGI':-5601GF[drG6$Fgt/FfzF[dqGI':-5603GF[drG6$Fgt/FfzF[dqGI':-5605GF[drGI
':-5606GF[drGI':-5607GF[drGI':-5608GF[drGI':-5609GF[drG6$Fgt/FfzF[dqGI':-5611GF
[drGI':-5612GF[dry6*%4ProcessTypesetRulesG%.LoadFunctionsG%'KernelG%+KernelTo2D
G%/KernelHelpTo2DG%)TdisplayG%+SimpleSignG%BRemoveMessageFromSymbolicSequenceG6
N%#TnG%#TiG%%TrowG%%TsubG%%TsumG%)TproductG%'TpowerG%*TsequenceG%)TbracketG%(Tf
encedG%(TprimedG%)HasAssumG%,IntToStringG%2PrintPreprocessorG%,ModuleApplyG%*ap
plypropG%+tomscriptsG%-applyaliasesG%-TypesetRulesG%)iEDigitsG%*iEDBeforeG%)iED
AfterG%(iETermsG%*iETBeforeG%)iETAfterG%'iDPrecG%(iRTSizeG%*iSAssumedG%'iIUnitG
%/iPhysicsColorsG%0iPhysicsVectorsG%.greek_lettersG%8greek_letters_of_lengthG%-
greek_gliphsG%1PhysicsFunctionsG%+PrintInertG%-PrintInertDoG%0PutSuperscriptsG%
/GetRootOfIndexG%3GreekLetterToGliphG%1GivePhysicsColorG%)p_in_pFqG%-FormatNumb
erG%=NormalizeCompositionOperatorG*GI':-5901GF[drGI':-5902GF[drt+6'>'%,convertt
o2dG%(booleanGFin>'%=normalizecompositionoperatorGFe]pFcbm>'%2numericformatting
GF^_lF,>'%*stripholdGFe]pFcbm>'7$%1typeset_argsonlyG%)argsonlyG<$Fg[sF^_lFin6$%
#rgG%#fpG6"6"C&@$/%7_Env_Debug_TypesettingGFcbmC%>8%-%&fopenG6$-%#ifG6%/-F]bo6#
.%)platformGQ(windows6"Q/C:/typeset.datF_^sQ-/tmp/typesetF_^s.%'APPENDG-%(fprin
tfG6&Fb]sQ=Kernel:~got~%d~arguments~%a|+F[]s9#7#9"-%'fcloseG6#Fb]s>8$p>%0_EnvTy
StripHoldGFcbm-%+subsindetsG6%-T'6$-T%6#F__sr.-%)specfuncG6#T)f*6#FfdpF[]s6$Few
FfwF[]s-Fh^m6$/F;-Fd_s6%-Ffv6$F;F^x.-F_`s6#T#f*6#F`jpF&6$FewFfwF&Fj`sF&F&F&F^xF
[]sF[]s6$FefqFa`sF[]sF[]s6*FczF&FhhqI#EVG6$Fgt/FfzF[dqFbirI,ModuleApplyG/FfzI(T
ypesetG6$Fgt/FfzF[dqFefqI*mcompleteGF[gr6#F%/FfzFjasGI':-5904GF[drGI':-5905GF[d
rf*6#%&expr0G6:Fefo%%flagG%'prefunG%$bdsG%%lbdsG%%dotmG%)overnameG%$arrG%#t1G%#
t2G%#t3G%#t4G%#t5G%#t6G%#s1GFg_lF]^p%"kG%4LOCAL_substitutionsG%.alias_contentG%
)new_exprGFf_l%&greekG%(opacityG6#%%lockGF&C*-FhvF&>8%Fcbm>8&-Fg]s6%2F:9#&9"6#F
;Fin>8$F^x>8,7#-%,disassembleG6#Fjds@$3/&F\es6#F:Fiv/-%(pointtoG6#&F\esFhds_F[d
qFefqO-FhesF`es@&3/FdesT)/Fges._F&%(PhysicsGC$>Fjds-%*addressofG6#-%&parseG6#-F
ey6$F]fs.F\u>F\esF]es330%0_EnvTypesetTo1DGFcbm2F;-Fd_m6#F\es-Fagl6#&_I&aliasG6$
FgtFht%>ContentAddressToGlobalAddressG6#&F\es6#F<C&>FjdsF]fs>87-FhesF`hs>88-Fch
l6$/Ffhs&_F]hs%0ContentToGlobalG6#FfhsFjds@$0FihsFjdsO-9!6#-Fifs6#Fihs@io-Feen6
$FdesT+-&T-6#F_dsF`es/FdesT/C%>8-F]fs@$/%0_EnvConvertTo2DGFcbm>Fejs-T16$Fejs.%(
reverseG-T56#-T36#Fejs-Feen6$Fdes<%FafsT7T9C+>%6_EnvTypesettingNoOperGFcbm@'/Fd
esFh[t@%-Feen6$Q/&colon;&colon;F&T;C$>81Q(&Colon;F&>F_dsFcbm>Ff\tFb\t/FdesFi[t@
%-Feen6$Q1&verbar;&verbar;F&Fc\tC$>Ff\tQ'&Vert;F&>F_dsFcbm>Ff\tF^]t>Ff\tQ/&colo
n;&minus;F&>Fejs-Fg]s6%/FgesFbblFbbl-&T=F`jsFies@%3-Feen6$Ff\t<$Fg\tFb\tFdgsC%>
%-_EnvTyIsTypeGFcbm>8.-F[^tF`hs>Fd^t.Fd^t>Ff^tFg^t@$F^^t>Fd^tFcbm@$3F^\t-T?6%Fj
esFh[t.%%leftG>Fejs-TAFd[t@$3F^\t-F`_t6%FahsFh[t.%&rightG>Ff^t-Ff_t6#Ff^t@$3Fj
\t-F`_t6%FahsFi[tF[`t>Ff^tF^`t-TE6%Fejs-TC6#Ff\tFf^t3/FdesTG55/FghsFbbl/FegsFcb
m/%;_EnvConvertPhysicsHelpTo2DGFcbmC%>8/-&F\^t6#Fcbm6$FjesFads@$-F`_t6%FjesFivF
b_t>Ffat-Ff_t6#Ffat@%F`at-Ff`t6$Ffat-Ff_t6$/.%%openGQ'&lsqb;F&/.%&closeGQ'&rsqb
;F&C$>Fejs-Fhat6$FahsFin-Ff`t6$Ffat-Ff_t6%FejsFfbtFjbtF\atC%>6%Fejs80Ff\t6%7#-F
_esFies7#-F_esF`hsFin@%30&FejsFeesTI0FbdtF]atC$>FfatFgat@$-F`_t6%FjesF]atFb_t>F
fatF_btC$>Ff^tFges@%50-Fd_m6#7#Ff^tF:-Feen6$Q.PackageMemberF&TKC$>Ffat-TM6%-Fha
tFiesFjesFjds@$Fhdt>FfatF_btC&@$/FbdtF]at>Ff^t-F\xF_`t@$/F`etF:C$@$53-Fbt6$Ff^t
.F[bp/<#-Fj\mF_`t<$._F&Fht._F&Fgt3-Fbt6$Ff^t.%'moduleG-Fbt6$Ff^t.Fiip>Ff\t-%&ev
albG6#0-%*intersectG6$<$F\ht.FgtF^gt<"@$55330F\\tFcbmFads5-Feen6$Ffht7#F_gt/&-F
ey6$Ff^tF`gs6#;F:F:Q"&F&/Ff^tFg^lFf\t>%@_EnvTypesettingRomanIdentifiersGFcbm>Ff
atFiet@$30F[jtFcbmFhdt>FfatF_bt@)3/%4Physics/InitializedGFcbm5/Ff^t-F\x6$_Fefs%
#a-GF:/Ff^t-F\x6$_Fefs%#a+GF:C$>Ff^t-FhatF`hs-TO6$Ffat-Fg]s6%2F:F`et-Ff`tF_`tFf
^t/-Fd_m6#FictF:-Fd[uFcbt3Ff\t4Fcet-Ff`t6$Ffat-Ff_t6%Fb[uFfbtFjbt-TQ6#-Fd[u6$Ff
at-Fjet6%Fb[uFahsFjds/FdesFcdtC(@$FaatO-TS6#-F]do6$Q#%aF&F]fs@$-TUF`esO-TW6#-F]
do6$Q$%ZmF&F]fs>Ff^tF]fs@$3Feft53F\it55F_it-Feen6$.FhtFaitFbitFiit>F[jtFcbm>Ff^
t-&TYFiatF`es@%5Fcjt/%<Physics/Vectors/InitializedGFcbmC$@$'Ff^t.-F`]u6#F\uC$>6
$898:6$&-Ffv6$F:Ff^tFees&F_`u6#;F;FN@$3'F[`u-.Fd[o6$Q"dF&Q"DF&'F\`u-Fh`u6#-Ffv6
#Ten@$'F]fs.%'globalGC&>F\`uFa`u>F[`uF^`u>Ff^t-Fh^m6$/F:-F]do6%Q'%A&%A;F&F[`uF
\`uFf^t>Ff^t-Fh^m6$/FN6$-Ffv6$FNFf^t/TgnQEPhysics~differential~of~a~coordinateF
&Ff^t@%-Feen6$./FhbuQ'atomicF&Ff^t-Fjet6%Ff^tFjdsFjdsFf^tFf^t3/FdesTinFaat-T]o6
$Fjes-&T[oFiat6%FahsFdcuF[`tFccuC%>FejsF]dt@&/FbdtT_oC$>83Fghs@%/FcduFNO-Tco6$-
Tao6#Q"1F&-Ficu6$FjesQ%evalF&C$>Fejs-Tgo6$7%FdcuFjes-Fifs6#,$FcduFNTeoO-Fhdu6$F
jdu-FhatFd[t/FbdtTioC$>Fcdu*$FghsFN@&/FcduF;O-T[p6#F\ft-Fbt6$Fcdu.FauO-T]p6$F\f
t-&F_jsFiat6#-Fifs6#FcduFecu/FdesT_pC)>82F:>Fjgu.Fjgu>6%FejsFf^tFfat-Tap6$FjdsF
jgu@$5/FejsF,/Ff^tF,C$>Fejs7$-FfvFd[t-FfvF`bt>FfatF,@'/-Fd_mFd[tF%>FejsFjdu/F^i
uF:>Fejs-F\x6$Fbdt/Fjguf*6#%"aGF&6$FewFfwF&F^xF&F&F&C$>Fejs-F\x6$Fejs/FjguFf_t>
Fejs-Ff`t6#-Ffv6$;F:FF-F`w6$f*FfiuF&6$FewFfwF&-Ffv6#7$F^x-F_as6#Q1&InvisibleTim
es;F&F&F&6$FadqFi`tFejs@'/-Fd_mF_`tF%>Ff^tFbbl/Fa[vF:>Ff^t-F\x6$&Ff^tFees/Fjguf
*FfiuF&6$FewFfwF&F^xF&F&F&C$>Ff^t-F\x6$Ff^tF]ju>Ff^t-Ff`t6#-Ffv6$Fcju-F`w6$f*Ff
iuF&6$FewFfwF&FhjuF&F&F^[vFf^t@%/Ff^tFbbl@%/-Fd_mF`btF%Fejs-Ff`t6#-Ffv6$Fcju-F`
w6$f*FfiuF&6$FewFfwF&FhjuF&F&F^[v7$FejsFjhu@%F[]v-Fhdu6$FejsFf^t-Ff`t6#-Ffv6$Fc
ju-F`w6$f*FfiuF&6$FewFfwF&FhjuF&F&F^[v7$Fg]vFjhu5/FdesTcp/FdesTep-TgpF`es/FdesT
ipC%@$-Fagl6#&F\hsF`esO-FeisF^_v>Fejs-Fffl6$-&FjcuF`js6$FcduFj^v/Fcdu&F\esFb`u@
'/FggsF:-Ff_t6#/FhbuQ%NULLF&/FggsF;Fejs-Ff`t6#-Ffv6#&-F`w6$Ffv7#-Fffl6$7$Fcdu-F
i`t6#Q(&comma;F&/Fcdu7#Fejs6#FcjuFcesC;>FejsFges@$/Fejs._F&Ff`rC$>Ff^t7#Fghs@$3
1F;Fa[v-Fbt6$Fg[vF\gu@*-Figm6$<#-Fj\m6#-Fhes6#Fg[v._F&%'coordsGO-FeisFgbv33-Fbt
6$&Ff^tFhds.-F_`s6#_F&%'MATRIXG1F:-Fd_m6#Facv-Fbt6$-Ffv6$F:Facv.-F^_l6#F^_lC$@'
-Fbt6$Ffbv.%'MatrixG>Ff^t-Ffdv6#F\dv-Fbt6$Ffbv.&%'VectorG6#_F&%'columnG>Ff^t-&F
^ev6#.F`ev6#-F`w6$FfvF\dv>Ff^t-F_[q6#FhdvO-Feis6#-FifsF_`t33-Fbt6$Facv.-F_`s6#_
F&%'VECTORGFgcv-Fbt6$F\dv.F^_lC$>Ff^t-&F^ev6#._F&%$rowGFidvOF^fv-Fbt6$Facv.<$F_
[q-F_`s6#F_[qO-Feis6#-FifsFicv@$2F:-Fd_m6#F`avC&>FejsF[dt>Fejs-Ff_t6#-Fffl6$-Fe
is6#&FejsFegu/Fcdu;F;F^iu>Ff^t&F]dtFb`uO-Ff`t6%Fejs-Fi`t6#Q0&ApplyFunction;F&-F
f_t6#-Fffl6$Fe_v/FcduFf^t@$-Feen6$FejsT[qOF]fs>8*F%>FejsF[dt@&/FbdtT]qC$>Fejs-T
_qFies@$0FejsF%>F\es-Fh^m6$/F;FejsF\es3/FbdtFcdt0&FejsFhdsF%C$>Fejs-F[[w6#Fe[w@
$F][wC$>FcjvFjes>F\esF_[w>Fict-Fey6$FgesF`gs@$330FictF_dp/-F_ep6$FictF:F_dp'Fge
sFdauC$>Fihs-Taq6$-Fey6$-F_ep6$FictFc`u.Fa[mFghs@$0FihsFc\mOFihs@.3-Feen6$Fjes<
%-Fifs6#F]_l-Fifs6#%'matrixG-Fifs6#%'vectorG4FgjsZ%C$>Fejs-Fifs6#-Fges6#Fghs@$/
&7#-F_esFd[tFeesTcqO-FeisFd[tF&F&/Fjes-Fifs6#%&ARRAYGC$>FejsFaiv@$1F;F^iuC$>Fej
s-F]_l6%-Fffl6$-FhesFegu/Fcdu&Fejs6#;F:Feo-Ffv6#-Fhes6#&Fejs6#FF-Fhes6#&Fejs6#F
NO-Feis6#-Fifs6#-F\xFd[t/Fjes-FifsFdcvC$>Fejs-F_^wFj^wOFaaw/Fjes-Fifs6#%*PIECEW
ISEGC&>F\esFaiv>FejsFbbl?(FcduF:F:FggsFcbmC'>847#-F_es6#&F\esFegu@$0&FfbwFeesTe
q[>Ffbw&7#-F_es6#&FfbwFhdsFb`u@$0-Fd_m6#FfbwF;F_cw@%3/FcduFggs/Fecw-Fifs6#.%*ot
herwiseG>Fejs6$FejsF]cw>Fejs6%FejsFecwF]cw@$2FggsFcduC$>F\es-Fdeu6$7%Fiv-Fifs6#
%*piecewiseG7$Fj^vFejsFjeuO-FeisFhgs355/Fjes-Fifs6#_%&UnitsG%%UnitG/Fjes-Fifs6#
F[fw/-F]do6$Fd]uFgesQ%UnitF&&Tgq6#Q*terseunitF&@'4-Fbt6$Fghs.FfhnO-Feis6#-Fifs6
#-F`w6$FiewFghs-Fbt6$FghsFb]wC$Z%>Fejs-Faco6#_F&%/unitattributesGF&>Fejs6%/.%*m
athcolorGQ'orangeF&/.%+fontweightGQ%boldF&/.%*fontstyleGQ'italicF&O-F`]u6%-F]do
6$Fd]uFghsFejs/FhbuQ%unitF&O-FeisF`hs/Fges.F_[lC&>Fejs6$-Fi`t6#Q&localF&-Fi`t6#
Q"~F&>Ff^tF]dt?&Ffat&Ff^t6#;F;FFFcbm>Fejs6%Fejs-FeisF`bt-Fi`t6#Q",F&O-Ff`t6$Fej
s-Feis6#&Ff^tF_aw>Ff^tFaiv>FejsFges@$/&F[dtFeesFafs>Fejs-F\gsF\\u@$Fahv>FejsF`a
v@*/Fejs.%%PLOTGO-Fj]u6#-F]do6$F^^u-%+print/PLOTG6#-Ffv6#F]fs/Fejs.%'PLOT3DGO-F
j]u6#-F]do6$F^^u-%-print/PLOT3DGFc\x-Feen6$Fejs<$.%/INTERFACE_PLOTG.%1INTERFACE
_PLOT3DGOFi]u33Feav2F%Fa[v-Fbt6$Ffbv.FjclC%>F\esFfbv@$2F;Fa[vC$>Fejs-FhesFicv@$
3'Fejs.-F_`s6#7$FfcvFifv-Fh^p6$-Ffv6$F:Fejs.-F_`s6#Tiq>F\es-w,6%%"VG%"MG%#V0GF&
6"F&-Fifs6#-9&6#-Ffv6#-Fh^m6$/,&-%0rtable_num_dimsG6#F^xF:F:F:-Ffv6$F:9%7#-FfvF
i`xF&F&F&6#F<6$7&Q@>lib/Typesetting/src/Typeset.mmF&"$$*)"&+u#"&Bv#7&Fbax"$&*)"
&Wu#"&7v#6%-FhesFhgsFejs-Fhes6#&Ff^tFbhsOFbew@$3-Fbt6$Fejs%&localG4-Feen6$Fc[x<
%T[rT]rT_rC%>Ffat-F]do6$Fd]uFejs@$-Feen6$Ffat<$FbfwQ,Units:-UnitF&>Fejs_F&F[fw@
$-Figm6$7#-Fj\mFd[t<$F\ht.Ffz>Fejs-TarFd[t@$-Fagl6#&TcrFd[tC$>Ffat-F`w6$FhesFf^
t?&FcduFddxFcbmC)@$-Feen6$&FcduFeesFfet\>Ffbw-Fd_m6#-Fbdp6%Fbt&FcduFbhsF\gv@%/F
fbwF%@$32F%-Fd_m6#&FcduFhds0F\fxFa[vF`ex@$2Fa[v,&-Fd_m6#FfexF:FfbwFNF`ex@$2F:Fc
fxC$?(FfbwF:F:Fa[vFcbmC$>85-Fg]s6%31FcfxFfbw-Fbt6$&FfexF_awF\gv&FbgxFees&FfexFi
cw@$45-Fbt6$&FfatFicwF[gx3-Fbt6$._F&%,thisisatestGF[gx-Feen6$&7#-F_es6#&Ff^tFic
wFeesTerF_cw@$1FfbwFa[vF`ex>Ffbw&Fcdu6#F=>Ffbw-F\x6#-Ffbw6$F_ds-FfvF_`t@$0Ffbw.
Fc\mOFfbw@$4-Fbt6$Fejs-.F_`s6#%._Inert_MEMBERGC$?&F[gx&&Fedx6#Q)patternsF&6#Q$a
llF&Fcbm@$-_I,StringToolsG6$FgtFht%)RegMatchG6$F[gxFictC$>FfatFhdx?&Fcdu&Fcjx6#
F[gxFcbmC)@$F]exF`ex@$FjexF`ex?(FfbwF:F:F\fxFcbm@$45-Fbt6$FjgxFdgx3-Fbt6$F^hxFd
gxFahxF_cw@$1FfbwF\fxF`ex>FfbwF\ix>Ffbw-F\x6#-Ffbw6%F_dsFjesFcix@$FeixOFfbw@$33
31F;-%'lengthGF\\u/&FictFeesFhit/&FictF_awQ";F&-_F[[y%(IsAlphaG6#&FictFajw@&/Fa
[vF;O-Ff`t6%-Ff_v6%Fg[vFhitFb_t-Fi`tF\\u-Ff_v6%FacvFhitF[`tFc[vO-Ff`t6%-Fjet6$F
b^y-Fcel6$-FifsFd[tF;Feiv-Ff_t6#-F[^tFgbv@$-Fbt6$Fejs.F^inC$>Ffat-F`dx6#-Ffv6$F
%Fejs@$3F`iu53/Ffat-F_jx6$.Fefs.%#d_G4-Feen6$Q*Physicsd_F&Ffet3/Ffat-F_jx6$Fa`y
.%#D_G4-Feen6$Q*PhysicsD_F&Ffet?&Fcdu&FedxF`btFcbmC%>FfbwF\ix>Ffbw-F\x6#-&Ffbw6
#-Fifs6#F^_xFbix@$FeixC$>Ffbw-Fh^m6$/F:-Fe\u6#-Ffv6$F:FfbwFfbwOFfbw@$50FcjvF%Fj
ixC$@%F[cyC$>Fict-Fey6$-Fhes6#FcjvFdau>FfbwFcbmC%>FfbwF[dt@%/F]cwFafs>Ffbw-Fifs
6#-F\gs6#F`fw>FfbwFjes@%-Feen6$-FhesFicw7#-%%bindGF&C%>Fejs-Fey6$FbdyFeau>FictF
ejs>FfbwFcbm>FfbwFin@$3Ffbw-Fagl6#&FedxF\\uC$>FfatFhdx?&FcduFaeyFcbmC)@$F]exF`e
x>FfbwFbex@%Fhex@$FjexF`ex@$FafxF`ex@$FffxC$?(FfbwF:F:Fa[vFcbmC$>F[gxF\gx@$Ffgx
F_cw@$FjhxF`ex>FfbwF\ix>FfbwF_ix@$FeixOFfbw@&/Fjds-Fifs6#&TgrFd[tC$>Ffat-Fhat6#
F\_y@%/-Ffv6$F%FfatF`]u@%&Fdfw6#Q=italicizesuppressedfunctionsF&O-F`]u6$-Ffv6$F
:Ffat/FhbuQ)functionF&O-F`]u6%F[hy/._F&FhhwQ'normalF&F]hy@%FegyO-Fbgy6$-Ffv6#-%
'removeG6$f*FfiuF&6$FewFfwF&3-Fbt6$F^xF``p/-%$lhsGFi`xF_asF&F&6$F]gqFhbuFfatF]h
yO-Fbgy6%-Ffv6#-F]iy6$f*FfiuF&6$FewFfwF&3Fbiy-Feen6$Feiy<$FchyF_asF&F&FgiyFfatF
bhyF]hy333Fc[v5&Fdfw6#Q-typesetprimeF&&Fdfw6#Q+typesetdotF&4-Fbt6$FejsF\gv-Figm
6$FgesFg^lC&>FejsF[dt>FcduF%@$/FbdtFiv@%3/Fe[w-Fifs6#Fg^l/-Fd_m6#7#-F_es6#&Fejs
FbhsF;>Fcdu-FifsFeesC$>Ffat7#-F_esFi[w@&3/&FfatFeesFiv/&FfatFhds-Fifs6#F[elC$>F
fat7#-F_es6#&FfatFbhs@$3/F\]vF</F`]zF\\z>FcduFh]z3/F^]zF]atF\^zC$>FfatFe]z@$/<#
-Ffv6$Fc`uFfat<#Ff\z>Fcdu-Fifs6#,&F\]vF:FNF:@$0FcduF%C$>Fejs&Fa\zFhds@$/F]_wFcd
tC$>FfatF^fu@$333-Fagl6#&F[gy6#-FhesFd[t/&F^_wFhdsF%/-Fd_mFj_zF:-Fbt6$Ffat-F]jx
6#F`]u@&3/-Ffv6$F:F[`z&Fdfw6#Q&primeF&Fijy@%/Fg[v-Fifs6#F[az@%3/&7#-F_esFeguFee
sTir1Fa`w&Fdfw6#Q+primelimitF&C$>Fejs-Fchl6&/Q/&prime;&prime;F&Q(&Prime;F&/Q6&p
rime;&prime;&prime;F&Q)&tprime;F&/Q=&prime;&prime;&prime;&prime;F&Q)&qprime;F&-
Fi`t6#-Fcgo6$F]u-Fcel6$Q(&prime;F&Fa`w@%FegyO-Ff`t6$-F`]u6$FjhuF]hyFejsO-Ff`t6$
-F`]u6%FjhuFbhyF]hyFejs@%FegyO-T[s6$Fecz-Ff_t6#-FhatFeguO-F_dz6$FjczFadzC$@%Fca
zC$>FejsF_bz>Ffat-Ff`t6$FfatFejs>Ffat-F_dz6$FfatFadzO-Ff`t6%FfatFeiv-Ff_t6#-Fha
tFgbv333/Fi`z&Fdfw6#Q$dotF&F\[zFdaz1Fa`wF=@%/Fg[v-Fifs6#F[fz@%FegyO-T]s6%Fecz-F
i`t6$-Fcgo6$F]u-Fcel6$Q)&period;F&Fa`w/.%%boldGQ%trueF&/.%'accentGFbgzO-Fffz6%F
jczFhfzFcgzC$>Ffat-Fffz6%FfatFhfzFcgzOFbez@$F[cyC$>F\es-Fh^m6$/F;FcjvF\es>FejsF
bcy>FejsF[dt@)Fadt>Fejs-Ff_v6%FjesFivFcbm/Fges%!G>FejsFbbl/FictQ&TABLEF&>Fejs-F
i`t6#Q&tableF&>Fejs-Fhat6$FjesFcbm@%/FejsFbblFhivFciv-Feen6$FdesT_sC&@)/FdesTas
@%-Feen6$Q-&lt;&equals;F&Fc\tC$>Ff\tQ%&le;F&>F_dsFcbm>Ff\tFbjz/FdesTcs@%-Feen6$
Q)&lt;&gt;F&Fc\tC$>Ff\tQ%&ne;F&>F_dsFcbm>Ff\tF][[l/FdesTes>Ff\tQ)&equals;F&>Ff
\tQ%&lt;F&>Fejs-Ff_v6%FjesFdesFb_t>Ff^t-Ff_v6%FahsFdesF[`tFe`t/FdesTgsC$>Ffat-.
%$notG6#Fges-Feis6#-FifsF`bt-Feen6$FdesTis@)/FdesT[tC$>Ffat-.%$andG6$FgesFghsFg
\[l/FdesT]tC$>Ffat-.%#orGFe][lFg\[l/FdesT_tC$>Ffat-.%$xorGFe][lFg\[lC$>Ffat-.%(
impliesGFe][lFg\[l/FdesTatC&@%-Feen6$Q1&period;&period;F&Fc\tC$>Ff\tQ)&hellip;F
&>F_dsFcbm>Ff\tF__[l>FejsFj[[l>Ff^tF]\[l-&TctF`jsFg`t/FdesTetC'>F_ds-Fg]s6%-Fee
n6$Q0&colon;&equals;F&Fc\tFcbmF_ds>Fejs-Ff_v6$FjesFdes>Ff^t-Ff_v6$FahsFdes>Ff\t
-Fg]s6%F``[lQ)&Assign;F&Fb`[lFg_[l-Feen6$Fdes<$F^cwTgtC'>Ff^t&F[dtFb`u>FejsFbbl
?&FcduFf^tFcbmC$>Ffat-F[^tFegu@%3-Fbt6$Ffat-F]jx6#Tit2F:Fggs>Fejs6$Fejs-Fg]s6%-
F`_tFg_vF_btFfat>Fejs6$FejsFfat>FejsF`av@%/FdesF`a[l@%3F]iu4-Feen6$Q)EmptySetF&
Ffet-F`]u6#Q(&empty;F&-Ff_t6%Fihu/FgbtQ'&lcub;F&/F[ctQ'&rcub;F&-Ff_t6%FihuFfbtF
jbt/FdesT[uC*>F\esF]fs@$0T]uF,>F\es-%'rtableG6%F\es/._F&%)datatypeG._F&F_el/._F
&%(storageG._F&%,rectangularG>Fejs7#-%/rtable_optionsGFhgs>Fejs-F`w6$Ffv7$-Fchl
6$-Fbdp6%FbtFejsF``p7&.Fjd[l.%(subtypeG.F`e[l.%&orderG-F]iy6$f*FfiuF&6$FewFfwF&
3Fbiy-Feen6$Feiy<&Fef[lFdf[lFbf[lFaf[lF&F&F&Fejs>8)7&Fejs7#-%.rtable_indfnsGFhg
s-Fh`xFhgs-%,rtable_dimsGFhgs@%0&F`g[lFhdsF,C%>Ff^t-F]do6$Q*Shape:~%aF&&Fjg[lFe
es?&Fcdu&Fjg[lFb`uFcbm>Ff^t-Fcgo6$Ff^t-F]do6$Q$,%aF&Fcdu>Ff\t-Tau6#-T_u6#-F`[tF
_`t>Ff\tFbbl>8'-Fg]s6%-Fbt6$F\es.F_[q7#-Ffv6$F;F\es7#-Ffv6$F:F\es@'5-Fbt6$F\es.
F^ev33Ffi[l/-Fd_m6#Fci[lF:/-Ffiy6#&Fci[lFeesF:C'>Fci[l-Fg]s6%-Fbt6$F\[\l%#..G-F
ghpF[[\lF\[\l@$2TcuFci[lC$@%Faj[l>Fejs-Ff_t6%-Teu6'-F[i[l6#-F^i[l6#-F`[t6#-F]do
6%Q5%d~Element~%s~VectorF&Fci[l-Fg]s6%/-Ffv6$7$F:F;F`g[l&Fcj[l6#.FaevQ'ColumnF&
Q$RowF&-F[i[l6#-F^i[l6#-F`[t6#-F]do6$Q.Data~Type:~%aF&-Ffv6$7$F:F:F`g[l-F[i[l6#
-F^i[l6#-F`[t6#-F]do6$Q,Storage:~%aF&-Ffv6$7$F:F<F`g[lFf\t-F[i[l6#-F^i[l6#-F`[t
6#-F]do6$Q*Order:~%aF&-Ffv6$7$F:F=F`g[lFfbtFjbt>Fejs-Ff_t6%-F^\\l6'-F[i[l6#-F^i
[l6#-F`[t6#-F]do6$Q01..%d~1-D~ArrayF&Fci[lFd]\lF`^\lFf\tF\_\lFfbtFjbtO-Fj]u6$-F
]do6$F^^u-%-print/rtableGFhgsFejs>Fejs7#-Fffl6$-F[^t6#-Fifs6#-Tgu6#&-F\x6$F\esF
:Fegu/Fcdu;F:Fci[l@%F[]\l>Fejs-Ff_t6&-F^\\l6#-Ffv6#-F`w6$f*FfiuF&6$FewFfwF&-Fhv
6#-F_asFi`xF&F&6&F\fqF^i[lF]fqF[i[lFejs/FhbtFibt/F\ctF]ct/FhbuQ*ColVectorF&>Fej
s-Ff_t6&-F^\\l6#-F[i[l6#-Ffv6#-F`w6$f*FfiuF&6$FewFfwF&F[c\lF&F&6$F\fqF^i[lFejsF
]c\lF^c\l/Fhbu-Fg]s6%/F\]\l&Fcj[l6#.FdgvQ*RowVectorF&Q)Array[1]F&@%/-Fh^m6$/F;F
bbl&F`g[lFees7%.F_el.Fce[l.%.Fortran_orderGOFejsOFg`\l5-Fbt6$F\esFedv333Ffi[l/F
gj[lF;Fij[l/-Ffiy6#&Fci[lFhdsF:C)>Fci[l-Fg]s6%Fa[\l-F`w6$FghpFci[lFci[l@$52Fg[
\lF\[\l2Fg[\lF_f\lC$@%Ffe\l>Fejs-Ff_t6%-F^\\l6'-F[i[l6#-F^i[l6#-F`[t6#-F]do6$Q/
%d~x~%d~MatrixF&-FfvFhj[lFd]\lF`^\lFf\tF\_\lFfbtFjbt>Fejs-Ff_t6%-F^\\l6'-F[i[l6
#-F^i[l6#-F`[t6#-F]do6$Q81..%d~x~1..%d~2-D~ArrayF&Fjg\lFd]\lF`^\lFf\tF\_\lFfbtF
jbtOFg`\l>Ff\tw,6%%"AGFg_lF]^pF&6"F&Z%-&Fiv6#Fafs6#-Fifs6#-Fhv6#&-F\x6$F_asF:6$
F\axF_`xF&-F\js6#Q"-F&F&F&6,F]csF\esFeirFfa\lF`hrF\^tFfbsF_dsF`dqF`]u6#F<6&7&Fb
ax"%n8"&lG%"&$*H%7&Fbax"%o8"&%)G%"&!)H%7&Fbax"%p8"&%*G%"&UH%7&Fbax"%r8"&hH%"&nH
%>FejsFbbl?(FcduF:F:F\[\lFcbm>Fejs6$Fejs-F[i[l6#-Fffl6$-F^i[l6#-Ff\t6%F\esFcduF
fbw/Ffbw;F:F_f\l>Fejs-Ff_t6&-F^\\lFd[tF]c\lF^c\l/Fhbu-Fg]s6%Ffe\lQ'MatrixF&Q)Ar
ray[2]F&@%Fid\lOFejsOFg`\lC)@'2F;Fgj[l>FejsFcbm/Fgj[lF%>FejsFinC$>FejsFin?&Fcdu
Fci[lFcbm@$2Fg[\l,(-FghpFeguF:-FfiyFeguFNF:F:C$>FejsFcbmF_cw@$FejsC'>Ff^t-F]do6
$Q(%d..%d~F&-Ffv6#-Ffv6$F=F`g[l?(FejsF;F:Fgj[lFcbm>Ff^t-Fcgo6$Ff^t-F]do6$Q*x~%d
..%d~F&-Ffv6#-Ffv6$,&F<F:FejsF:F`g[l>Ff^t-Fcgo6$Ff^t-F]do6$Q+%d-D~ArrayF&Fgj[l>
Fejs-Ff_t6%-F^\\l6'Fjh[lFd]\lF`^\lFf\tF\_\lFfbtFjbtOFg`\l@)F`]]lC$>Fejs-Ff_t6$F
fc[lFhc[l>FfatFbblFfj[lC&>FejsFbbl?(Fcdu-Ffv6$7$F=F:F`g[lF:-Ffv6$7$F=F;F`g[lFcb
m@$0-FifsFibw-Fifs6#F%>Fejs6$Fejs-Ff`t6%-Ff_t6#-F[eu6#-TiuFegu-Fi`t6#Ff[[l-Ficu
6$-Fifs6#-Ffa\lFibwFd[[l>Fejs-Ff_t6%FejsFfc[lFhc[l>Ffat-Fhat6#-FifsFc^]lF[f\lC&
>FejsFbbl?(FcduFg`]lF:Fj`]lFcbm?(Ffbw-Ffv6$7$F>F:F`g[lF:-Ffv6$7$F>F;F`g[lFcbm@$
0-Fifs6#&F\es6$FcduFfbwF`a]l>Fejs6$Fejs-Ff`t6%-Ff_t6$Fha]l-F[eu6#-F[b]lFicwF\b]
l-Ficu6$-Fifs6#-Ffa\lFgc]lFd[[l>FejsFdb]l>Ffat6$Fgb]l-Fhat6#-Fifs6#-Ffv6$F>F`g[
lYQ2should~not~happenF&>Ff^t-F]iy6%FbtFee[l/-.F]t6#Fbf[lF_e\l>Ff^t-F`w6$f*FfiuF
&6$FewFfwF&-Fg]s6%Fbiy-Fiv6%-F_as6#-Fey6$FeiyF`gs-FhvF]b]l-F_as6#-Fey6$-FghpFi`
xF`gs-F_as6#-Fey6$F^xF`gsF&F&6(F`dqF`]uFadqFi`tFhdqFf`tFf^t>Fejs-Ff`t6%-Fi`t6#Q
&ArrayF&Feiv-Ff_t6%FfatFejsFcixOFejs/FdesF`_wC$>Fci[lFghs@%/Fci[lFinC'>Fejs7#-F
_es6#&F\esF]ix@$0FbdtT[vYQ/internal~errorF&>Ff^tFbbl?(FcduF;F:F^iuFcbmC&@$/F]iv
F%F`ex>Ffat7#-F_esF\iv@$50F^]zT]v-Fbt6$F\]v.%%evenGYFjh]l?(FfbwF;F;F\]vFcbmC(@$
/FjgxF%F_cw>Fict7#-F_es6#Fjgx@%3/Fb]yFj^v2F;F[\u>Fict-Ff_t6#-Ffv6#-F`w6%Ff_v&Fi
ctFb`uFj^v>Fict-Ff_v6%FjgxFd[[lFb_t>Ff\t7#-F_es6#&Ffat6#,&FfbwF:F:F:@%3/&Ff\tFe
esFj^v2F;-Fd_mFj`t>Ff\t-Ff_t6#-Ffv6#-F`w6%Ff_v&Ff\tFb`uFj^v>Ff\t-Ff_v6%Fg[^lFd[
[lFb_t>Ff^t6$Ff^t-Ff`t6%FictF\b]lFf\t-Ff`t6%F`izFeiv-Ff_t6#-Ff_t6%Ff^tFfbtFjbtC
$>Fejs-F\xFe\x@'3/-Fdcp6%FfvF:<#Fci[l<#F:/-Fd_m6#7#Fci[lF:C%>Ff^tFbbl?(FcduF:F:
-FghpFhj[lFcbm@%-FaglF\iv>Ff^t6$Ff^t-F^i[l6#-Fhat6#-FifsF\iv>Ff^t6$Ff^t-F^i[l6#
-Fd[u6$-Fi`t6#Q"?F&Fha]l-Ff_t6&-F^\\l6#-F[i[lF_`tFfbtFjbt/FhbuQ)array[1]F&3Fj]^
l/F`^^lF;C&>Fci[l-F`w6$FghpFb^^l>Ff^tFbbl?(FcduF:F:F\[\lFcbmC%>F[gxFbbl?(FfbwF:
F:F_f\lFcbm@%-Fagl6#&FejsFic]l@%-F`_t6$-FifsF]a^lFj^v>F[gx6$F[gx-F^i[l6#-Ff_t6#
-Fhat6#Fba^l>F[gx6$F[gx-F^i[lFha^l>F[gx6$F[gx-F^i[l6#-Fd[u6$Ff_^l-Ff`t6%Fha]lF
\avF`d]l>Ff^t6$Ff^t-F[i[lFc[y-Ff_t6&-F^\\lF_`tFfbtFjbt/FhbuQ)array[2]F&C)>8(-F`
w6$FfiyFb^^l>Fci[lFd`^l>Ff^tF`c^l>FfatFbbl?(F&F:F:F&FcbmC&>Fcdu-F`w6$f*FfiuF&6$
FewFfwF&Fib\lF&F&6&F`irF[b]lF_dqF[euFf^t@%-Fagl6#&Fejs6#Fcix>Ffat6$Ffat-Ff`t6%-
Ff_t6#-FfvFeguF\b]l-Ficu6$-FifsF`d^lFd[[l>Ffat6$Ffat-Ff`t6%Fgd^lF\b]l-Fd[u6$Ff_
^l-T_vFhd^l?(FfbwFgj[lFNF:Fcbm@$2Fghx&Fci[lFicwC$>Ff^t7%-Ffv6$;F:,&FfbwF:FNF:Ff
^t,&FghxF:F:F:-Ffv6$;Fi[^lFNF`c^lF_cw@$FhexF_cw>Ff^t-F`w6$f*FfiuF&6$FewFfwF&-&F
_asFiat6#-FifsFi`xF&F&6$F`hrF\^t7$FgesFghs-Ff`t6%-Fi`t6#Q&arrayF&Feiv-Ff_t6$Fci
x-Ff_t6%FfatFfbtFjbt-Feen6$Fdes<$TavTcvO-Ff`t6%-Fi`t6#-Fg]s6%/FdesF\h^lQ%readF&
Q%saveF&TevF\ft-Feen6$Fdes<$TgvTivC$>Fejs-Fg]s6%/FdesF\i^lQ&errorF&Q'returnF&@%
/FggsF%O-Fi`tFd[tO-Ff`t6%Fhi^lFhh^lF\ft-Feen6$Fdes<,Fhh]lFfi]lT[wT]wT_wTawTcwTe
wTgwTiwC$>FejsF]fs@%-Fbt6$Fejs.%'objectGC$@$Fad[lZ&C&>8;-F]bo6#/.%.opaquemodule
sGFin>Ff^t-_Fejs%.ModuleTypesetG6$Fejs/._F&F]\sFbd[l>Ffat7#-_Fejs%2ModuleDecons
tructGFd[tO-Fc_x6$Ff^t-T]x6#-T[xF`btF&F&-F]bo6#/Fg[_lFc[_lZ&C&>Ff^t-T_xFd[t>Fc[
_lFd[_l>FfatFb\_l@%-F_ht6#/FejsFf^tYF&OFg\_lF&O-Fj]u6#-F]do6$F^^uFejsF^]_lOF_^_
l/FdesFgjvC&>F_dsFcbm@%-Feen6$Q,&minus;&gt;F&Fc\t>Ff\tQ&&map;F&>Ff\tFj^_l>Fejs<
#-FhesFdh]l@%/Fejs<$.Ffw.FewC5>%-_Env_In_ProcGFcbm>%0_EnvInArrowProcGFcbm>Fejs7
#-F_es6#&F\es6#F?Z%C*>Ff^t-F`w6$f*FfiuF&6$FewFfwF&-%(ToInertG6#-FhesFi`xF&F&F&F
ca[l>Ff^t-Fffl6$/-%-_Inert_PARAMGFegu-Fg]s6%-Fbt6$&Ff^tFegu-F]jx6#%._Inert_DCOL
ONG-Ffv6$F:Ffa_lFfa_l/Fcdu;F:Fa[v>Ffat-Fi`_l6#-FhesF^`_l>Fict-Fcap6$Ffat.-F_`s6
#%,_Inert_PROCG>Ffbw.Ffbw>Fict<#-Fffl6$/&FictFegu&FfbwFegu/Fcdu;F:F[\u>Ffat-Fch
l6$-F`w6$f*FfiuF&6$FewFfwF&-/FghpFfiyFi`xF&F&F&Fict-Fchl6$Ff^t-Fchl6$FictFfat>F
\es-Fh^m6$/F?-Fifs6#-%*FromInertG6$Ffat._F&F\gsF\esF&F&Z%>Fejs-Ficu6%F_`_lQ#->F
&F[`tF&OFi]u@$-Figm6$FejsFj]uOFi]u>FictFbbl>FfatFbbl>Ff^tFca[l?(FcduF:F:Fa[vFcb
mC%>Ffbw-Fhat6#Ffa_l>Ffat6$FfatFfbw@%/&7#-F_esF]f_lFeesFcdt>Fict6$Fict/-F`]u6#-
F]do6$Q)args[%d]F&FcduFfbwC%>FfbwFfa_l@$/&7#-F_esFicwFeesFh[t>Ffbw&Fbg_lFhds>Fi
ct6$Fict/Fhf_l-FhatFicw>Ff^tFaiv>86-F_ht6#0Ff^tF,?(FcduF:F:Fa[vFcbmC%>FfbwFfa_l
@$F`g_l>FfbwFeg_l>Fict6$Fict/-F`]u6#-F]do6$Q*LOCAL[%d]F&FcduFig_l>Ff^t7#-F_es6#
&F\es6#""*>Ff^t7#-Fffl6$&Ff^t6#,&FcduF;F:F:/Fcdu;F:-%%iquoG6$Fa[vF;?(FcduF:F:Fa
[vFcbm>Fict6%Fict/-F`]u6#-F]do6$Q,LEXICAL[%d]F&FieuF\f_l/-F`]u6#-F]do6$Fhj_lFcd
uF\f_l@$07#FictF,C$>Fejs-Fchl6$FictFejs@$3F\h_lFcjt>Fejs-F\x6$Fejs/Fd[uf*F&F&6$
FewFfwF&-Fhv6#-.F_as6#FgdsF&F&6&FbeqFd[uFijrFe\u@$0-Fd_m6#7#FfatF:>FfatF_bt-Ff`
t6%FfatFh`tFejsOFi]u/FdesFibx@9/FjesF%O-F`]u6#Q&nargsF&/FjesFNO-F`]u6#Q%argsF&/
FjesFFO-F`]u6#Q)procnameF&/FjesFeoO-F`]u6#Q*_nresultsF&/Fjes!"%O-F`]u6#Q(_param
sF&/Fjes!"&O-F`]u6#Q)_nparamsF&/Fjes!"'O-F`]u6#Q&_restF&/Fjes!"(O-F`]u6#Q'_nres
tF&/Fjes!")O-F`]u6#Q)_optionsF&/Fjes!"*O-F`]u6#Q*_noptionsF&/FjesF*O-F`]u6#Q)th
isprocF&O-F`]u6#-F]do6$F\g_lFjes/FdesFjbxO-F`]u6#-F]do6$F\i_lFjes/FdesF[cxO-F`]
u6#-F]do6$Fhj_lFjes/FdesTaxO-Ff_t6%Fj]t/FgbtQ'&apos;F&/F[ctFbb`l/FdesTcxC'>Fejs
F[dt@'Fc[wC$>Ff^t-Fhat6#-Fifs6#-%&modp1G6$-%+ConvertOutG6$F]fsFgesFghs>FejsF`fw
3/FbdtFj^v/F^iuF<C$>Ff^t-Fhat6#-Fifs6#-%&modp2GFac`l>Fejs-F]do6$Q&%a,%aF&FgesOF
i]u@$-Fbt6$Ff^t-F]jx6#Ff`t>Ff^tF^`t>FfatFghs-Ff`t6%Ff^t-Fi`t6$Q$modF&/FhbuFejs-
F[eu6#-F]do6$Q#%dF&Ffat5/FdesTex/FdesTgxC&>Fejs-Ff_v6$FjesFggu>Ff^tFbbl?(FcduF<
F;FggsFcbmC&>FfatFgbw>F[gx&F\es6#,&FcduF:F:F:@'/F[gxF%>FictFbbl/F[gxF:>FictFejs
>Fict-F_dz6$Fejs-F[eu6#-F[b]lFc[y@%/FcduF<@'3F]]z/F`]z-Fifs6#%"OG>Ff^t-Ff`t6%-F
i`t6#Q"OF&Feiv-Ff_tF\\uFjf`l>Ff^t-Ficu6$FjbwFd^v@'/FjbwFf\z>Ff^tFict/Fjbw-FifsF
_aw>Ff^t6$-Fi`t6#Q*&uminus0;F&Fict>Ff^t-Ff`t6%-Ficu6$FjbwFggu-Fi`tF\[vFict@/Fgg
`l>Ff^t6%Ff^t-Fi`t6#Q'&plus;F&F]h`lFjf`l@'3-Feen6$F^]zTix2-FhesFibwF%>Ff^t6%Ff^
t-Fi`t6#Q(&minus;F&-Ficu6$-Fifs6#,$Fbj`lFNFd^v3/F^]zFd^vF[^z@%2-FhesFg]zF%@%/Fa
[alFN>Ff^t6%Ff^tFej`l-Ficu6$F`]zFggu>Ff^t6%Ff^tFej`l-Ff`t6%-Fhat6#-Fifs6#,$Fa[a
lFNFei`lFf[al@%/Fa[alF:>Ff^t6%Ff^tFii`l-Ficu6$F`]zFd^v>Ff^t6%Ff^tFii`lFdh`l>Ff^
tFh\alFgh`l>Ff^t6%Ff^tFii`lFictFih`l>Ff^t6%Ff^tFej`lFictF^j`l@%Faj`l>Ff^t6%Ff^t
Fej`l-Ff`t6%-Ficu6$Fjj`lFgguFei`lFict>Ff^t6%Ff^tFii`lFai`lF][al@'/Fh]zFjh`l>Ff^
t6%Ff^tFej`l-Ff`t6%Ff[alFei`lFictF`[al>Ff^t6%Ff^tFej`l-Ff`t6'-Ficu6$F^\alFgguFe
i`lFf[alFei`lFict>Ff^t6%Ff^tFii`l-Ff`t6'-Ficu6$Fh]zFgguFei`lFf[alFei`lFict>Ff^t
Ff]al@%FeftOFf^tOFi[u/FdesT[y@%3/%;_Env_Typesetting_ProcdepthGF%/-F]v6$<#-Fffl6
$&F\es6#,&FfbwF;F:F:/Ffbw;F:-F^j_l6$,&FggsF:FNF:F;<$Fjh`lFf\zFghtC%>FejsFbbl?(F
cduF;F;FggsFcbmC&>Ff^t-FhatFibw@$2F;Fcdu>Ff^t6$T]yFf^t@$2Fhf`lFggs@%/Fff`lFf\z>
Ff^t6$Ff^t-Fi`t6#Q'&semi;F&>Ff^t6$Ff^t-Fi`t6#Q(&colon;F&>FejsFh]vO-Ff`tFd[tC%>F
ejsFbbl?(FcduF;F:FggsFcbmC'>Ff^tFg`al@$4-Feen6$&FgbwFees<'F^_alT_yTayTcyTey>Ff^
t6$-Fcel6$TgyFb_alFf^t@$Fi`al>Fejs6$FejsF\aal@$2FcduFggs>Ff^tFbaal>FejsFh]vOF]b
al/FdesFibalC->8+-F_ht6#/Fj__lFcbm>Ffat-Fg]s6%4F]dalF_calFbbl>Fejs6(Ffat-Fi`t6#
Q#ifF&Fhh^lF\ftFhh^l-Fi`t6#Q%thenF&>Fejs6$Fejs-Fg]s6%F]dalFhh^lF\aal>Fb_al,&Fb_
alF:F:F:@%-Feen6$&F]dtFeesFhbal>Fejs6$Fejs-Ffv6#Fb[u>Fejs6&FejsFfat-Fg]s6%Fddal
FacalFbblFb[u>FejsF^eal?(FcduF=F;FggsFcbmC&@%2FggsFhf`lC$>Fejs6%FejsFfat-Fi`t6#
Q%elseF&>Ff^tFjbwC$>Fejs6)FejsFfat-Fi`t6#Q%elifF&Fhh^lFg`alFhh^lFjdal>Ff^tFff`l
>FejsF^eal@%-Feen6$&7#-F_esF_`tFeesFhbal>Fejs6$Fejs-Ffv6#-FhatF_`t>Fejs6&FejsFf
atF]falF]hal>FejsF^eal>Fb_al,&Fb_alF:FNF:>Fejs6'FejsFfat-Fi`t6#Q$endF&Fhh^lFgda
lOF]bal/FdesFjbalC->F]dalF^dal>FfatFbdal>FejsFfat@%/FggsF>>Fejs6+Fejs-Fi`t6#Q$f
orF&Fhh^lF\ftFhh^l-Fi`t6#Q#inF&Fhh^lFb[uFhh^lC(>FictF[dt@$50Fb]yFj^vFgj]l>Fejs6
'FejsFbialFhh^lF\ftFhh^l@$0FahsFf\z>Fejs6'Fejs-Fi`t6#Q%fromF&Fhh^lFb[uFhh^l@$0F
eh]lFf\z>Fejs6'Fejs-Fi`t6#Q#byF&Fhh^l-FhatFdh]lFhh^l>Fict7#-F_es6#&F\es6#F>@$F[
jal>Fejs6'Fejs-Fi`t6#Q#toF&Fhh^l-FhatFa[blFhh^l@$0&F\esF[aw-FifsFiat>Fejs6'Fejs
-Fi`t6#Q&whileF&Fhh^l-Fhat6#F]\blFhh^l>Fejs6%Fejs-Fi`t6#Q#doF&F_eal>Fb_alFbeal@
%-Feen6$&7#-F_es6#&F\esF_awFeesFhbal>Fejs6$Fejs-Ffv6#-FhatFb]bl>Fejs6&FejsFfatF
]falFh]bl>Fb_alFbhal>Fejs6(FejsF_ealFfatFehalFhh^lFh\blOF]bal/FdesTiyO-Fi`t6#Q&
breakF&/FdesT[zO-Fi`t6#Q%nextF&/FdesF[calC)>Ffat6%F_cal-Fi`t6#Q$tryF&F\aal>Fb_a
lFbeal@%Fdeal>FejsFheal>Fejs6&FejsFfatFacalFb[u?(FcduF<F;FggsFcbmC$@%FcfalC$>Fe
js6'FejsF\aalFfat-Fi`t6#Q(finallyF&F\aal>Ff^tFjbwC'>Fejs6&FejsF\aalFfat-Fi`t6#Q
&catchF&>Fict7#-F_es6#Fff`l@%F[jal>Fejs6$Fejs-&%(displayGFiatFj`bl>Fejs6$Fejs-F
`]u6#F]u>Fejs6%FejsFhaalF\aal>Ff^tFff`l@%Fdgal>FejsFjgal>Fejs6&FejsFfatFacalF]h
al>Fb_alFbhal>Fejs6(FejsF\aalFfatFehalFhh^lF__blOF]bal/FdesF\calC)>FfatF_cal>Fe
js6'Ffat-Fi`t6#Q$useF&F\ftFeialF\aal>Fb_alFbeal@%F]]bl>FejsFheal>FejsFf_bl>Fb_a
lFbhal>Fejs6(FejsF\aalFfatFehalFhh^lFebblOF]bal/FdesT]zOFi]uY6%Q?not~handled:~c
ode=%1,~value=%1F&FdesF]fsF&F&6^zFczF&FddqI'mspaceGFddrFc_rI#FNG/F_[l/FfzF[dqFi
^rI'MEMBERG/F_[l/FfzF[dqFabrI)CNumericG/F_[l/FfzF[dqFdhrI#TnG/F_[l/FfzFjasFg^rI
'STRINGG/F_[l/FfzF[dqFc[rI9ProcessEscapedCharactersG6$I':-5679GF[dr/F_[l%,_n617
660864GFi\rI.StringToGlyphG/F_[l/FfzF[dqFedqI#msG6$Ffdr/F_[l%,_n617113152GF[_rI
'DCOLONG/F_[l/FfzF[dqF\_rI)CATENATEG/F_[l/FfzF[dqFf\rI-UseOpTypesetG/F_[l/FfzF[
dqF`hrI)TdisplayG/FfzFjasFdgqI+NeedsBraceG6$Fgt/FfzF[dqF`eqI(mfencedGFcerFadqI#
moGF`drFhdqI%mrowGFidrFj^rI)TABLEREFG/F_[l/FfzF[dqFh^rI%NAMEG/F_[l/FfzF[dqF`\rI
5DisabledTypesetRulesG/F_[l/FfzF[dqF\[sI1GivePhysicsColorG/F_[l/FfzFjasFbeqI%ms
ubGFferFijrI0PutSuperscriptsG/F_[l/FfzFjasF`dqI#miGF^drF_irI)HasAssumG/F_[l/Ffz
FjasFdfqI*mverbatimG6$Fjfr/F_[l%,_n617174672GFehrI#TiG/F_[l/FfzFjasFcjrI.greek_
lettersG6$I':-5940GF[dr/F_[l%,_n617183504GF]gqI+msemanticsGFegrF]_rI&POWERG/F_[
l/FfzF[dqF\irI)TbracketG/F_[l/FfzFjasFjhrI'TpowerG/F_[l/FfzFjasFa^rI'INTNEGG/F_
[l/FfzF[dqF_dqI#mnGF\drFidqI&mfracGF[erFh[rI$ATBG/F_[l/FfzF[dqFggqI$ASMG6$Fgt/F
fzF[dqFc^rI)RATIONALG/F_[l/FfzF[dqFjdqI&msqrtG6$F]er/F_[l%,_n617113472GF[eqI&mr
ootG6$F^er/F_[l%,_n617113536GF^_rI%PRODG/F_[l/FfzF[dqFihrI)TproductG/F_[l/FfzFj
asFa_rI$SUMG/F_[l/FfzF[dqFb_rI%POLYG/F_[l/FfzF[dqFhhrI%TsumG/F_[l/FfzFjasF]`rI$
SEQG/F_[l/FfzF[dqFfjqI(AllTagsG6$I':-5666GF[dr/F_[l%,_n617121280GFi`rI%PROCG/F_
[l/FfzF[dqFecrI3GetOverloadBindingG6$I':-5809GF[dr/F_[l%,_n617700304GFgjrI+Prin
tInertG6$I':-5944GF[dr/F_[l%,_n617183584GFc`rI&TABLEG/F_[l/FfzF[dqF^`rI%LISTG/F
_[l/FfzF[dqFc\rI'SetTblG/F_[l/FfzF[dqFefqF]bsFj`rI&PARAMG/F_[l/FfzF[dqF[arI&LOC
ALG/F_[l/FfzF[dqF\arI(LEXICALG/F_[l/FfzF[dqFccrI4ExportNameToiMEMBERG/F_[l/FfzF
[dqFfirI-TypesetRulesG6$I':-5927GF[dr/F_[l%,_n617183144GFbbrI%NameG/F_[l/FfzF[d
qFb\rI5SuppressDependenciesG6$I':-5694GF[dr/F_[l%,_n617699824GFb^rI'INTPOSG/F_[
l/FfzF[dqFceqI%msupGFherFfeqI&moverG6$F\fr/F_[l%,_n617114176GFebrI+RelationalG/
F_[l/FfzF[dqFf_rI'LESSEQG6$I':-5746GF[dr/F_[l%,_n617124608GFe_rI(INEQUATG6$I':-
5745GF[dr/F_[l%,_n617124544GFd_rI)EQUATIONG6$I':-5744GF[dr/F_[l%,_n617180568GFi
_rI$NOTG/F_[l/FfzF[dqFdbrI(BooleanG/F_[l/FfzF[dqFh_rI$ANDG/F_[l/FfzF[dqFj_rI#OR
G/F_[l/FfzF[dqF[`rI$XORG/F_[l/FfzF[dqF_`rI&RANGEG/F_[l/FfzF[dqFfhrI%TrowG/F_[l/
FfzFjasFa`rI'ASSIGNG/F_[l/FfzF[dqF``rI$SETG/F_[l/FfzF[dqF^[rI&TSexpG/F_[l/FfzF[
dqFf`rI'RTABLEG/F_[l/FfzF[dqFgcrI*NumFormatG/F_[l/FfzF[dqF\fqI$mtdG6$Fbfr/F_[l%
,_n617114432GF]fqI$mtrG6$Fcfr/F_[l%,_n617114496GF^jrI(iRTSizeG/F_[l/FfzFjasF[fq
I'mtableG6$Fafr/F_[l%,_n617114368GFeirI-applyaliasesG6$I':-5926GF[dr/F_[l%,_n61
7183104GF`irI,IntToStringG/F_[l/FfzFjasFd`rI(HASHTABG/F_[l/FfzF[dqFe`rI%HASHG/F
_[l/FfzF[dqF[irI*TsequenceG6$I':-5916GF[dr/F_[l%,_n617182824GFfarI%READG/F_[l/F
fzF[dqFgarI%SAVEG/F_[l/FfzF[dqF\crI+ITimesReplG6$I':-5800GF[dr/F_[l%,_n61718084
8GF`arI&ERRORG/F_[l/FfzF[dqFaarI'RETURNG/F_[l/FfzF[dqFjarI'MODDEFG/F_[l/FfzF[dq
F[brI'MODULEG/F_[l/FfzF[dqF_arI%STOPG/F_[l/FfzF[dqFdarI'BINARYG/F_[l/FfzF[dqF\b
rI(GARBAGEG6$I':-5784GF[dr/F_[l%,_n617127008GF]brI(FOREIGNG6$I':-5785GF[dr/F_[l
%,_n617127072GF^brI(CONTROLG6$I':-5786GF[dr/F_[l%,_n617127136GF_brI%DBUGG6$I':-
5787GF[dr/F_[l%,_n617127200GFhhqFeasFjhqI&_HoldG6$I':-5639GF[dr/F_[l%,_n6171164
16GFairI2PrintPreprocessorG6$I':-5922GF[dr/F_[l%,_n617700880GFh`rI'UNEVALG/F_[l
/FfzF[dqFg`rI'ZPPOLYG/F_[l/FfzF[dqF__rI'SERIESG/F_[l/FfzF[dqF`_rI,EXACTSERIESG/
F_[l/FfzF[dqF`brI(NumericG/F_[l/FfzF[dqFb`rI(STATSEQG/F_[l/FfzF[dqF^crI(NewLine
G6$I':-5802GF[dr/F_[l%,_n617127968GF^arI#IFG/F_[l/FfzF[dqF]arI$FORG/F_[l/FfzF[d
qFearI$TRYG/F_[l/FfzF[dqFharI$USEG/F_[l/FfzF[dqF[crI+ProcMspaceG6$I':-5799GF[dr
/F_[l%,_n617180808GFbarI&BREAKG/F_[l/FfzF[dqFcarI%NEXTG/F_[l/FfzF[dqFiarI'SDPOL
YG/F_[l/FfzF[dqF]fblGI':-5907GF[drGI':-5908GF[drNf*F&6/%%contG%&cont0G%%attrG%$
digG%$powG%$sgnG%$valG%$semG%#vrG%#viG%#iiGFa_oF]^p6#F[dsF&C(>6$FadsFjds-F`^m6%
Fbt7#FgdsF``p@$0-Fd_mF`esF:YQ;'mn'~requires~one~argumentF&>Fjds-Fhes6#&FjdsFees
>F_dsFjdsZ%@$30FhvF,0%D_Env_Typesetting_SuppressFormattingGFcbmO-Fiv6$F_dsFhvF&
F&@1-Fbt6$FjdsF]^xC%>Fict-Fg]s6%2FjdsF%F_i`lF]u>Fjds-F]do6$Fge`l-Fg]s6%Ff^dl,$F
jdsFNFjds@%2Fafs-F`]yF`esC$>Ff^t,(F__dlF:F\jsFNF_jsFN-F[[t6%-F]do6(Q9%s%s[...%d
~digit%s...]%sF&Fict&Fjds6#;F:F\jsFf^t-Fg]s6%2F:Ff^tQ"sF&F]u&Fjds6#;,$F_jsFNFN-
Ffv6#Fads/FbjsFjds-F[[t6$-Fcgo6$FictFjdsFc`dl-Fbt6$Fjds.%)rationalG@%Ff^dl-Fh[t
6$-Fc[tF^i`l-F`[t6$-Feis6#-Fifs6#,$-%&numerGF`esFN-Feis6#-Fifs6#-%&denomGF`es-F
`[t6$-Feis6#-Fifs6#FiadlF[bdl3-Fbt6$Fjds.%'hfloatG/%4_EnvConvertHelpTo2DGFcbm-F
h[t6%-Fi[t6#Q'HFloatF&-Fc[tFfiv-Fc\t6#-F[[t6#-Fey6$FjdsF`gs-Fbt6$Fjds.%&floatG@
+-Fbt6$Fjds.%*undefinedG-Fh[t6&-Fc[t6#Q&FloatF&Fccdl-Fc\t6#-Fi[t6$Q*undefinedF&
/._F&%'italicGQ&falseF&Fc`dl3-Fbt6$Fjds.%)infinityG2F%Fjds-Fh[t6&FeddlFccdl-Fc
\t6#-Fi[t6#Q(&infin;F&Fc`dl3FcedlFf^dl-Fh[t6&FeddlFccdl-Fc\t6#-Fh[t6$-Fc[tF]j\l
F\fdlFc`dl-Feen6$Q0FloatScientificF&F\^t@%/-Ffv6$F:FjdsF%@&5/-Ffv6$F%-Fi`_lF`es
%._Inert_HFLOATG/-Ffv6$F:Fcgdl-%._Inert_INTPOSGFaa]lO-F[[t6$Q#0.F&Fc`dl/Ffgdl-%
._Inert_INTNEGGFaa]lO-F[[t6$Q,&uminus0;0.F&Fc`dlC(>FcjvFj^dl@%32F%F`_t2F`_t-F`]
y6#F\gdlC$>F]dal/Fbjs-F]do6$Fd]uFcjv>Fjds-&%&evalfG6#F`_tF`es>F]dalFbbl>Fci[lF[
idl>F`c^l-Ffv6$F;Fjds@%Ff^dl>6$FjdsF`g[l6$-F]do6$Fge`l,$F\gdlFNF:>F^jdl6$-F]do6
$Fge`lF\gdlF%@%31Fc^`l,&Fci[lF:F`c^lF:1FjjdlF?C&@'1FjjdlF%>Fjds-Fcgo6%F]hdl-Fce
l6$Q"0F&,&Fci[lFNF`c^lFNFjds1F%F`c^l>Fjds-Fcgo6%Fjds-Fcel6$Fd[elF`c^lQ".F&>Fjds
-Fcgo6%&Fjds6#;F:,&F`c^lF:FNF:F\\el&Fjds6#;F`c^lFN@$/F`g[lF:>Fjds-Fcgo6$F_i`lFj
ds@$/&Ff_t6#Q.striptrailingF&FcbmC$?(Fi`tF__dlFNF:Fcbm@$0&Fjds6#Fi`tFd[elF_cw@$
2Fi`tF__dlC$@$/7#F]dalF,>F]dalF_idl>Fjds&Fjds6#;F:Fi`t-F[[t6%FjdsFc`dlF]dalC)>F
jds6%Fd]dlF\\el&FjdsFb`u@$0F]dalFbblC$>F]dal-F]do6$Fge`l-Ffv6$F:Fcjv>F]dal/Fbjs
-Fcgo6%&F]dalFeesF\\el&F]dalFb`u@$Fh\el>FjdsF[]el>F`c^lFjjdl>Fjds-FcgoF`es@$F]]
elC$?(Fi`tF__dlFNF:Fcbm@$Fd]elF_cw@$Fh]elC$@$F[^elC$>F]dalF\_el>F]dalFa_el>Fjds
F_^el-Fh[t6%-F[[t6$FjdsF]dal-Fc[tF\[v-F]at6%-F[[t6#Q#10F&-F[[t6#-Ff`t6#Fc\el/Fb
jsQ"^F&@%F[gdlOF[hdlC*>FcjvFj^dl@%FhhdlC$>F]dalF_idl>FjdsFcidl>F]dalFbbl>Fci[lF
[idl>F`c^lFjidl@%Ff^dl>F^jdlF_jdl>F^jdlFdjdl@%3Fijdl1F`c^lF<C$@'F^[el>FjdsF`[el
Ff[el>FjdsFh[el>FjdsF^\el@$F]]elC$?(Fi`tF__dlFNF:Fcbm@$Fd]elF_cw@$Fh]elC$@$F[^e
l>F]dalF_idl>FjdsF_^elC&>Fjds-FcgoFf^el@$F]]elC$?(Fi`tF__dlFNF:Fcbm@$Fd]elF_cw@
$Fh]elC$@$F[^el>F]dalF_idl>FjdsF_^el>F`c^l,(F`c^lF:Fci[lF:FNF:@%Ff[el>Fjds-Fcgo
6%FjdsQ#e+F&-F]do6$Fge`lF`c^l>Fjds-Fcgo6%FjdsQ#e-F&-F]do6$Fge`l,$F`c^lFN@$Fh\el
>FjdsFj\elFb^el-Fbt6$Fjds.F^clYFjh]l-Fbt6$Fjds.%1extended_numericG@)F_ddl-Fi[t6
%F\edlF]edlFc`dlFbedl-Fi[t6$F^fdlFc`dlF_fdl-Fh[t6%-Fc[tFfj`lF\fdlFc`dlYFjh]l/&7
#-F_es6#-FifsF`esFeesFcdtC&>6$F\esFejs6$-%#ReGF`es-%#ImGF`es>Ff^t-F]do6$Fd]uFfe
t@%/Ff^tQ"IF&C$>Ff^tQ-&ImaginaryI;F&>F`c^lF[[t>F`c^l-Fg]s6%-Feen6$Ff^t<$Q"iF&Q"
jF&F[[tFi[t@%/F\esF%@'/FejsF:-F`c^l6$Ff^tFc`dl/FejsFN@%/F`c^lF[[t-F[[t6$-Fcgo6$
F_i`lFf^tFc`dl-Fh[t6%Faadl-Fi[tF_`tFc`dlC%@%2FejsF%C$>Fejs-Feis6#-Fifs6#,$FejsF
N>FfatF:C$>Fejs-FeisF_gy>FfatF%@%-Fbt6$Fejs-F]jx6#F`[t@%/F^_x-F[[tF\eu>Fejs-Fh^
m6$/F:-F`c^lF_`tFejs>Fejs-Fh^m6$/F:-Fh[t6%F^_xFj`elF_[flFejs>Fejs-Fh[t6%FejsFj`
elF_[fl@%/FfatF%Fejs-Fh[t6%FaadlFejsFc`dlC'>F\es-Feis6#-FifsFhgs>Ffat-Fg]s6%5-F
bt6$FejsFaddl1F%FejsF:FN>Fejs*&FfatF:FejsF:>Ffat-Fc[t6#-Fg]s6%/FfatF:F[j`lFgj`l
@%Fghel-Fh[t6&F\esFfatF_[flFc`dlC&>FejsFajel@%Fdjel@%Fijel>FejsF\[fl>FejsFa[fl>
FejsFg[flFejs-Fh[t6%F\esFfatFejsYQ>'mn'~content~must~be~a~numberF&F&F&6LFczF&Fg
crFebclF^[sI-FormatNumberG6$I':-5951GF[dr/F_[l%,_n617183784GFgirI)iEDigitsG/F_[
l/FfzFjasFhirI*iEDBeforeG/F_[l/FfzFjasFiirI)iEDAfterG/F_[l/FfzFjasF]gqFdhblF_dq
FaiblFadqFbfblFidqFbiblFhdqFcfblF`dqFdgblF`eqFafblF`\rFjfblF]jrI'iDPrecG/F_[l/F
fzFjasFc\rF^]clFg_lI"iG6$I':-5813GF[dr/F_[l%,_n617128384GF`irF\dclFceqF]_clFf^r
I(COMPLEXG/F_[l/FfzF[dqF`jrI'iIUnitG/F_[l/FfzFjasFcdblf*6#Fj[dl68Ffbs%%prefGF]c
sF^csF_csF`csFacsFajqF\\dl%%baseG%%expoG%(expovisG%+oversymbolGFg_lF]^p%+savedn
amesGFa^p%/PhysicsCommandG%2PhysicsStringNameG%,case_PamPapG%*addprefixG%&extra
G6#F[dsF&C(>Fjds-Fg]s6%3-Fbt6$FeisFc_y1F:-Fd_m6#Feis-Ffv6$F:FeisFcbm>Fads7#-F_e
sFi`x>FihsFbbl@$/&FadsFeesFhvC(>F]dal-Fey6$F[a_lF`gs@$FgjsZ%C$>Fci[lFh`_l@&-Fee
n6$-Ffv6$F%Fci[l<$%,_Inert_NAMEG%4_Inert_ASSIGNEDNAMEGC$>F`c^l-F\gs6#-Fcgo6%Q"`
F&F]dalFdcfl@$-Feen6$-Ffv6$F%-Fi`_l6#F`c^l<$%1_Inert_LOCALNAMEG%9_Inert_ASSIGNE
DLOCALNAMEG>Fihs-Fiv6#Q#:-F&-Feen6$FibflF\dflC$>F\es7#-Fj\mFj`_l?&F`c^lF\esFcbm
@$/-Ffv6$F%F`c^l.%(_MEMBERG>Fihs6$-Fg]s6%/-Fd_mF[dflF:Fbbl-Fafs6#-Fifs6#-Ffv6$F
:F`c^lF`dflF&F&@$-Fagl6#&F\js6#F]dalC%>F]dalF_ffl@$4-Feen6$/F_jsF_cuF]dal>F]dal
--Ffv6$F%F]dal6$-FfvF`fflFgfflOF]dal@$332F:-F`]yF`ffl/Fd_elQ"#F&550FdjtFcbm0__F
efs%(TetradsG%,InitializedGFcbm4-Feen6$-Fey6$F]dalFb]w7#-%(exportsG6#F[hfl@&3Fc
jt-Feen6$F]dal7$-Fey6$FgjtF`gs-Fey6$F\[uF`gs>FfhsFcbm0-_F[[y%'SearchG6$7%Q$mi(F
&Q$mo(F&Q$mn(F&F]dal7$F%F%Z%C(>F]dal-Fchl6$Fbjs-F\gs6#Fe_el@$43-Fbt6$F]dal.Ffem
-Feen6$-F\x6#FjfflF[[tYF&>F]dal-F\xF`ffl>F]dal&7#-F`[t6%F]dalFghtFc[tFees@$43/F
jfflFh[t-_F[[y%.IsSubSequenceG6$Q#__F&-Ffv6$F:F]dalC$>F]dal&F\js6#F]\gl@$Fdffl>
F]dalFifflOF]dalF&F&@&/F]dalF_`vO-Fh[t6#F_`v/%8_EnvStripModuleLocationGFcbmO-Fh
[t6#F`bfl@$/Fd^tFcbm@,/F]dalQ(integerF&O-Fc\t6$-Fh[t6$Q'&Zopf;F&Fbhy-Fi[t6#7#._
F&Fjcl/F]dalQ'posintF&O-Fc\t6$-F\^t6$Fh]gl-FivFji`l-Fi[t6#7#._F&Fau/F]dalQ'negi
ntF&O-Fc\t6$-F\^t6$Fh]gl-FivFfj`l-Fi[t6#7#._F&%'negintG/F]dalQ*nonposintF&O-Fc
\t6$-F\^t6$Fh]gl-Ff_t6$-F`_t6#Fd[elFd_gl-Fi[t6#7#._F&%*nonposintG/F]dalQ*nonneg
intF&O-Fc\t6$-F\^t6$Fh]gl-Ff_t6$Fd`glFg^gl-Fi[t6#7#._F&%*nonnegintG@$4FjdsOF[a_
l@'/F]bflFi`t@'/-Fd_m6#7#-F_es6#&FadsFbhsF:-&Ff`tF`es6$-Feis6#&FadsFhdsFdbt334-
Feen6$FeetF]at-Fbt6$-F\x6$-FhesF\cglF;F\ht-Feen6$Ffht7#-Fj\m6#Fgcgl-Fcdt6$F[cgl
-Ff_t6%-&FafsF`esFfbglFfbtFjbt-Fibgl6$F[cglFadglF\bflC4>F]dal-FfetFj`_l>Fjgu-Fd
_mF`ffl@$Fcjt@&532F:Fjgu/F]\glFcfs3/FjguF:555-Feen6$-Ffv6$FNF]dal__FefsF`gq%DIn
ertPhysicsCommandsWithTypesettingG3/FjgflFcbm-Feen6$Fgegl_Fjegl%KInertPhysicsTe
tradsCommandsWithTypesettingG3/__Fefs%-ThreePlusOneGF]hflFcbm-Feen6$Fgegl_Fjegl
%PInertPhysicsThreePlusOneCommandsWithTypesettingG3/__Fefs%.StandardModelGF]hfl
Fcbm-Feen6$Fgegl_Fjegl%QInertPhysicsStandardModelCommandsWithTypesettingGC$>F[g
xFgegl@$5Faegl-Fagl6#&_Fjegl%1ContentToDisplayGFc[yC$>F\h_l(Q(PhysicsF&F[gx@$4-
Feen6$F\h_lF]atZ%O-Fjegl6$F[gxF\h_lF&F&FaeglC$>FfbwF]\glZ%@$5-Feen6$Ffbw-_Fefs%
.GetDefineINFOG6#Q&namesF&-Feen6$Ffbw-_Fefs%-GetSetupINFOG6#Q2coordinatesystems
F&C$@$0FjetFin@'-Fbt6$Ffbw._F&%*nc_symbolG>F\es-Fg]s6%0&FjetFhdsQ%noneF&/._F&%+
foregroundGFijglFbbl-Fbt6$Ffbw._F&%*ac_symbolG>F\es-Fg]s6%0&FjetFbhsFjjgl/F\[hl
Fh[hlFbbl>F\es-Fg]s6%0&FjetFeesFjjgl/F\[hlF^\hlFbblO-Fh[t6%-Fey6$FfbwF`gsF\es/F
_jsQ.PhysicsTensorF&F&F&>FcduFbbl@%3F^egl-Feen6$F[a_lFcdy>F]dal-F_jx6#FgeglC$>F
`c^l-F[]pF&?(F&F:F:F&2F:FidglC,>F`g[l-F]do6$Fd]uF]\gl@$332F;-F`]y6#F`g[l/F]e\lF
dcfl/&F`g[lF_awFdcfl>F`g[l&F`g[lFajw@%/FidglFjgu>Fci[l-F\cflF]^hl>Fci[l-F_jx6$F
ci[lFf^hl>Fejs-Fhd_l6$Fci[lFjd_lZ%>Ff^t7#-FehflFdawF&>Ff^tF,@%-Feen6$._F&F^dqFf
^t>Ffat-F\x6#--Fhd_l6$-F_jx6$Fci[l-F\cfl6#Q*_pexportsF&Fjd_lF&>FfatFf^t>F`g[l-F
]do6$Fd]u-Ffv6$F;F]dal@$Fi]hl>F`g[lFb^hl>Fcjv-Fhd_l6$Ff^hlFjd_l@%-Feen6$FcjvFf^
tC$@$43-Feen6$FejsF`c^l-Feen6$FcjvFfat>Fcdu6$FcduF]\gl>F]dal-Fh^m6$/F:FbblF]dal
C%>F]dalF]]hl>FcduFbblF_cw>F]dal-Fjffl6$FcduF]gfl@'Fc]hlC%>Fads-Fh[t6$Ff]hl/Fgh
wFehy?(Ff\tF;F:FidglFcbm>Fads6%Fads-Fiv6#Fe]t-Fh[t6$-F]do6$Fd]u-Ffv6$Ff\tF]dalF
ibhlO-FcdtFd`dlF^egl>FadsFf]hl>Fads-F]do6$Fd]uF[a_l@$332F:-F`]yFd`dl/F]bflFdcfl
/&FadsF_awFdcfl>Fads-Fcgo6%FdcflF`bflFdcfl@,-Feen6$Fads<#Q)infinityF&>FadsF^fdl
/FadsQ&NablaF&O-Fiv6#Q(&nabla;F&/FadsQ'%NablaF&O-Fe\u6$-Fiv6$Faehl/F_jsQ&inertF
&/F_hwFd[u-Fjjx6$Q,_[a-zA-Z]+$F&Fads@$-Fagl6#&F`]u6#&FadsFb`u>Fads-Fcgo6$Q"_F&F
bfhl-Fjjx6$Q2^[a-zA-Z]+[0-9]*$F&FadsC$>F_ds&-_F[[y%&SplitG6$FadsQ+0123456789F&F
ees@$-Fagl6#&F`]uF`js>Fads-Fcgo6$Fgghl&Fads6#;,&-F`]yF`jsF:F:F:FN>Fads-Fg]uFd`d
l>F\esFbbl>FictFin@$F^jglC$>F]dalF[a_l@'-Fbt6$F]dal._F&%/noncommutativeG>F\esFf
jgl-Fbt6$F]dal._F&%0anticommutativeG>F\esFe[hl>F\esF[\hl@$0Fj]uFinC%>F]dalF[a_l
@(-Feen6$F]dal<$.__Fefs%(VectorsG%&NablaG._F_jhl%+DivergenceGF&-Fbt6$F]dal-._F&
%3PhysicsUnitVectorsG6#.Fejs@$/&Fj]uFhdsQ$hatF&C$>Fads-Fey6$FejsF`gs>Fict-Fiv6#
Q(&wedge;F&3-Fbt6$F]dal-._F&%/PhysicsVectorsGF[[il0&Fj]uFeesFjjglC$>FadsFc[il@(
/Fa\ilFehw>F\es/._F&FdhwFehw/Fa\ilQ&arrowF&>Fict-Fiv6#Q'&rarr;F&/Fa\ilQ*halfarr
owF&>Fict-Fiv6#Q.&RightVector;F&@&F\fhl@$F`fhl>FadsFffhlFifhlC$>F_dsF^ghl@$Fegh
l>FadsFighl@%/FfhsFcbmC$@%0-%+searchtextG6$F_i`lF]dalF%>Fci[l-F\gs6#_Fjegl%'gui
pamG>Fci[l-F\gs6#_Fjegl%'guipapG>Fci[l-Fh^m6$/FN6$-Ffv6$FNFci[lF\esFci[lC$>Fci[
l-Fg]s6%/F[jtFcbm-Fh[t6%FadsF\esFbhy-Fh[t6$FadsF\es@$0FihsFbbl>Fci[l-Fcdt6$Fihs
Fci[l>Fci[l-Fg]s6%/FictFinFci[l-F]_u6$Fci[lFict@$35-_F[[y%)IsPrefixG6$Q/Standar
d~HTML5F&-Faco6#I(versionG6$FgtFht/%H_Env_Typesetting_StandardHTML5InterfaceGFc
bm-Fbt6$Fci[l-F]jx6#Fh[t>Fci[l-_Faau%1FormatMIForHTML5GFhj[lFci[lYQ<'mi'~conten
t~must~be~a~nameF&F&F&6fnFczF&Fh^rFgfblFadqFbfblF`hrF\fblFd[rI.SemanticTableG/F
_[l/FfzF[dqF]gqFdhblFgjqI/GlobalToExportG6$I':-5667GF[dr/F_[l%,_n617179288GFfjq
Ff[clFh[rFciblF\hqI*AddAtomicG6$I':-5625GF[dr/F_[l%,_n617175152GF`dqFdgblFjhqF[
hclFefqF]bsFceqF]_clF_dqFaiblF`eqFafblFj^rFdfblFghrI%TsubG6$I':-5912GF[dr/F_[l%
,_n617129504GF`\rFjfblFhdqFcfblFccrFj]clFajrI/iPhysicsColorsG/F_[l/FfzFjasFejqI
(minertcG6$I':-5665GF[dr/F_[l%,_n617121216GF\eqI'mstyleG6$F_er/F_[l%,_n61711360
0GF[]rI3DisplayPrefixTableG/F_[l/FfzF[dqFi\rF\eblFbjrI0iPhysicsVectorsG/F_[l/Ff
zFjasFfeqF^_clF`hqI&HTML5G6$I':-5629GF[dr/F_[l%,_n617115968GF^hblf*F&6(FfbsFj[d
lF\\dl%(newcontGFg_lF]^p6"F&C(>FjdsF]afl>6$FadsF_dsFi\dl@$2-Fd_mF`jsF:YQO'mrow'
~must~have~at~least~one~content~argumentF&>Fci[lFbbl?&F`c^lF_dsFcbm@'-Fbt6$F`c^
l-F]jx6#Fhv@%/-Fd_m6#-Fbdp6%FbtF`c^lF``pF%>Fci[l6$Fci[l-FfvF[dfl>Fci[l6$Fci[lF`
c^l-Fbt6$F`c^l-F]jx6#Fiv>Fci[lFjfilC$>F`g[l-FbdglF[dfl@%-Fbt6$F`g[lF^fil@%/-Fd_
m6#-Fbdp6%FbtF`g[lF``pF%>Fci[l6$Fci[l-FfvF]^hl>Fci[l6$Fci[lF`g[l>Fci[lF`hil@%F_
^^lC$?&F`c^lFadsFcbm>Fci[l-F]iy6$f*FfiuF&6$FewFfwF&-Fbt6$F^x/-FfiyF^asF_e\lF&F&
6$Fg_lF`c^lFci[l-Fibfl6$Fjg\lFc`dl-Fhv6$Fci[lFc`dlF&F&6*FczF&FhdqFcfblF^[rF_bcl
F`hrF\fblFhaclGFbcilf*6#Fefo66%%varsG%%multG%)isratpolG%#smG%$numG%$denG%$extGF
_\dl%#cfGF]csF^csF_csF`csFccsFg_lF]^p%$eidGFa^p%$cofG%$monG6#F[ds6"C/>8$<">8%Fi
n>8-7#-F_es6#9$>85Fin@$/&F[[jl6#F:T%C(>Fa[jl-FhesF^[jl>867#-%'coeffsG6%Fa[jl-Fe
ep6$-Fcap6#Fa[jl<#I*constantsGFht.87>Fg\jl7#Fg\jl>Fa[jl7$-Fffl6$-Ffv6#7$&Fg\jl6
#82&F[\jlFb]jl/Fc]jl;F:,&-Fd_m6#Fg\jlF:FNF:-Fg]s6%/&Fg\jl6#FNF:-Ffv6#7$&F[\jlF^
^jlF:-Ffv6#7$F]^jlFb^jl>F[[jl7$T'-Fffl6$-FifsFb]jl/Fc]jlFa[jl>Fa[jlFcbm@$0Fd[jl
Fh^jlYQ.invalid~inputFcjil@$2T),&-Fd_m6#F[[jl#F:F;#FNF;F:C%>Fc]jl,*Ff_jlFh_jlFi
_jlF:T+FNT-FN@%/Fc]jlF:>84-%-tools/gensymG6#Q/[...1~term...]Fcjil>Fb`jl-Fd`jl6#
-F]do6$Q1[...%d~terms...]FcjilFc]jl>F[[jl7&-Ffv6$;F:,&F:F:F]`jlF;F[[jl-Fifs6#Fb
`jl-FifsFe[jl-Ffv6$;,$F^`jlFFFNF[[jl@%5Fa[jl/Ff_jlF<>8&FinC%>F^bjlFcbm?(Fc]jlF;
F;Ff_jlFcbmC&>8.&7#-F_es6#&F[[jl6#,&Fc]jlF:F:F:Fe[jl@$4-Feen6$FdbjlT/C$>F^bjlFi
n[>8/7#-F_es6#&F[[jlFb]jl@+-Feen6$&FecjlFe[jlF`cjl\-Feen6$F]djlT1@%-Feen6$Ficjl
Ffjil>FijilFcbm>Ffjil-Feep6$Ffjil<#Ficjl/F]djlT3C$?(83F;F;-Fd_m6#FecjlFcbm@)0&7
#-F_es6#&Fecjl6#,&F^ejlF:F:F:Fe[jlT5C$>F^bjlFinFccjl4-Feen6$&7#-F_es6#&Fecjl6#F
^ejlFe[jlFadjlC$>F^bjlFinFccjl-Feen6$FdfjlFfjil>FijilFcbm>Ffjil-Feep6$Ffjil<#Fd
fjl@$4F^bjlFccjl3/F]djlT7-Feen6$&Fecjl6#F;<$-Fifs6#%$&+-G-Fifs6#%$&-+GC&>Fecjl7
#-F_es6#&Fecjl6#F<@$0F_ejlF;C$>F^bjlFinFccjl>807#-F_es6#Ffgjl@+-Feen6$&F[ijlFe[
jlF`cjl@$45-Feen6$Fibjl<$-FifsF^^jlFeajl-Feen6$FfgjlFhijlC$>F^bjlFinFccjl/Fbijl
T9@%-Feen6$FfgjlFfjil>FijilFcbm>Ffjil-Feep6$Ffjil<#Ffgjl/FbijlF[ejlC$?(F^ejlF;F
;-Fd_m6#F[ijlFcbm@)0&7#-F_es6#&F[ijlFhejlFe[jlFjejlC$>F^bjlFinFccjl4-Feen6$&7#-
F_es6#&F[ijlFefjlFe[jlFadjlC$>F^bjlFinFccjl-Feen6$F]\[mFfjil>FijilFcbm>Ffjil-Fe
ep6$Ffjil<#F]\[m@$F`gjlFccjl33/FbijlFh^jl/F[[[mF<FfijlC%@$4-Feen6$&7#-F_es6#&F[
ijlFehjlFe[jlF`cjlC$>F^bjlFinFccjl>Fecjl7#-F_es6#&F[ijlFggjl@&F_djl@%-Feen6$F\^
[mFfjil>FijilFcbm>Ffjil-Feep6$Ffjil<#F\^[mFjdjlC$?(F^ejlF;F;F_ejlFcbm@)FbejlC$>
F^bjlFinFccjlF]fjlC$>F^bjlFinFccjlFhfjl>FijilFcbm>FfjilF\gjl@$F`gjlFccjlC$>F^bj
lFinFccjlC$>F^bjlFinFccjl>F^bjl-F_ht6#3F^bjlFijil>81F:>Fi_[m.Fi_[m>8'Fbbl@%F^bj
l?(Fc]jlF;F;Ff_jlFcbmC)>8+Q"+F&>8,-FhesFhbjl>FdbjlFfcjl@'-Feen6$&FdbjlFe[jlF`cj
l@%30Fe`[mF:0Fe`[mFNYFbe]lC$>Fe`[m*&Fe`[mF:-FhesFhcjlF:>8(Fbbl3/F[a[mFcgjl-Feen
6$&FdbjlFggjlFhgjlC$>Fecjl7#-F_es6#&FdbjlFehjl@%/F_ejlF;C%@%/F[b[mFigjl>Fb`[m-F
chl6$7&/Fc`[mQ#+-F&/F^j\lQ#-+F&/F\c[mFc`[m/F^c[mF^j\lFb`[m>Fb`[m-Fchl6$7&/Fc`[m
F^c[m/F^j\lF\c[m/F\c[mF^j\l/F^c[mFc`[mFb`[m>FdbjlF\ijl@'Fi`[m@%F]a[mYFbe]l>Fe`[
m*&Fe`[mF:-FhesF^ijlF:/F[a[mFh^jlC$@%F]a[mYFbe]l>Fe`[m*&Fe`[mF:-FhesF`b[mF:>Ffa
[m-&T;6#Fcbm6#F[b[m>Ffa[m-Fid[mF^ijl>Ffa[m-Fid[mFhcjl@%/Fe`[mF:>Ffa[m-&T=F[e[m6
$FicjlFh^jl>Ffa[m-Fee[m6$FicjlQ+scalarprodF&@$3-Fbt6$Fe`[m.F^cl2Fe`[mF%C$>Fe`[m
,$Fe`[mFN>Fb`[m-Fchl6$7&/Fc`[mF^j\l/F^j\lFc`[m/F\c[mF^c[m/F^c[mF\c[mFb`[m@'Fbe[
m@$/Ffa[mFbbl>Ffa[m-T?6#F]euF_g[m>Ffa[m-Fid[m6#-Fifs6#Fe`[m>Ffa[m-TC6%Feg[m-TA6
#F][vFfa[m@%/7#F]`[m7"@%/Fb`[mFc`[m>F]`[mFfa[mC$>Fb`[m-Fchl6'/Fc`[mF[j`l/F^j\lF
_i`l/F\c[mQ)&plusmn;F&/F^c[mQ)&mnplus;F&Fb`[m>F]`[m6$-F^h[m6#Fb`[mFfa[mC$>Fb`[m
-Fchl6'F[i[m/F^j\lFgj`lF]i[mF_i[mFb`[m>F]`[m6%F]`[mFci[mFfa[m?(Fc]jlF;F;Ff_jlFc
bmC5>Fb`[mFc`[m>Ffa[mFbbl>8)Fbbl>8*Fbbl>Fe`[mFf`[m>FdbjlFfcjl@1Fi`[m@%Fbe[m>Fe`
[mFda[m>Fe`[mFca[m33/F[a[mTE/-Fd_m6#FdbjlF;0F[b[mFeajlC$>Fe`[m*&Fe`[mF:-FhesF\e
[mF:>Ffa[m-Fid[m6#-TI6$7$F][\mFeajlTG3F\[\m/F_[\mF<C(>FecjlFd[\m@'2FecjlF%@%Fah
[m>F]`[m6$-F^h[m6#F_i`l-TK6#-Fifs6#,$FecjlFN>F]`[m6%F]`[m-F^h[m6#Fgj`lFi\\mFah[
m>F]`[m-Fj\\m6#-FifsF`ejl>F]`[m6%F]`[m-F^h[m6#F[j`lFd]\m>FecjlFed[m>FdbjlFg[\m@
'/FecjlF:>F]`[m6%F]`[mFi]\mFdbjl/FecjlFN>F]`[m6%F]`[mFa]\mFdbjlC%@%2F%FecjlC$>F
ecjlFd]\m>F]`[m6$F]`[mFi]\mC$>FecjlFi\\m>F]`[m6$F]`[mFa]\m@%-Fbt6$Fecjl-.F_`s6#
TM@%/-Ffv6$F:FecjlFag[m>Fecjl-Fh^m6$/F:FdbjlFecjl>Fecjl-Fh^m6$/F:-F[h[m6%Fh_\mF
]h[mFdbjlFecjl>Fecjl-F[h[m6%FecjlF]h[mFdbjl>F]`[m6$F]`[mFecjlF^djl-Feen6$F[a[mF
adjl>Ffa[mF`e[m/F[a[mF[ejlC'>Fecjl7#-F_esF\e[m@'33/F]djlF][\mFcb[m0FfgjlFeajlC%
>Fe`[mF^d[m>Fdbjl-Fj[\m6$-Fh^m6$/F;F\\\mFdbjlF]\\m>6%Ffa[mFaj[mFcj[m-TO6$FdbjlF
i_[m333Fda\m/F_ejlF<2F_d[mF%2-FhesFchjlF%C%>Fe`[mFdf[m>Fdbjl-Fj[\m6$-Fh^m6$/F;-
Fifs6#,$Fe[\mFNFdbjlF]\\m>F_b\mF`b\m>F_b\m-Fab\m6$FicjlFi_[m>Ffa[m-Ffv6#Ffa[m>F
aj[m-Ffv6#Faj[m>Fcj[m-Ffv6#Fcj[mFga[mC$>FecjlF^b[m@%Fcb[mC%@%Ffb[m>Fb`[mFhb[m>F
b`[mFbc[m>FdbjlF\ijl@)Fi`[m@%Fbe[m>Fe`[mF_d[m>Fe`[mF^d[m/F[a[mF_jjl>Ffa[mF^e[mF
\a\mC&>F_b\m-Fab\m6$FfgjlFi_[m>Ffa[mFjc\m>Faj[mF]d\m>Fcj[mF`d\m>Ffa[m-Fee[m6$Ff
gjlF\c[m>Ffa[m-Fee[m6$FicjlF\c[m3Fha[m-Feen6$-F]do6$Fd]uFe[\m7$FbfwFdcxC$>Ffa[m
Fbbl>Fcj[mF`e[m@%Fbe[m>Ffa[mFde[m>Ffa[mFie[m@$3-Fbt6$Fe`[m.FjeelFaf[mC$>Fe`[mFd
f[m>Fb`[mFff[m>Fdbjl7#-F_esFfg[m@(3/F[a[mTQ0TSFch[m>Ffa[m6$-Fj\\mFfg[mFfa[mFfg
\mC$@$Fa[\m>Ffa[m6$-Fbg[m6#-F]do6$Fge`lFe[\mFfa[m>Faj[m6$-Fbg[m6#-F]do6$Fge`lFf
d[mFaj[m0-Fi`_lFhg[m-FigdlFe[jl>Ffa[m6$Feg[mFfa[m>6$Ffa[mFaj[m6$7#Ffa[m7#Faj[m@
$30Fcj[mFbbl/Faj[mFch[mC$>Ffa[m7$Fjc\mFcj[m>Fcj[mFbbl@&/-Fd_mF[d\mF%>Ffa[m7#Fag
[m-Figm6$Ffa[mFi_[m@%2F:F_j\m>Ffa[m-F\x6$Ffa[m/Fi_[mTU>Ffa[m-F\x6$Ffa[m/Fi_[mf*
6#FgiuFcjil6$FewFfwFcjilF_[jlFcjilFcjilFcjil@$-Figm6$Faj[mFi_[m@%2F:-Fd_mF^d\m>
Faj[m-F\x6$Faj[mFij\m>Faj[m-F\x6$Faj[m/Fi_[mf*FfiuF&6$FewFfwF&F^xF&F&F&>Ffa[m&-
F`w6$f*F`[]mFcjil6$FewFfwFcjil-FfvFijuFcjilFcjil6$FadqF^h[mFfa[m6#;F:FF@%/F_j\m
F:>Ffa[m&Ffa[mFe[jl>Ffa[m-F[h[m6#Fjc\m@$0Faj[mFch[mC$@%/Fg[]mF:>Faj[m&Faj[mFe[j
lC$>Faj[m&-F`w6$f*F`[]mFcjil6$FewFfwFcjilFg\]mFcjilFcjilFh\]mFaj[mFi\]m>Faj[m-F
[h[m6#F]d\m>Ffa[m-Fe_\mFai\m@$Fgi\mC$>Ffa[m&-F`w6$f*F`[]mFcjil6$FewFfwFcjilFg\]
mFcjilFcjilFh\]m7$Ffa[mFcj[mFi\]m>Ffa[mF`]]m@%Fah[m@%Feh[m>F]`[mFfa[mC$>Fb`[mFi
h[m>F]`[mFbi[mC$>Fb`[mFgi[m>F]`[mF[j[m@%/-Fd_m6#Fbh[mF:F]`[m-F[h[m6#F]`[mFcjilF
cjil6VFczF&Fb_rF][clFa_rFjjblFjirI(iETermsG/F_[l/FfzFjasF[jrI*iETBeforeG/F_[l/F
fzFjasF\jrI)iETAfterG/F_[l/FfzFjasF`brFaiclFbbrFb^clF^_rFdjblFb^rFj^clFc_rFhcbl
Fh^rFgfblF`hrF\fblF\irFhhblF_dqFaiblFadqFbfblFhdqFcfblFf^rFf_flFh[rFciblFggqFfi
blFdhrFadblFidqFbiblFihrFgjblFc^rFiiblFgcrFebclF`eqFafblFb[clf*6$%"pGFccs6)F[ji
lF\jilF]jilF]csF^csF_csFg_l6"6"C)>8'7#-F_es6#9$@$0&F`a]m6#F:T%YFa_jl>8$Fbbl>8%F
bbl>8&Fbbl?(8*F;F;-Fd_m6#F`a]mFcbmC$>8(-Fhes6#&F`a]m6#,&Fbb]mF:F:F:@)-Feen6$Fgb
]m<$FNF:C%>Fgb]m-&T'6#Fcbm6#&F`a]m6#Fbb]m>8)7#-F_esFgc]m@%/Fjb]m-FifsFha]m@%3/&
F[d]mFha]mT)-Feen6$-F]do6$Fd]u-Fhes6#&F[d]m6#F;7$FbfwFdcx>F`b]m6$F`b]mFgb]mC$@$
-T+6%Fhc]mFia]m-Fg]s6%/7#F\b]m7".Fc_t.F\`t>Fgb]m-9%6#Fgb]m>F\b]m6$F\b]mFgb]mC$@
$-Fde]m6%Fhc]mFia]m-Fg]s6%/7#F^b]mFje]mF[f]mF\f]m>Fgb]mF^f]m>F^b]m6$F^b]mFgb]m/
Fgb]m#F:F;>F\b]m6$F\b]m-T-6#Fcc]m/Fgb]m#FNF;>F^b]m6$F^b]mFbg]mC$>F[d]mF\d]m@)33
/&7#-F_esFib]mFha]mT/2-F`bdlF`f]m"$+"2-%$absG6#-FjadlF`f]mFeh]mC$@%-Fbt6$-&T3Ff
c]m6%-FifsF`f]mT1F\f]m-.F_`s6#T5>Fgb]m-Fhi]m6#-T96%-T76#-F]do6$Fge`lFgh]m-F`j]m
6#-F]do6$Fge`lFdh]m/.%)bevelledGFbgz>Fgb]mF\j]m@'2Fhb]mF%>F^b]m6$F^b]m-T;6$Fhc]
mFgb]mFbd]m>F`b]m6$F`b]mF`[^m>F\b]m6$F\b]mF`[^m3-Fbt6$Fgb]m.F^cl2Fgb]mF%>F^b]m6
$F^b]m-Fa[^m6$Fhc]m-F`i]m6%-Fifs6#,$Fgb]mFNFdi]mF\f]mFbd]m>F`b]m6$F`b]m-Fa[^m6$
Fhc]mF_i]m>F\b]m6$F\b]mFg\^m6%Fie]mFjf]m7#F`b]mF]a]mF]a]m6<FczF&F^_rFdjblF`hrF
\fblFc_rFhcblFdgqF^fblFjdqF\jblFc^rFiiblF]_rFehblF\irFhhblF`eqFafblF_dqFaiblFid
qFbiblFjhrF[iblFijblf*6$Fgiu%$bmkG6#F]cs6"6"C$>8$-&T'6#Fcbm6$9$T%@%3-Fbt6$Ff]^m
-.F_`s6#T)/-F]v6$-Fbdp6%Fbt<#-Ffv6#Ff]^m/-.F]t6#T+.F_el<#/Fb_^mQ)tablerefFc]^m<
"-T-6%-Ffv6$F:Ff]^m-Ffv6$F;Ff]^m9%-T/6$Ff]^mF_`^mFc]^mFc]^m60FczF&F]_rFehblF\ir
FhhblFbeqF`gblF]gqFdhblFdeqI(msubsupG6$Fjer/F_[l%,_n617114048GFceqF]_clF]iblGFg
dclf*Fcw6'Ffbs%$oflG%$argGFgiu%"tG6#F[dsF&C(>FjdsF]afl@%32F;Feds-Feen6$&Fgds6#F
eds<$FinFcbmC$>F_dsFea^m>Fads&Fgds6#;F:,&FedsF:FNF:C$>F_dsFbbl>FadsFgds@$333Fba
^m/FfdsFhv0FivF,/&FivF]ixFinC$>F`c^lF[^dl>F[^dlFcbm>Fci[l-Fbdgl6$F^xF_ds@$-Fagl
F[dfl>F[^dlF`c^l@%30FfdsF%-F\jsFd`dl-F_jsFhj[lFci[lF&F&6.FczF&F]_rFehblFgcrFebc
lF`hrF\fblFdgqF^fblF]irI(TfencedG6$I':-5918GF[dr/F_[l%,_n617129792GFjhblGF[d^mG
I':-5919GF[drf*6#'FduFjcl6&%#daG%#dsG%#tfG%$mprG6$%)rememberGF[dsE\s""59c)>OuSu
Y%=FinC)@$0FhvF:OFin>FjdsFhafl@$50Fd]dlFiv0&FjdsFhdsF%OFin>Fjds7&FafsF%-Fifs6#F
bbl-Ffv6$;F=FNFjds>F_ds-Fhes6#-F_js6$FjdsF\js@$52F_hhlF:0&F_ds6#;FNFNQ"|irF&OFi
nZ%C%>Fads-F\x6$-Fhes6#-F_js6$7%Fbjs-FifsFhj[l7$F[[tF^xF\js/Fci[l%/hasassumptio
nsG>Fci[lFhg^m-Fg]s6%-Fbt6$Fads.Fe]pFadsFinF&FinF&F&62FczF&F_jrI*iSAssumedG/F_[
l/FfzFjasFh^rFgfblFg^rFddblFh[rFciblFggqFfiblFc_rFhcblF]`rFc[clFggblf*6#Fg_l6"6
$FewFfwFeh^m-Fg]s6%29$F%-F]do6$Q,&uminus0;%dF&,$Fjh^mFN-F]do6$Fge`lFjh^mFeh^mFe
h^m6$FczF&F^dclGFbhclt+6('Fefo%'unevalG>F_\sFin>Fe[sFin>Fi[sFcbm>F\\sF,>Fb\sFin
6.%$inpGF\a^mF]csF^csF_csFi\s%#eeG%#e0G%$mcpG%)mcpcleanG%/rulestodisableGFics6#
F[dsF_^sCH>8-Fin@$9&>FhjsFcbm>T%9(@&5/-%)numelemsG6#Fjj^mF%/&Fjj^m6#F:F]u>Fjj^m
7"3/%C_Env_Typesetting_NumericFormattingGFcbm4-_F[[yF_ail6$Q)StandardF&-Faco6#F
dail>T'-%0define_externalG6-.%.numericFormatG.%%JAVAG'.%%arg1GF\u'.%%arg2GF\u'.
%%arg3G&Fg[sFd[_m'.%%arg4GFc]_m'.%%arg5GFc]_m'.%%arg6GFc]_m'._F_^sFaarF\u/.%*CL
ASSPATHG-Fcgo6$-F]bo6#.FeaoQ0/java/Maple.jarF_^s/.%&CLASSGQAcom.maplesoft.clien
t.dag.DagUtilF_^s@$39''9$.F`_lZ%C$@%'Fa__m.-F_`s6$FdbxT)C$>8*-Ffv6#Fa__m>8+-F\x
6$F]`_mF;>Fa`_mFa__m@$3'Fa`_mFb__m-Figm6$Fa`_m.F^fmC$>F]`_m-Fd_s6%Fa`_m.-F_`s6#
F^fmT+@$0F]`_mFa`_mO-w,6#F]j^mF_^s6"F_^s-T#6%Fa__mp./_F_^sFj[sFinF_^sF_^s6$Fbir
T]p6#F:6$7&FbaxF^io"%3X"%&e%7&FbaxF^io"%<X"%!e%6$F]`_m&9"6#;F;FNF_^sF_^s>%6_Env
InTypesetNotParseGFcbm>T--F[bpF_^sZ%C$>8&7#-F_es6#-Fifs6#-F\x6$Fa__mF:@'3/&Fhc_
mFd[_mT//&Fhc_m6#F;-Fifs6#Fj__mC$>Fhc_m-Fhes6#&Fhc_m6#F<>8$-Fifs6#-F\x6$Fhc_mF;
3Fbd_m/Ffd_m-Fifs6#T1C$>Fae_m-Ffv6$F:-F\xF_`_m@$-Fbt6$Fae_m-.F_`s6$.FjclFje_m>F
ae_m-Ffv6$F:Fae_m>Fae_m-FifsF_`_mF_^s>Fae_mF[g_m@$/F_]sFcbmC%>8)-Fd]s6$-Fg]s6%/
-F]bo6#.F]^sF^^sF`^sFa^s.Fc^s-Fe^s6%Fag_mQ/[input]~:=~%a|+F_^s7#-Fhes6#Fae_m-F
\_s6#Fag_m@$/F^h_mFf[_mO-T36#F]u>8/-F]bo6#Fh[_lZ&C&>Fhc_m7#-F_esF`h_m@$3Fbd_m/F
fd_m-Fifs6#T5C,>Fhc_m7#-F_esF]e_m@$0-Fd_m6#Fhc_mF<O-T76#QUinvalid~'mprintslash'
:~incorrect~number~of~argumentsF_^s>Fae_mFfd_m>8'F\e_m>Fhc_mF`i_m@$0Fcd_mT9O-Fb
j_m6#QUinvalid~'mprintslash':~first~argument~must~be~a~listF_^s>Fae_mFfd_m>Fhc_
mF`i_m@&1F^j_mF:>Fae_m-Fifs6#Fbbl/F^j_mF;>Fae_mFfd_m@*54-Fbt6$Fgj_m.F^_l0-Fd_m6
#Fgj_mF:F_^s-Fbt6$&Fgj_mFd[_m.F][_lC%>Fjh_m-F]bo6#/Fh[_lFin>Fgj_m-FfvFa\`m>8,-_
Fgj_mFe\_lFa\`m33-Fbt6$Fd\`m-Fdf_m6#<$.F[`p.%$intG2F%-Fd_m6#Fd\`m-Fbt6$-Ffv6$F:
Fd\`mFe]`m>F^]`mF\]`m0-Fcap6$F_h_m-Fdf_m6#T;<"C&>F^]`mF\]`m>Fgj_m-Fcap6$F^]`m.-
F_`s6$/-F]t6#%$%idGFau<'F_[qFfdvF^ev&F^ev6#Faev&F^ev6#Fdgv@$0Fgj_mFi^`mC$>Fgj_m
-F`w6$f*6#FgiuF_^s6$FewFfwF_^s/Fa__m-Fhes6#-Ffv6$7$F:F;Fa__mF_^sF_^sF_^sFgj_m>F
^]`m-Fchl6$Fgj_mF^]`m>Fej^mFcbm>Fgj_mF_h_m@$3334-Fagl6#F^]`m-Fbt6$Fgj_mFe]`m2F%
F`\`m-Fbt6$-Ffv6$F:Fgj_mFe]`m>F^]`mFgj_mF_^sF_^s-F]bo6#/Fh[_lFjh_m>Fhc_mF`i_m@$
Fbd_mC$>Fhc_m-F]do6$Fd]u-Fhes6#Ffd_m@$32F7-F`]yF_j_m/&Fhc_m6#;F:F7Q+INTERFACE_F
_^sOF_h_m>6&Fgj_mT=T?TA-Faco6&.Fdail.%+rtablesizeG.%,showassumedG.%.imaginaryun
itG>Fgj_m-Fey6$Fgj_m.F\u@'31Fbp-F`]yFa\`m/&Fgj_m6#;F:FbpF^\_m>6)TCTETGTITKTMTO-
Faco6).%7elisiondigitsthresholdG.%4elisiondigitsbeforeG.%3elisiondigitsafterG.%
6elisiontermsthresholdG.%3elisiontermsbeforeG.%2elisiontermsafterG.%1displaypre
cisionG33-Fagl6#%>_Env_Typesetting_Elision_TestG-Fbt6$Fjf`m-F^\`m6#Fff_m/-Fd_mF
if`mFM>F^e`m-FfvFif`m>F^e`m6)"&++"Feh]mFeh]mFeg`mFeh]mFeh]mFN@$2F_e`m,&F`e`mF:F
ae`mF:>F_e`mFhg`m@$2Fbe`m,&Fce`mF:Fde`mF:>Fbe`mF\h`m>Fhc_m-Fcap6$F^h_m-Fdf_m6#<
$.%%DiffG.%%diffG>Fgj_m-Fbdp6%Fbt-FcapF_j_m.Ffhn>%G_Env_Typesetting_UsePartialD
erivativesG-F_ht6#32F:F`\`m/&TQ6#Q-globalderivsF&Fcbm@%3/-TSF_^sQ)extendedF&Fcj
tC$>TU7%Fjjgl-_FefsFiigl6#Q4noncommutativecolor6"-Fcj`m6#Q5anticommutativecolor
Ffj`m>F`j`m-F`w6%FeyF`j`mFdd`m>F`j`mFin@%3Fji`mF`_uC$>TW7$-Fcj`m6#Q.vectordispl
ayF_^s-Fcj`m6#Q2unitvectordisplayF_^s>Fb[am-F`w6%FeyFb[amFdd`m>Fb[amFin>Fb_alF%
>TY-Fh^m6$/F=Fbbl-F\x6#F`\am>8.Fi^`m@$-Fbt6$9)F^\`m>Fg\am<#-Ffv6#F[]am@$F\cdl>F
g\am-Feep6$-Feep6$Fg\am<#Q"$F&Ten>Fg\am-F]v6$Fg\amTgn@$0Fg\amFi^`m-Tin6#Fg\am>F
hc_mF`i_m@%3/F[]amFcbmFbd_mC%>Fgj_m-F_esFhb`m@%/Fd\`mT[o>8(-Tao6$-&T]o6#Fcbm6#&
Fgj_mFgd_m-T_o6%-Fb_am6#&Fgj_mF_e_m/.FhbtFibt/.F\ctF]ct>F]_am-Fb_amFhb`m>Fhc_m-
F__am6%F]_am-Tco6#Fgiv-Fh_am6#-Fb_amF]e_m>Fhc_m-Fb_amF`h_m@$F^^am-TeoFa^am@$Fda
`mC%@$3Fej^m-Fbt6$Fhc_m.-F_`s6#Tgo>Fhc_m-Ffv6$F:Fhc_m>F^]`m7#F^]`m>Fhc_m-Fjaam6
$Fhc_m-Tio6#-Fj__mFea`m@$5/9%Fcbm/Fb_sFcbmC$>Fgj_m-Fcap6$Fhc_m.-F_`s6#Fdbam?(F_
^sF:F:F_^sF\``mC$>Fhc_m-Fchl6$<#-Fffl6$/T[p-Ffv6#-Ffv6$F:F\dam/F\damFgj_mFhc_m>
Fgj_mF^cam@$F^g_mC%>Fag_mFbg_m-Fe^s6%Fag_mQ.output~:=~%a|+F_^sFhc_mFah_mFhc_mF_
^sF_^s6^pFczF&FgcrFebclFhcrI-NumFormatterG6$I':-5812GF[dr/F_[l%,_n617181128GFhh
qFeasF_[sI=NormalizeCompositionOperatorG6$I':-5952GF[dr/F_[l%,_n617670736GFh[rF
ciblFc_rFhcblFihqI#ADG6$I':-5638GF[dr/F_[l%,_n617116352GF`dqFdgblFgfqI,mprintsl
ashGF^grF]eqI'merrorG6$F`er/F_[l%,_n617113664GF^`rF[]clF^[rF_bclF^jrF`cclF_jrF`
h^mF`jrFi_flFgirFe^flFhirFh^flFiirF[_flFjirF_`]mF[jrFb`]mF\jrFe`]mF]jrF^_flFc\r
F^]clFjiqI&StateG6$Fgt/FfzF[dqFajrFecilFbjrFddilF_irFegblFfiqI5SpecialFunctionR
ulesG6$I':-5651GF[dr/F_[l%,_n617697472GF`\rFjfblFbiqI3DisableTypesetRuleG6$I':-
5647GF[dr/F_[l%,_n617697280GFj^rFdfblF`hrF\fblF`eqFafblFhdqFcfblFadqFbfblFaiqI2
EnableTypesetRuleG6$I':-5646GF[dr/F_[l%,_n616660928GFefqF]bsFjhqF[hclFg_lFa_flF
birFhas6#F;FiasGI':-5924GF[drGI':-5925GF[drGFicclGF_^clFeg`mFg^flFeh]mFj^flFeh]
mF]_flFeg`mFa`]mFeh]mFd`]mFeh]mFg`]mFNF`_flF7FbcclF:Fbh^m^#F:F[`flFinFgcilFinFf
dilGFahblGI':-5941GF[drGI':-5942GF[drGI':-5943GF[drGFe\clGI':-5945GF[drf*6#Fjo6
+%.covariant_idxG%0N_covariant_idxGF]^p%#muGFj`]m%1contravariant_muG%2contravar
iant_idxGF]i\lFa^p6#%&cacheGk[s#-F`gbl6$-Fdgbl6#Q0equilibriumeqnsF&-FaiblF\euFc
ham-F`gbl6$Feham-Faibl6#Q"2F&Fiham!C$@&33/FdjtFcbm2F:-Fd_m6#9$'-Ffv6$7$F:FNFfia
m/.-F]t6#T%-Feep6$<#Ff\hl-_FefsFbigl6#Q3PhysicsTensorNames6"C(>8$-Fg]s6%'-Ffv6$
F;Ffiam.-F_`s6#T'7#-Ffv6#F^[bm7#F^[bm>8%-Fd_m6#Fjjam@$32F:Fi[bm4-Feen6$.-T)6#F^
avFjjamC$>Fjjam7#-.Fc[bm6#-FfvF[\bm>Fi[bmF:>Fjjam-F_[q6$;F:Fi[bmFjjam?(8&F:F;Fi
[bmFcbmC&>6$8'8(-w,6#%"mGFgjam6"Fgjam6$Ffiam7#pFgjamFgjamFgjam6#F:6$7&Fbax"%gR"
'<m7"'Rm77&FbaxFd^bm"'Dm7"'Mm76#-T+6#&Fjjam6#Fc]bm@$/Fg]bmFc\mOFfiam@$2F:-F`]y6
#Fg]bm@$/-F_ep6$Fg]bmF:Fif^mC(>8)-T-6#-F_ep6$Fg]bm;F;FNZ%C$>8,-F\gs6#F]`bm@$'Fg
`bm.FjaglC$>F]`bm-.T/Fi`bm>Fh]bm&Fh]bm6#;F:FFFgjamFgjam>&8*F__bm-Fh^m6$/Fh]bmF]
`bmF^_bm>F^_bm-.T16#Fgabm@$32F:Fc]bm/&Fjjam6#,&Fc]bmF:FNF:Fb\bmC$@$-Fagl6#&Fhab
m6#,&Fc]bmF:FFF:>&FhabmFfbbmFb\bm@%-Fagl6#F`cbm>Febbm-F^bbm6#Febbm>FebbmFbbl\@$
332F;Fc]bm/-Ffv6$F%&FjjamF]cbmF^bbmFdbbm@%Fbcbm>FebbmFecbm>FebbmFbbl@$-Fagl6#Fh
abmC)>Fhabm-Fj\bm6#-Fffl6$-Fg]s6%-FaglF`bbmFgabm-Fg]s6%/-Ffv6$F%F^_bmF^bbmF^_bm
-Fg]s6%/F^_bmFbblFbbl-F^bbmF]_bm/Fc]bmFa]bm>Fjjam-Fj\bm6#-Fffl6$F^_bmFiebm>Fg]b
m-Ffv6$F:Fhabm@$0-Ffv6$F%Fg]bmF^bbmC$>Fhabm-Fh^m6$/F:6$.-F_bbm6#-Fd\bm6#F][vFg]
bmFhabm>Fjjam-Fh^m6$/F:6$F\gbm-Ffv6$F:FjjamFjjam>8+-Ffv6$F:Ffiam@$0-Ffv6$FNFigb
m/F_jamQ+Physicsmb_Fgjam>Figbm-Fh^m6$/F:-Fey6$-Ffv6$F:Figbm.F\uFigbmO-T36&Figbm
FjjamFhabm/F_jamQ5PhysicsTensorIndicesFgjam'Fjgbm.-F_`s6#T5C&>Fg`bm-Fh^m6$/F:-F
fv6$7$F:F:FfiamFfiam>Fg`bm-9!6$Fg`bm&9"6#Fc`bm>Fg`bm-Fh^m6$/F:FjgbmFg`bmOFg`bmF
fiamFgjamFgjam66FczF&F]gqFdhblFhdqFcfblFadqFbfblFjjrI/GetRootOfIndexG6$I':-5947
GF[dr/F_[l%,_n617183704GF[[sI3GreekLetterToGliphG6$I':-5948GF[dr/F_[l%,_n617701
024GF_dqFaiblF_eqI)mphantomG6$Fber/F_[l%,_n617174272GFdeqFd`^mFefqF]bsFcgblGF][
cmGFb[cmf*6%%(op_T_mkG%%op_TGFjo6(F\a^m%#t0G%%op_tGFdcs%)ac_colorG%)nc_colorG6"
Ffj`mC$@$3/FdjtFcbm5'-Ffv6$F%9$.-F]t6%T%T'T)-Feen6$./T+F_cuF[]cmC$>6$8(8)-Ffv6#
-Fdcp6%F]doQ#%sFfj`m7$-_FefsFiigl6#Fij`m-Fc^cm6#Fej`m@$350Fj]cmFjjgl0F[^cmFjjgl
4-Fhbl6$/.F_el-.Fd[oFi]cmF[]cmZ%C$>8$-Fhes6#9&@&'Ff_cm.F^inC%>8&-Fhes6#9%>8%-Ff
v6$F%Ff_cm@$5/F_`cmFd`cm3'Fd`cm-.F`cl6#-.F]t6#-Ffv6#-_FefsFbigl6#Fdigl'Fd`cm.%&
c_varGC$@&'F_`cm.-F`cl6#%'ac_varG@$3Fj^cm'Ff_cm.F`bcm>8'/._Ffj`mF^[hlFj]cm'F_`c
m.-F`cl6#%'nc_varG@$3F[_cm'Ff_cm.F^ccm>Ffbcm/FhbcmF[^cm@$-Fagl6#FfbcmO-Fh^m6$/F
N6$-Ffv6$FNF[]cmFfbcmF[]cm'Ff_cm.Fa[mC$@&Fbbcm>Ffbcm/._Ffj`mF`hwFj]cmF`ccm>Ffbc
m/FedcmF[^cm@$FfccmO-.T-6$F[]cmFfbcmFfj`mFfj`mF[]cmFfj`mFfj`m6.FczF&F`dqFdgblF_
dqFaiblFadqFbfblF]gqFdhblF\eqF]dilF_gblGI':-5950GF[drGFb^flGFaeambF]]lFchrF&Fjg
rF&F&F&F&F&F[bsGI':-5614GF[drGI':-5615GF[drGI':-5616GF[drf*6$%#xaG%'loc_inG6+%$
locG%%dismGFj[dl%&ocontG%%rdirG%%ToBrG%(SumTypeG%(PrdTypeGF]cs6#F[ds6"C?@$/%6_E
nv_Debug_NeedsBraceGFcbm-%'lprintG6%%-Needsbrace:~G-Fhes6#9$9%>8(-Fg]s6%29#F<Fi
n-F_ht6#/&9"6#F<.F\`t@$/%B_Env_Debug_Typesetting_PrecedenceGFcbm-Fhfcm6(%7Enter
~with~Expression=GF[gcm%',~Loc=GF^gcm%&~Dir=GF`gcm@'-Feen6$F^gcm<0T%T'T)T+T-T/T
1T3T5T7T9T;T=T?Y6$Q;invalid~location~value:~%1FbfcmF^gcm5-Feen6$F^gcm<9FinTATCT
ETGTITKTMTOTQTSTUTWTYTenTgnTinT[oT]oT_oTaoTcoTeo3/F^gcmTgoF`gcmOFin>8$-Fchl6//Q
$SumF&Q$sumF&/Q&LimitF&Q&limitF&/Q(ProductF&Q(productF&/Q%EvalF&F`eu/Q$IntF&Q$i
ntF&/Q&intatF&Fh\dm/Q&IntatF&Fh\dm/Q$NotF&Tio/Q$AndF&T[p/Q#OrF&T]p/Q$XorF&T_p/Q
(ImpliesF&TapF^gcm>8%7#-F_esF\gcm@;3/&F]^dm6#F:Tcp2F:-Fd_m6#7#-Fhes6#&F]^dm6#F;
OFin3Fb^dm/-Fey6$Fj^dm.F\uFbfwO-9!6$&F]^dmFjgcmF^gcmFb^dmC'>8,7#-F_esF[_dm@'/&F
[`dmFd^dmFfjcmC$>8&-TepF[_dm@$0Fc`dmF%>F]^dm-Fh^m6$/F;Fc`dmF]^dm3/F``dmF]icm0&F
[`dmF]_dmF%C$>Fc`dm-Fe`dm6#F_adm@$Fg`dm>F]^dmFi`dm>Fc`dmF%>F[`dm-Fey6$-Fey6$Fj^
dmFeauFc_dm@$/F``dmF_dp>F[`dm&F[`dm6#;F;FN@Q3/Fc`dmF%/-Tgp6#Fj^dm-F_jx6$.FefsF^
il>Fc`dmQ#*aF&3Fdbdm5-Feen6$Fj^dm<(Fbbl._Fbfcm%&%CurlG._Fbfcm%'%NablaG._Fbfcm%,
%DivergenceG._Fbfcm%*%GradientG._Fbfcm%+%LaplacianG-Feen6$Ffbdm<(Fbbl-F_jx6%F[c
dm.F`jhl.%%CurlG-F_jx6%F[cdmFgddm.Fajhl-F_jx6%F[cdmFgddm.Fdjhl-F_jx6%F[cdmFgddm
.%)GradientG-F_jx6%F[cdmFgddm.%*LaplacianG>Fc`dmQ#.nF&-Feen6$F[`dm<%Q0delayDotP
roductFbfcmQ/delayLaplacianFbfcmQ2delayCrossProductFbfcm>Fc`dmFiedm/F[`dmQ%diff
F&C$>F[`dm-T[q6#-TipF\gcm@+333/-Ffv6$F%F[`dmT]q2F;-Fd_m6#F[`dm/-Ffv6$FFF[`dm-T_
q6#Fgiv0-Ffv6$7$F:F%F[`dmTaq>Fc`dmQ(diffdepFbfcm3/F_gdmTcq/-Ffv6$7$F;F%F[`dmTeq
>Fc`dmQ(diffnumFbfcm-Feen6$F_gdm<$TgqTiq>Fc`dmQ(diffdotFbfcm33F^gdm/FcgdmF;/Ffh
dmFigdm>Fc`dmQ*diffprimeFbfcm>Fc`dmFbfdm-Feen6$F[`dm<1Fg]amQ#&*F&Q"@F&Q#@@Fbfcm
FgialQ&minusF&Fae`lQ%modpFbfcmQ%modsFbfcmQ'subsetF&Q&unionF&Q)assumingF&Q0doubl
efactorialFbfcmQ*factorialFbfcmQ*intersectF&>Fc`dm-Fchl6%/FajdmFae`l/FbjdmFae`l
F[`dm-Feen6$F[`dm<(F_\dmFb\dmF\\dmF`\dmFc\dmF]\dm>Fc`dm-Fchl6&F[\dmF^\dmFa\dmF[
`dm-Feen6$F[`dm<$Fe\dmF`eu>Fc`dmF`eu-Feen6$F[`dm<$Q*PIECEWISEFbfcmQ*piecewiseFb
fcm>Fc`dmF]\dm-Feen6$F[`dm<&Fg\dmF\]dmFh\dmFj\dm>Fc`dmFh\dm-Feen6$F[`dm<%Q$expF
bfcmQ%sqrtFbfcmQ%surdFbfcm>Fc`dmFe[dm3-Feen6$F[`dm<$Q$&+-FbfcmQ$&-+Fbfcm/-Fd_m6
#7#-F_es6#Fh_dmF;>Fc`dmF\c[m/F[`dmQ#&xF&>Fc`dmFg]em/F[`dmF\\el@%/Fj^dm._FbfcmI"
.G6$FgtFht>Fc`dmF\\el>Fc`dmFiedm-Feen6$F[`dm<$Fc`[mF^j\l>Fc`dmT[r-Feen6$F[`dm<$
Q"*FbfcmQ"/Fbfcm>Fc`dmT]r/F[`dmFeael>Fc`dmFe[dm/F[`dmQ"=Fbfcm>Fc`dmT_r/F[`dmQ#<
>Fbfcm>Fc`dmTar3-Feen6$F[`dm<'Fa]dmFj]dmF^]dmFd]dmFg]dm4-Feen6$F[`dmTcrC$>8'F[`
dm>Fc`dm-Fchl6(F]]dmF`]dmFc]dmFf]dmFi]dmF[`dm-Feen6$F[`dm<'Q$andFbfcmQ(impliesF
&Q$notFbfcmQ#orFbfcmQ$xorFbfcm>Fc`dm-Fchl6(/F[aemF_]dm/Fi`emFb]dm/F\aemFe]dm/F]
aemFh]dm/Fj`emF[^dmF[`dm32F:-F`]yFdgdm/&F[`dm6#;F:F:Fhit>Fc`dmFhit/F[`dmQ%mrowF
bfcm>Fc`dmFf^em/F[`dmQ(mfencedFbfcm>Fc`dmFe^dm>Fc`dmFc^dm/Fc^dmFfjcm@%/<#-Fhes6
#&F]^dm6#F=<$.Ffw.Few>Fc`dmF`e_l>Fc`dmFfjcm3/Fc^dmF]_em/-Fd_m6#F]^dmF<>Fc`dmFe[
dm/Fc^dmFihcm>Fc`dmFf^em/Fc^dmF]jcm>Fc`dmF]_em/Fc^dmF^jcm@%/FecemF;>Fc`dm-Fg]s6
%/Fj^dmF:F]icmF]_em>Fc`dmFf^em-Feen6$Fc^dm<$FjhcmF[icmC$>F[`dmF[gcm@%3-Fbt6$F[`
dm.F^cl2F[`dmF%>Fc`dmFf^emC$>F[`dm-&_FffdmF`hr6#FcbmF\gcm@%-Fbt6$F[`dm-.F_`s6#F
agdm>Fc`dmF]_em>Fc`dmFjhcm/Fc^dmTer@'/FecemF:OFinF^demO-Ff_dm6$F\_dm&Figcm6#;F;
Fdgcm>Fc`dmFc^dm3/Fc^dmFf^emFdcem>Fc`dmF]_em/Fc^dmTgr>Fc`dmFf^em>Fc`dmFc^dm@$3-
Feen6$Fc`dm<%F`\dmFc\dmF]\dm2F%-Fd_m6#F[gcm@$-Tir6$-Fifs6#-Ffv6$F:F[gcmF]\dm>Fc
`dm-Fcgo6$Fc`dmQ"bF&@$F]hcm-Fhfcm6(%9Process~with~Expression=GF[gcm%(,~Cont=GFc
`dmFbhcmFh[dm@$3/F^gcmFd]dm/Fb`emFa]dmOFcbm@$-Feen6$Fc`dm<=FhhcmF\icmF]icmF^icm
F_icmF`icmFaicmFbicmFcicmFdicmFeicmFajcmFbjcmFcjcmFejcmFfjcmFgjcmFhjcmFijcmFjjc
mF[[dmF\[dmF][dmF^[dmF_[dmFa[dmFb[dmOFin@*/Fh[dmT[sO-F_ht6#/Fc`dmFfiem/Fh[dmFej
dmO-Feen6$Fc`dm<#Ffiem/Fh[dmF_femO-Feen6$Fc`dm<%FejdmF_femFfiem/Fh[dmF`e_l@'Fbj
emOFcbm/Fc`dmF`e_lO4F`gcmOFin>8)6'FfjcmF_femFejdmFfiemF`e_l@2/Fh[dmQ$iffF&O-Fee
n6$Fc`dm<#F][fm/Fh[dmF[^dm@%F`gcmO-Feen6$Fc`dm<%Fa[fmF][fmF[^dmO-Feen6$Fc`dm<$F
a[fmF][fm/Fh[dmFh]dm@%F`gcmO-Feen6$Fc`dm<'Fa[fmQ$norF&F][fmFe]dmF[^dmOFi[fm/Fh[
dmFe]dm@%F`gcmO-Feen6$Fc`dm<'Fa[fmFf\fmF][fmFh]dmF[^dmOFi[fm/Fh[dmFf\fm@%F`gcmO
-Feen6$Fc`dm<(Fa[fmFf\fmF][fmFe]dmFh]dmF[^dmOFi[fm/Fh[dmFb]dm@%F`gcmO-Feen6$Fc`
dm<)Fa[fmQ%nandF&Ff\fmF][fmFe]dmFh]dmF[^dmOFb]fm/Fh[dmF\^fm@%F`gcmO-Feen6$Fc`dm
<*Fa[fmF\^fmFf\fmF][fmFb]dmFe]dmFh]dmF[^dmOFb]fm/Fh[dmF_]dm@$50F^gcmF^]dm-Feen6
$F^]dmF_`emOFa^fm>F][fm-Feep6$-Feep6$Fe[fmT]s<%Fa[fmF\^fmFf\fm@,/Fh[dmFg]amO-Fe
en6$Fc`dm-Feep6$F][fm<#Fg]am-Feen6$Fh[dm-Feep6$T_s<#FgialO5-Feen6$Fc`dm-Feep6$-
Feep6$F][fmF_`fm<$Fg]amFgial3FhjemF`gcm/Fh[dmTasO-Feen6$Fc`dm-Feep6$Fg`fm<%Fg]a
mFgialF\afm/Fh[dmFcjdmO-Feen6$Fc`dm-Feep6$Fg`fm<&Fg]amFgialFcjdmF\afm/Fh[dmFae`
lO-Feen6$Fc`dm-Feep6$Fg`fm<'Fg]amFgialFae`lFcjdmF\afm>F][fm-Feep6$Fg`fm<+Fg]amF
gialFae`lFcjdmF_jcmF`jcmFdjcmF`[dmF\afm>8*6%Ff^emFdjdmF`jdm@$-Feen6$Fh[dm<#Ffbf
m@)-Feen6$Fc`dm-Feep6$F][fmFegemOFcbm-Feen6$Fc`dmF[cfmOF`gcm33/Fh[dmFf^emFdcemF
[gemO-F_ht6#3F`gcm-Fbt6$-FhesFd]em.%)negativeGOFin>F][fm-Feep6$F][fm<$FbfdmFfbf
m@$Fe^fmO-Feen6$Fc`dm-Feep6$F][fm<#Tcs@*/Fh[dmF\c[mO-Feen6$Fc`dm-Feep6$F][fm<#F
\c[m-Feen6$Fh[dm<)F\c[mF`\dmQ'limitbF&Fc\dmF]\dmQ%sumbF&Q)productbF&O5-Feen6$Fc
`dm-Feep6$F][fm<%FhitF]jdmF\c[m33/Fc`dmF]_emFdcem/F^dfmFN/Fh[dmF`euO-Feen6$Fc`d
m-Feep6$F][fm<,FhitF]jdmF\c[mF`euF`\dmFiefmFc\dmF]\dmFjefmF[ffm/Fh[dmFh\dmOFiff
m>F][fm-Feep6$F][fm<+F\c[mF`euFh\dmF`\dmFiefmFc\dmF]\dmFjefmF[ffm>8+6+F\\elFied
mFg]emF]_emF]cdmF^jdmFhjdmF]jdmF[f[m@,3-Feen6$Fh[dm<%Fg]emF\\elFiedm-Feen6$Fc`d
mF[hfmO-Fg]s6%3/Fh[dmF\\el/Fc`dmF\\elF`gcmFcbm3/Fh[dmF[f[m-Feen6$Fc`dm<(Fg]emF]
cdmF\\elFiedmFbfdmF]_emOFin53Figfm-Feen6$Fc`dm<$F]cdmF]_em3F\hfm-Feen6$Fh[dmF^i
fmOFcbm53/Fh[dmF]cdmFeffm3/Fh[dmF]_em/Fc`dmF]cdmOFin-Feen6$Fh[dm<#Fegfm@'-Feen6
$Fc`dmF][fmOFcbm-Feen6$Fc`dmF\jfm@'5/Fh[dmF]jdm/Fc`dmF]jdmOFcbm32F:Fecem/Fj^dmF
^ilOFinOF`gcmOFin>F][fm-Feep6$F][fm<&FbidmF[idmFhidmFegfm@(-Feen6$Fh[dm<$F_jdmF
e[dmO-Feen6$Fc`dm-Feep6$F][fm<%F]jdmF_jdmFe[dm-Feen6$Fh[dm<$FfjdmFgjdmO-Feen6$F
c`dm-Feep6$F][fm<)FhitF]jdmF_jdmFahdmFfjdmFgjdmFe[dm/Fh[dmFhitOF`\gm>F][fmFb\gm
@,/Fh[dmTesO-Feen6$Fc`dm-Feep6$F][fm<#Fj\gm/Fh[dmFe^dm@%/Fac_mFcbmO-Feen6$Fc`dm
-F]v6$F^]gm<#F_jdmOF\]gm/Fh[dmTgs@%/Fc`dmF\^gmOFjjemOF\]gm/Fh[dmTis@'-Feen6$Fc`
dm-Feep6$F][fm<%Fe^dmFj\gmF\^gmOFcbm/Fc`dmFj\gmOF`gcmOFin/Fh[dmT[t@'-Feen6$Fc`d
m-Feep6$F][fm<&Fe^dmFj\gmF\^gmF^_gmOFcbm/Fc`dmF^_gmOF`gcmOFinY6$Q3unhandled~cas
e:~%1FbfcmFh[dmFbfcmFbfcm6\tFczF&Fb^rFj^clFa^rF^iblFd^rI&FLOATG/F_[l/FfzF[dqFe^
rI'HFLOATG/F_[l/FfzF[dqFg^rFddblFh^rFgfblFd`rF_dclFe`rFbdclFj`rFa]clF[arFd]clF
\arFg]clFbarF][dlFcarF`[dlFdarFdfclFc^rFiiblFf^rFf_flF__rF[iclF`_rF^iclFb`rFdic
lFc`rFh\clFf`rFbbclFg`rFhhclFh`rFehclFi`rF[\clF]arF_jclF^arF\jclF_arFafclF`arFe
eclFaarFheclFearFbjclFfarFjdclFgarF]eclFharFejclFiarFc[dlFjarF[fclF[brF^fclF]_r
FehblFi_rFd`clFh_rFj`clFj_rF]aclF[`rF`aclF\`rI(IMPLIESG/F_[l/FfzF[dqFc_rFhcblFe
crF^\clFccrFj]clFihqFdeamF`gqFjasFhdqFcfblFadqFbfblFidqFbiblFceqF]_clF`eqFafblF
feqF^_clFjeqI)mscriptsG6$F`fr/F_[l%,_n617174472GFa_rFjjblF^_rFdjblFd_rF_`clFe_r
Fj_clF`\rFjfblF]`rFc[clFb_rF][clFdgqF^fblFa`rFiaclFdbrFg`clFebrFb_clF_`rFcaclF^
`rF[]clF[_rFceblFj^rFdfblFi^rF[dblF\_rFfeblF_fblGI':-5618GF[drGI':-5619GF[drf*6
#%"lG6"6"F_agm-%)assembleG6#-Ffv6#-F`w6$f*6#FgiuF_agm6%FewF[dsFfwF_agm-Fg]s6%-F
bt6$F^xF\gvF[c\lF^xF_agmF_agm6$FggqT%9$F_agmF_agm6&FczF&FggqFfiblFgiblGI':-5621
GF[drGI':-5622GF[drGI':-5623GF[drGI':-5624GF[drGF]cilGI':-5626GF[drGI':-5627GF[
drGI':-5628GF[drGFidilGI':-5630GF[drGI':-5631GF[drGI':-5632GF[drGI':-5633GF[drG
I':-5634GF[drGI':-5635GF[drGI':-5636GF[drGFfasGFfeamGF]hclGI':-5640GF[drGI':-56
41GF[drGI':-5642GF[drGI':-5643GF[drGI':-5644GF[drGI':-5645GF[drGF]gamGFhfamGI':
-5648GF[drGI':-5649GF[drGI':-5650GF[drGFcfamGI':-5652GF[drGI':-5653GF[drGI':-56
54GF[drf*6"F^dgm6"F^dgm@'/-Fc^il6$Q=Standard~Worksheet~InterfaceF&-Faco6#._F^dg
mFdailF%Q$ttyF^dgm/-Faco6#._F^dgm%,typesettingG._F^dgm%)extendedGF]j`mQ)standar
dF^dgmF^dgmF^dgm6$FczF&F_famGI':-5656GF[drGI':-5657GF[dritf*6"Fhegm6"Fhegm-T%Fh
egmFhegmFhegm6&FczF&FefqF]bs/FfzF[dqGI':-5659GF[drGI':-5660GF[drGI':-5661GF[drG
I':-5662GF[drGI':-5663GF[drGI':-5664GF[drGFjcilGFh[clGFhbilGI':-5668GF[drGI':-5
669GF[drGI':-5670GF[drGI':-5671GF[drGI':-5672GF[drGI':-5673GF[dr<JI(mactionG6$F
gfr/F_[l%,_n617114656GI&maddrG6$Fcgr/F_[l%,_n617115136GI(matomicG6$Fbgr/F_[l%,_
n617115072GFjeamFafblFbiblI'mglyphG6$Fgdr/F_[l%,_n617113216GFdgblFaiblFbfblF^_c
lI(mpaddedG6$Faer/F_[l%,_n617113728GF`jblFcfblF_eblFgcblF\jblF]dilF`gblFd`^mF]_
clFccclFhbclI&mtextG6$Fcdr/F_[l%,_n617113024GF\cclI'munderG6$F[fr/F_[l%,_n61711
4112GI%noneG6$Fhdr/F_[l%,_n617113280GI,maligngroupG6$Fffr/F_[l%,_n617174592GI+m
alignmarkG6$Fefr/F_[l%,_n617174552GF]bsI)mdisplayG6$Fcfgm/F_[l%,_n617179248GI)m
encloseG6$Feer/F_[l%,_n617174312GI+mlabeledtrG6$Fdfr/F_[l%,_n617174512GI.mmulti
scriptsG6$F^fr/F_[l%,_n617174392GFe[cmI,mprescriptsG6$F_fr/F_[l%,_n617174432GFf
`gmFdhblI+munderoverG6$F]fr/F_[l%,_n617174352GFhgblFabclGI':-5675GF[drGI':-5676
GF[drGI':-5677GF[drGI':-5678GF[drGFidbl=F&FinE\[l!FebilGI':-5681GF[drGI':-5682G
F[drGI':-5683GF[dr=F&FinE\[l!FeiblGI':-5685GF[drGI':-5686GF[drGI':-5687GF[drGI'
:-5688GF[drGI':-5689GF[drGI':-5690GF[drGI':-5691GF[dr<`vQ'AiryAiF&Q(AiryAi2F&Q'
AiryBiF&Q(AiryBi2F&Q'AngerJF&Q(BesselIF&Q(BesselJF&Q(BesselKF&Q(BesselYF&Q%Beta
F&Q&DiracF&Q'Dirac2F&Q&GAMMAF&Q'GAMMA2F&Q&HeunBF&Q&HeunCF&Q&HeunDF&Q&HeunGF&Q&H
eunTF&Q(JacobiPF&Q(KummerMF&Q(KummerUF&Q$PsiF&Q%Psi2F&Q(StruveHF&Q(StruveLF&Q'W
eberEF&Q%ZetaF&Q&Zeta2F&Q&ZetaHF&Q'ZetaH3F&Q&eulerF&Q'eulerNF&Q(lnGAMMAF&Q(poly
logF&Q)AppellF1F&Q)AppellF2F&Q)AppellF3F&Q)AppellF4F&Q+ChebyshevTF&Q+ChebyshevU
F&Q)CoulombFF&Q*CylinderDF&Q*CylinderUF&Q*CylinderVF&Q+EllipticCEF&Q+EllipticCK
F&Q,EllipticCPiF&Q*EllipticEF&Q+EllipticE2F&Q*EllipticFF&Q*EllipticKF&Q0Ellipti
cModulusF&Q-EllipticNomeF&Q+EllipticPiF&Q,EllipticPi3F&FifdlQ)FresnelCF&Q)Fresn
elSF&Q)FresnelfF&Q)FresnelgF&Q,GegenbauerCF&Q)HankelH1F&Q)HankelH2F&Q*Heaviside
F&Q)HermiteHF&Q+HeunBPrimeF&Q+HeunCPrimeF&Q+HeunDPrimeF&Q+HeunGPrimeF&Q+HeunTPr
imeF&Q0InverseJacobiAMF&Q0InverseJacobiCDF&Q0InverseJacobiCNF&Q0InverseJacobiCS
F&Q0InverseJacobiDCF&Q0InverseJacobiDNF&Q0InverseJacobiDSF&Q0InverseJacobiNCF&Q
0InverseJacobiNDF&Q0InverseJacobiNSF&Q0InverseJacobiSCF&Q0InverseJacobiSDF&Q0In
verseJacobiSNF&Q)JacobiAMF&Q)JacobiCDF&Q)JacobiCNF&Q)JacobiCSF&Q)JacobiDCF&Q)Ja
cobiDNF&Q)JacobiDSF&Q)JacobiNCF&Q)JacobiNDF&Q)JacobiNSF&Q)JacobiSCF&Q)JacobiSDF
&Q)JacobiSNF&Q-JacobiTheta1F&Q-JacobiTheta2F&Q-JacobiTheta3F&Q-JacobiTheta4F&Q+
JacobiZetaF&Q*KelvinBeiF&Q*KelvinBerF&Q*KelvinHeiF&Q*KelvinHerF&Q*KelvinKeiF&Q*
KelvinKerF&Q*LaguerreLF&Q+LaguerreL3F&Q)LambertWF&Q*LambertW2F&Q*LegendrePF&Q+L
egendreP3F&Q*LegendreQF&Q+LegendreQ3F&Q)LerchPhiF&Q)LommelS1F&Q)LommelS2F&Q)Mat
hieuAF&Q)MathieuBF&Q)MathieuCF&Q*MathieuCEF&Q/MathieuCEPrimeF&Q.MathieuCPrimeF&
Q)MathieuSF&Q*MathieuSEF&Q/MathieuSEPrimeF&Q.MathieuSPrimeF&Q,MeijerG_TblF&Q+Ph
ysicsBraF&Q/PhysicsBracketF&Q,PhysicsCurlF&FaayQ.PhysicsDaggerF&Q.PhysicsDgamma
F&Q+PhysicsDotF&Q/PhysicsFundiffF&Q0PhysicsGradientF&Q/PhysicsInverseF&Q+Physic
sKetF&Q,PhysicsNormF&Q/PhysicsProductF&Q.PhysicsPsigmaF&Q+Physics_GFF&Q+Physics
_NPF&Fg`yQ*Physicsg_F&Q+SphericalYF&Q*Stirling1F&Q*Stirling2F&Q-WeierstrassPF&Q
0WeierstrassZetaF&Q+WhittakerMF&Q+WhittakerWF&Q,WrightomegaF&Q*bernoulliF&Q+ber
noulliNF&Q)harmonicF&Q*harmonicNF&Q*hypergeomF&Q.hypergeom_TblF&Q+pochhammerF&Q
*stirling1F&Q*stirling2F&Q6PhysicsAntiCommutatorF&Q2PhysicsCommutatorF&Q1Physic
sComponentF&Q2PhysicsDivergenceF&Q6PhysicsKroneckerDeltaF&Q1PhysicsLaplacianF&Q
2PhysicsLeviCivitaF&Q4PhysicsNabla(1-arg)F&Q4PhysicsNabla(2-arg)F&Q4PhysicsVect
orsCrossF&Q2PhysicsVectorsDotF&Q3PhysicsVectorsPlusF&Q4PhysicsdAlembertianF&Q2W
eierstrassPPrimeF&Q1WeierstrassSigmaF&F\gblGI':-5693GF[drGFg^cl=F&FinE\[l5Q0num
ericalderivsF&FcbmQ'usedotF&FcbmQ0numberfunctionsF&FinQ%usedF&FinQ+autoatomicF&
FcbmQ'userepF&FinF^[zFinF]fzF\a^mFgi`mFinQ/functionassignF&FcbmFggyFinQ/strictb
racketsF&FinFffwFinQ*toleranceF&FinF\bzF=F`]elFinQ)useprimeF&FcbmF[[zFinQ,inlin
eprimeF&FcbmF]azFduF`]clGI':-5696GF[drGI':-5697GF[dr<9Fj`emFgialF`jdmFcjdmFdjdm
Fb`[lQ-&gt;&equals;F&FbjzF][[lFj^_lQ,Logic:-&andF&Q,Logic:-&iffF&Q0Logic:-&impl
iesF&Q-Logic:-&nandF&Q,Logic:-&norF&Q,Logic:-&notF&Q+Logic:-&orF&Q,Logic:-&xorF
&FhjdmQ3&amp;&minus;&plus;F&Q3&amp;&plus;&minus;F&Q1&lt;&hellip;&gt;F&F^]tF[fbl
GI':-5699GF[drGI':-5700GF[drf*6#Fa_o6%F]csF^csFg_l6#F[ds6"C-@$4-Fbt6$9$.F\uOFhi
hm>8$Fhihm>8%Fbbl>8&-Fc^il6$Q.#mglyph(alt~=F&Fhihm@$/F`jhmF%OFhihm@$3/&F\jhm6#F
:Fdcfl/&F\jhm6#FNFdcflC$>F\jhm&F\jhm6#;F;FF>F`jhm,&F`jhmF:FNF:?(FbihmF:F:Fbihm2
F%F`jhmC'>F^jhm6$F^jhm&F\jhm6#;F:Fe[im>F\jhm&F\jhm6#;F`jhmFN>F`jhm-Fc^il6$Q")Fb
ihmF\jhmZ%C%@$FejhmYFbihm>T%7#-F\gs6#&F\jhm6#;FbpF`jhm@%33-Fbt6$F[]im-.F^_l6#F`
`p/-Fd_m6#F[]imF</-F`w6$Ffiy<#-FfvF\^im<%.%$altG.%&indexG.%+fontfamilyGC$>F^jhm
6$F^jhm-T'6#Fa^im>F\jhm&F\jhm6#;,&F`jhmF:F:F:FNYFbihmFbihm[>F`jhm-Fc^il6$FcjhmF
\jhm>F^jhm7$F^jhmF\jhm?(F`jhm,&-Fd_m6#F^jhmF:FNF:FNF:Fcbm@&3-Fbt6$&F^jhm6#F`jhm
Fiihm-Fbt6$&F^jhm6#Fc_imFiihm>F^jhm-Fh^m6%/Fc_imFbbl/F`jhm-Fcgo6$Fc`imFg`imF^jh
m/Fg`imF]u>F^jhm-Fh^m6$F\aimF^jhm@$32F:F]`im/&F^jhmF[[imF]u>F^jhm&F^jhm6#;F;FN-
FfvF^`imFbihmFbihm6(FczF&FajqI$varG6$F`fgm/F_[l%,_n617120992GFfdqFgggmF^eblGI':
-5702GF[dr=F&FinE\[lenQ'LambdaF&Q)&Lambda;F&Q&DeltaF&Q(&Delta;F&Q&alephF&Q(&ale
ph;F&Q$TauF&Q&&Tau;F&Fd]hmQ&&Psi;F&Q&varpiF&Q(&varpi;F&Q&AlphaF&Q(&Alpha;F&Q(om
icronF&Q*&omicron;F&Q&omegaF&Q(&omega;F&Q)varkappaF&Q+&varkappa;F&Q#muF&Q%&mu;F
&Q&OmegaF&Q(&Omega;F&Fj\hmQ(&Gamma;F&Q%ZETAF&Q'&Zeta;F&Q'varphiF&Q)&varphi;F&Q&
KappaF&Q(&Kappa;F&Q'varrhoF&Q)&varrho;F&Q+varepsilonF&Q-&varepsilon;F&Q$phiF&Q&
&phi;F&Q$tauF&Q&&tau;F&Q&ThetaF&Q(&Theta;F&Q%betaF&Q'&beta;F&Q&gammaF&Q(&gamma;
F&Q(epsilonF&Q*&epsilon;F&Q#xiF&Q%&xi;F&Q#MuF&Q%&Mu;F&Q#ReF&Q%&Re;F&Q#ImF&Q%&Im
;F&Fi]hmQ'&zeta;F&Q#XiF&Q%&Xi;F&Q&thetaF&Q(&theta;F&Fg\hmQ'&Beta;F&Q'lambdaF&Q)
&lambda;F&Q&kappaF&Q(&kappa;F&Q$PhiF&Q&&Phi;F&Q$chiF&Q&&chi;F&Q(upsilonF&Q*&ups
ilon;F&Q#NuF&Q%&Nu;F&Q&SigmaF&Q(&Sigma;F&Q#PiF&Q%&pi;F&Q)varthetaF&Q+&vartheta;
F&Q&deltaF&Q(&delta;F&Q(EpsilonF&Q*&Epsilon;F&Q)varsigmaF&Q+&varsigma;F&Q&sigma
F&Q(&sigma;F&Q$CHIF&Q&&Chi;F&Q(OmicronF&Q*&Omicron;F&Q$etaF&Q&&eta;F&Q$EtaF&Q&&
Eta;F&Q%IotaF&Q'&Iota;F&Q(UpsilonF&Q'&Upsi;F&Q&alphaF&Q(&alpha;F&Q$rhoF&Q&&rho;
F&Q#PIF&Q%&Pi;F&Q#nuF&Q%&nu;F&Q%iotaF&Q'&iota;F&Q$psiF&Q&&psi;F&Q$RhoF&Q&&Rho;F
&FcdilGI':-5704GF[drGI':-5705GF[drGI':-5706GF[drGI':-5707GF[drGI':-5708GF[drGI'
:-5709GF[drGI':-5710GF[drGI':-5711GF[drGI':-5712GF[drGI':-5713GF[drGI':-5714GF[
drGI':-5715GF[drGI':-5716GF[drGI':-5717GF[drGI':-5718GF[drGI':-5719GF[drGI':-57
20GF[drGI':-5721GF[drGI':-5722GF[drGI':-5723GF[drGI':-5724GF[drF:F`iblF;F\_clF<
F[jblF=F_`gmF>Fb`gmF?Fh_flFMFfdblFbpFifblFci_lF]dblF7Fffbl"#6FeeblFaeoFheblFeio
Fghbl"#9Ffjbl"#:F]iclF][jmF`icl"#;F\[cl"#<F_[cl"#?FjcblGFa`clGF\`clGFg_clGI':-5
747GF[dr"#EF\aclFe`oFf`cl"#GF_acl"#HFbacl"#IFe`gm"#JFe[cl"#KF]]cl"#PFeacl"#QF^b
cl"#VF[bcl"#[Fficl"#RFj\cl"#eFadcl"#dFddclF$Fdbcl"#=Fjhcl"#@Fghcl"#OF]\cl"#MFc]
cl"#LFf]cl"#NFi]cl"#WFajcl"#XF^jcl"#\FcfclF)Fgecl"#_Fjecl"#`F_[dl"#aFb[dl"#cFff
cl"#^Fdjcl"#YF\ecl"#ZF_eclFehoFgjcl"#>Fe[dl"#TF]fcl"#UF`fclGFifclGF^gclGFcgclGF
hgcl<'F:F;F<F=F>Fcicl<(F:F;F<F=F>F?F`dbl<*FbpFci_lF7F[[jmFaeoFc\jmFb\jmFd\jmFd^
clGI':-5791GF[dr<'Fb[jmFe`oFc[jmFd[jmFe[jmFi`cl<&"#AFjdo"#CFbuFd_clGI':-5794GF[
drGI':-5795GF[drGI':-5796GF[drGI':-5797GF[drGI':-5798GF[drGFjjclGFbeclGI':-5801
GF[drGFiiclGI':-5803GF[drGI':-5804GF[drGI':-5805GF[drGI':-5806GF[drf*6#%'ref_in
G6%%$refG%%mseqGF\\dl6"6"C)>8$9$>8%Fbbl>8&7#-Fj\m6#F^_jm@$3/-Fd_m6#Fc_jmF:-Fbt6
$&Fc_jm6#F:.F^_l>Fc_jmF^`jm>Fc_jm-Fbdp6$f*FfiuF&6$FewFfwF&3Fbiy-Feen6$FeiyF\dxF
&F&F&Fc_jm?(F[_jmF:F:F[_jm0Fc_jm7"C)>Fa_jm6$-Ffv6$F:-Fi`_lFf_jmFa_jm>F^_jm-Fghp
6#F^`jm@$43-Feen6$&-F_es6#-FifsFf_jmF_`jm<$T%T'-Fbt6$F^_jm.FigtO-F_jx6#F^x@$-Fb
t6$F^_jm.F^inC$>Fa_jm6$-Ffv6$F:F^_jmFa_jm>F^_jm-Ffv6$F%F^_jm>Fc_jmFd_jm@$Fh_jm>
Fc_jmF^`jm>Fc_jm-Fbdp6$f*6#FgiuF[_jm6$FewFfwF[_jmFg`jmF[_jmF[_jmF[_jmFc_jm-F`w6
%Fey-F_jxF_ajm.FfhnF[_jmF[_jm6(FczF&Fh^rFgfblFj^rFdfblF\^clGI':-5808GF[drGF`\cl
GI':-5810GF[drF,FgbclGF\eamGFc_flGI':-5814GF[drbF]]lF]jq6#FiipF]dqF&F&F&F&F&6$F
gtFht,
I(iniconc7(F;F;F;F;F;F;F&,
I%K_G_F^eoF&,
I'f_CO2_FdeoF&,
I%viDbF%F&,
I(nsolidsF>F&,
I*variablesFacqF&,
I*alphadata7($F7!#6FaejmFaejmFaejmFaejmFaejmF&,
I,StringToolsy6gw%'LengthG%(IsUpperG%(IsLowerGFh]y%(IsDigitG%/IsAlphaNumericG%3
IsControlCharacterG%(IsSpaceG%.IsPunctuationG%*IsGraphicG%-IsIdentifierG%.IsIde
ntifier1G%,IsPrintableG%(IsASCIIG%+IsHexDigitG%-IsOctalDigitG%.IsBinaryDigitG%(
IsVowelG%)HasUpperG%)HasLowerG%)HasAlphaG%)HasDigitG%0HasAlphaNumericG%4HasCont
rolCharacterG%)HasSpaceG%/HasPunctuationG%+HasGraphicG%.HasIdentifierG%/HasIden
tifier1G%-HasPrintableG%)HasASCIIG%,HasHexDigitG%.HasOctalDigitG%/HasBinaryDigi
tG%)HasVowelG%$HasG%5ExpandCharacterClassG%'RandomG%*RandomizeG%3IndexOfCoincid
enceG%(EntropyG%/ArithmeticMeanG%(KasiskiG%(RepeatsG%(ExplodeG%(ImplodeG%%ChopG
%&ChompG%&FenceG%+MatchFenceG%(PadLeftG%)PadRightG%'CentreG%'CenterG%%TrimG%*Tr
imRightG%)TrimLeftG%(SqueezeG%,DeleteSpaceG%(ReverseG%'InsertG%'DeleteGF_ail%)I
sSuffixG%-CommonPrefixG%-CommonSuffixG%7LongestCommonSubStringG%9LongestCommonS
ubSequenceG%(SoundexG%*MetaphoneG%,LevenshteinG%0HammingDistanceG%-EditDistance
G%/PrefixDistanceG%/SuffixDistanceG%4DifferencePositionsG%(CompareG%*CompareCIG
%*CamelCaseG%*UpperCaseG%*LowerCaseG%*OtherCaseG%+CapitalizeG%.FirstFromLeftG%/
FirstFromRightG%%TakeG%%DropG%&SnarfG%-CharacterMapG%)LeftFoldG%*RightFoldG%$Ma
pG%'AndMapG%&OrMapG%%CharG%$OrdG%*SubStringG%'SelectG%'RemoveG%-SelectRemoveG%&
GroupGFaghl%*CaseSplitG%,LengthSplitG%,StringSplitG%,ReadabilityG%*SentencesG%&
WordsG%*WordStartG%(WordEndG%/WordContainingG%'NGramsG%6SimilarityCoefficientG%
*WordCountG%%JoinG%)CaseJoinGF][y%'RegSubG%(RegSubsG%)RegSplitG%2ApproximateSea
rchG%5ApproximateSearchAllG%.HammingSearchG%1HammingSearchAllGFdifl%*SearchAllG
%+SubstituteG%.SubstituteAllG%2PatternDictionaryG%.FormatMessageG%+FormatTimeG%
*ParseTimeG%%FillG%'RepeatG%%IotaG%(VisibleG%'EscapeG%'EncodeG%'DecodeG%)Compre
ssG%+UncompressG%.WildcardMatchG%*NumbOccurG%:CountCharacterOccurrencesG%&Shift
G%'RotateG%)ExchangeG%%StemG%(PermuteG%0SortPermutationG%%SortG%'UniqueG%%HashG
%)IsSortedG%*IsAnagramG%)AnagramsG%/SyllableLengthG%)GenerateG%(NthWordG%(Suppo
rtG%+IsBalancedGFj[gl%-IsPalindromeG%.IsEodermdromeG%.IsPermutationG%.IsDerange
mentG%,IsMonotonicG%,IsPrimitiveG%.PrimitiveRootG%'BorderG%-BorderLengthG%,Bord
erArrayG%(OverlapG%,IsConjugateG%1MinimumConjugateG%'PeriodG%)IsPeriodG%*ThueMo
rseG%1MonotonicFactorsG%.LyndonFactorsG%)LexOrderG%.ShortLexOrderG%,RevLexOrder
G%1ShortRevLexOrderG%7LeftRecursivePathOrderG%8RightRecursivePathOrderG%,ToByte
ArrayG%.FromByteArrayG%5CharacterFrequenciesG%<MaximalPalindromicSubstringG%(Mi
nCharG%(MaxCharG%)TabulateG%-StringBufferG%+ExpandTabsG%)WrapTextG%'IndentG%2Pa
tternEquivalentG%5PatternCanonicalFormG%3GenerateIdentifierGF^dq%%SubsG%*Fibona
cciG6;%(TestingG%'BitmapG%#BFG%,SuffixArrayG%6LyndonFactorPositionsG%3CheckMaxi
malRepeatG%2slowLyndonFactorsG%=SerialCorrelationCoefficientG%+ChiSquaredG%?Lon
gestCommonSubSequenceLengthG%/PrintSentencesG%+difficult?G%-matchMatrix2G%*_ran
dpermG%)_permuteG%(_configG%+TrampolineG%)SequiturG%(passignG%&defunG%-compress
ImplG%/uncompressImplG%2ParallelMultiSubsG%0SerialMultiSubsG%+NextLetterGgwGI&:
-522GFarGI&:-523GFarGI&:-524GFarGI&:-525GFarGI&:-526GFarGI&:-527GFarGI&:-528GFa
rGI&:-529GFarGI&:-530GFarGI&:-531GFarGI&:-532GFarGI&:-533GFarGI&:-534GFarGI&:-5
35GFarGI&:-536GFarGI&:-537GFarGI&:-538GFarGI&:-539GFarGI&:-540GFarGI&:-541GFarG
I&:-542GFarGI&:-543GFarGI&:-544GFarGI&:-545GFarGI&:-546GFarGI&:-547GFarGI&:-548
GFarGI&:-549GFarGI&:-550GFarGI&:-551GFarGI&:-552GFarGI&:-553GFarGI&:-554GFarGI&
:-555GFarGI&:-556GFarGI&:-557GFarGI&:-558GFarGI&:-559GFarGI&:-560GFarGI&:-561GF
arGI&:-562GFarGI&:-563GFarGI&:-564GFarGI&:-565GFarGI&:-566GFarGI&:-567GFarGI&:-
568GFarGI&:-569GFarGI&:-570GFarGI&:-571GFarGI&:-572GFarGI&:-573GFarGI&:-574GFar
GI&:-575GFarGI&:-576GFarGI&:-577GFarGI&:-578GFarGI&:-579GFarGI&:-580GFarGI&:-58
1GFarGI&:-582GFarGI&:-583GFarf*6"Fcg[n6$%.call_externalG-Fd\_m6'%1mstring_ispre
fixGQ&MAPLEF&/Q$LIBF&Q(mstringF&/Q,DESCRIPTIONF&Q>test~for~an~initial~substring
F&Q,THREAD_SAFEF&Fcg[n-Feg[n6'F%".g(f$Q6z)FcbmFcbmFgds6#F_h[nFcg[nFcg[n6$Fgt/Ff
zF[[yGI&:-585GFarGI&:-586GFarGI&:-587GFarGI&:-588GFarGI&:-589GFarGI&:-590GFarGI
&:-591GFarGI&:-592GFarGI&:-593GFarGI&:-594GFarGI&:-595GFarGI&:-596GFarGI&:-597G
FarGI&:-598GFarGI&:-599GFarGI&:-600GFarGI&:-601GFarGI&:-602GFarGI&:-603GFarGI&:
-604GFarGI&:-605GFarGI&:-606GFarGI&:-607GFarGI&:-608GFarGI&:-609GFarGI&:-610GFa
rGI&:-611GFarGI&:-612GFarGI&:-613GFarGI&:-614GFarGI&:-615GFarGI&:-616GFarGI&:-6
17GFarGI&:-618GFarGI&:-619GFarGI&:-620GFarGI&:-621GFarGI&:-622GFarf*6"F^[\n6$Fe
g[n-Fd\_m6&%.mstring_splitGFig[nFjg[n/F^h[nQHsplit~a~string~at~designated~chara
ctersF&F^[\n-Feg[n6'F%".S'y$Q6z)FcbmFinFgds6#Fd[\nF^[\nF^[\n6$Fgt/FfzF[[yGI&:-6
24GFarGI&:-625GFarGI&:-626GFarGI&:-627GFarGI&:-628GFarGI&:-629GFarGI&:-630GFarG
I&:-631GFarGI&:-632GFarGI&:-633GFarGI&:-634GFarGI&:-635GFarGI&:-636GFarGI&:-637
GFarf*6"Fj\\n6$Feg[n-Fd\_m6&%1mstring_regmatchGFig[nFjg[n/F^h[nQSdetermine~if~a
~string~matches~a~regular~expressionF&Fj\\n-Feg[n6'F%".'*3VQ6z)FcbmFinFgds6#F`]
\nFj\\nFj\\n6$Fgt/FfzF[[yGI&:-639GFarGI&:-640GFarGI&:-641GFarGI&:-642GFarGI&:-6
43GFarGI&:-644GFarGI&:-645GFarGI&:-646GFarGI&:-647GFarGI&:-648GFarGI&:-649GFarG
I&:-650GFarGI&:-651GFarGI&:-652GFarGI&:-653GFarGI&:-654GFarGI&:-655GFarGI&:-656
GFarGI&:-657GFarGI&:-658GFarGI&:-659GFarGI&:-660GFarGI&:-661GFarGI&:-662GFarGI&
:-663GFarGI&:-664GFarGI&:-665GFarGI&:-666GFarGI&:-667GFarGI&:-668GFarGI&:-669GF
arGI&:-670GFarGI&:-671GFarGI&:-672GFarGI&:-673GFarGI&:-674GFarGI&:-675GFarGI&:-
676GFarGI&:-677GFarGI&:-678GFarGI&:-679GFarGI&:-680GFarGI&:-681GFarGI&:-682GFar
GI&:-683GFarGI&:-684GFarGI&:-685GFarGI&:-686GFarGI&:-687GFarGI&:-688GFarGI&:-68
9GFarGI&:-690GFarGI&:-691GFarGI&:-692GFarGI&:-693GFarGI&:-694GFarGI&:-695GFarGI
&:-696GFarGI&:-697GFarGI&:-698GFarGI&:-699GFarGI&:-700GFarGI&:-701GFarGI&:-702G
FarGI&:-703GFarGI&:-704GFarGI&:-705GFarGI&:-706GFarGI&:-707GFarGI&:-708GFarGI&:
-709GFarGI&:-710GFarGI&:-711GFarGI&:-712GFarGI&:-713GFarGI&:-714GFarGI&:-715GFa
rGI&:-716GFarGI&:-717GFarGI&:-718GFarGI&:-719GFarGI&:-720GFarGI&:-721GFarGI&:-7
22GFarGI&:-723GFarGI&:-724GFar;GI&:-725GFarGI&:-726GFarGI&:-727GFarGI&:-728GFar
GI&:-729GFarGI&:-730GFarGI&:-731GFarGI&:-732GFarGI&:-733GFarGI&:-734GFarGI&:-73
5GFarGI&:-736GFarGI&:-737GFarGI&:-738GFarGI&:-739GFarGI&:-740GFarGI&:-741GFarGI
&:-742GFarGI&:-743GFarGI&:-744GFarGI&:-745GFarGI&:-746GFarGI&:-747GFarGI&:-748G
FarGI&:-749GFarb6#F^]lFja[n6%Fiip%+noimplicitG%jnCopyright~(c)~Maplesoft,~a~div
ision~of~Waterloo~Maple~Inc.~2005GFeejm6"6#QKa~package~of~string~manipulation~u
tilitiesF[e\nF[e\nF[e\nF&F\[y,
I%K_M_F^eoF&,
I+maxxmeas_vF%F&,
I$valFIF&,
I+switchcrit7#,&%%Amm1GF:!#SF:F&,
I%vDb0FIF&,
I&rate5*$FjioFNF&,
I*nswitchesF%F&,
I(ntopt_vF%F&,
I'nnodes"$,"F&,
I(mu_max_F]eoF&,
I+bnddata_upFidjmF&,
I-listnotranspF_joF&,
I*interfacef*6"6&FfuF`jp%#naG%#vaG6#%]oCopyright~(c)~1999~by~the~Waterloo~Maple
~Inc.~All~rights~reserved.GFbf\nC&@$4-Fbt6$7#9"-F^_l6#<$Ffhn/FfhnF_elYQ2invalid
~argumentsFbf\n>8$Fbbl?&8%F]g\nFcbm@%-Fbt6$Fhg\nFfhn@)-Feen6$Fhg\n<%.%+printbyt
esG.%1max_record_depthG.%:display_zero_complex_partG>Ffg\n6$Ffg\n-F]bo6#Fhg\n/F
hg\n.%+patchlevelGC$>8'-F\i\nFbf\n@%/F_i\n-F[i\nFbf\n>Ffg\n6$Ffg\nF%>Ffg\n6$Ffg
\nF_i\n/Fhg\n.%+autoassignG>Ffg\n6$Ffg\n%5interface/autoassignG>Ffg\n6$Ffg\n-%+
streamcallG6#-%.INTERFACE_GETGFih\nC%>8&-Ffv6$F:Fhg\n>F_i\n-Ffv6$F;Fhg\n@)-Feen
6$Fgj\nF_h\n>Ffg\nFgh\n/Fgj\nF[i\nY6$Q1%1~cannot~be~setFbf\nFgj\n/Fgj\nFii\nC$@
$4-Fbt6$F_i\nFa[mYQAautoassign~root~must~be~a~symbolFbf\n@'-Feen6$F_i\n<$Fin.Fg
dq-%'assignG6#/.F]j\nFa\]n/F_i\nFcbm-Fc\]n6#/Ff\]n.%"RG-Fc\]n6#/Ff\]nF_i\nC$>Ff
g\n6$Ffg\n-Faj\n6#-%.INTERFACE_SETG6$Fgj\nF_i\n@$/Fgj\n.%,helpbrowserG>FecoFeco
OFfg\nFbf\n6$F\i\nFecoFbf\nFbco,
I%rho_F`eoF&,
I+file_namesFacqF&,
I)packagesf*6"Fc^]n6$FewFfwFc^]n-Fg]s6%'T%F^_lFh^]n7"Fc^]nFc^]n6&FczF&FjjoI&pli
stG/F_[lFi[pF\]p,
I(idpar_vF,F&,
I's_dens$FbuFNF&,
I,time_inioutFdoF&,
I+nrnotranspF>F&,
I(versionf*6"6(%$guiG%'kernelG%(libraryG%*toolboxesGF\a^mFh_l6"Fd_]nC2>8$-Fey6$
-Faco6#.Fdail.F\u>F]`]n&-_F[[yFaghl6#F]`]n6#FN>F]`]n-F\gsFh`]n>8%-Fey6$-F]boFa`
]nFc`]n>F]a]n&-Fg`]n6#F]a]nFi`]n>F]a]n-F\gsFda]n>8&%0_libraryversionG>8)F\[jm>8
'-F]bo6#.%/toolboxversionG@$0F]b]n7"?&8(F]b]nFcbm>F[b]n-%$maxG6$F[b]n-F`]y6#&Ff
b]n6#F:>F[b]n,&F[b]nF:F:F:-%'printfG6&Q)%*s:~%d|+Fd_]nF[b]nQ/User~InterfaceFd_]
nF]`]n-Fbc]n6&Fdc]nF[b]nQ'KernelFd_]nF]a]n-Fbc]n6&Fdc]nF[b]nQ(LibraryFd_]nFha]n
@$Fcb]n?&Ffb]nF]b]nFcbm-Fbc]n6&Fdc]nF[b]nF]c]n-F\gs6#&Ffb]n6#F<-Fib]n6%F]`]nF]a
]nFha]nFd_]nFd_]nFd_]nFeail,
I+ndissolvedF:F&,
I*type_down7(F:F:F:F:F:F:F&,
I(neqrxnsF;F&,
I&rate6F]oF&,
I+nparam_optF%F&,
I".f*6"6,Fa_oF\a^mFg_l%&constG%'const1GF[_l%*hasrtableG%#b1G%#b2G%%optsG6$/%(bu
iltinG%,builtin_dotG%fnCopyright~(c)~1999~Waterloo~Maple~Inc.~All~rights~reserv
ed.GF^e]nC-@$33/9#F;-Fbt6$7#9"7$.Fed[lFff]n5-Fbt6$&Fdf]n6#F:<$.Ffdv.F^ev-Fbt6$&
Fdf]n6#F;F\g]nZ%O-_%.LinearAlgebraG%)MultiplyG6$Fdf]n.%)_fromdotGF^e]nF^e]n>8$-
F`w6$f*6#FduF^e]n6$FewFfwF^e]n@%-Fbt6$9$.-F_`s6$F_elF^^em-Ffv6#Ffh]nFfh]nF^e]nF
^e]nF^e]nFcf]n>6$8'F]h]n-F`^m6%FbtF]h]n.Fhjl>F^i]n-F^il6$-Ffv6#F^i]n-Ffv6#-F`w6
$f*Fah]nF^e]n6$FewFfwF^e]n-Fg]s6%-Fbt6$Ffh]n<%F^ilF^^emFai]n-Fbdp6%FbtFfh]nFai]
nFbblF^e]nF^e]nF^e]nF]h]n>F]h]n-F`w6$f*Fah]nF^e]n6$FewFfwF^e]n-Fg]s6%F_j]n-F]iy
Fcj]nFfh]nF^e]nF^e]nF^e]nF]h]n>8*-Fh^p6$F]h]nFff]n@$5/F]h]n7"3/F^i]nF%4F][^nOF^
i]n>8%-F`w6%FbtF]h]nFff]n@$-Feen6$FcbmFi[^nC$>8&-F`w6$f*6#FfdpF^e]n6$FewFfwF^e]
n@%'Ffh]n.-F\cl6$F]_lF_^w-Fey6$Ffh]nF]g]nFfh]nF^e]nF^e]nF^e]nF]h]n@$0Fa\^nF]h]n
C$>F]h]nFa\^n>Fi[^nFj[^n?(Fa\^nF:F:F^e]n2Fa\^n-Fd_m6#F]h]nC(>8-Fbbl@'3&Fi[^n6#F
a\^n&Fi[^n6#,&Fa\^nF:F:F:C$@$4-Fbt6$F^i]n-F]tF[g]nC$>F]h]n-Fh^m6$/Fa\^n*&F^i]nF
:&F]h]nF]^^nF:F]h]n>F^i]nF:@'3-Fbt6$F]_^n.F_[q-Fbt6$&F]h]nF_^^nFc_^n>8)f*6$F]i
\l%"BGF^e]n6$FewFfwF^e]n-%$zipG6%f*6$Fdu%"yGF^e]n6$FewFfwF^e]n-F^^em6$Ffh]n9%F^
e]nF^e]nF^e]nFfh]nFf`^nF^e]nF^e]nF^e]n33-Fbt6$F]_^nF^g]n-Fbt6$Ff_^nF^g]n/-%.Vec
torOptionsG6$F]_^n.%,orientationG-F_a^n6$Ff_^nFaa^n>Fh_^n_Fgg]n%+DotProductGC$>
Fh_^nFfg]n>Fi]^nFjg]n5F\^^nF^^^nC$@$Fc^^nC$@%F\^^n>F]h]nFi^^n>F]h]n-Fh^m6$/F`^^
n*&F^i]nF:Ff_^nF:F]h]n>F^i]nF:\C%>8+-Fg]s6%-Fbt6$F]_^nFjcm-Ffv6$F:F]_^nF]_^n>8,
-Fg]s6%-Fbt6$Ff_^nFjcm-Ffv6$F:Ff_^nFf_^n@%3/Fjb^nFbc^n-Fbt6$Fjb^n.Ffhn>Fh_^n.F^
ilFgb^n>F]h]n-Fh^m6%/Fa\^n-Fh_^n6%F]_^nFf_^nFi]^n/F`^^nFbblF]h]n>Fi[^n-Fh^m6%/F
a\^n-Fbt6$F]_^nFff]nFgd^nFi[^n@&-Fbt6$F]_^nFai]nC&>F^i]nF\_^n>F]h]n-Fh^m6$/Fa\^
nFbblF]h]n>Fi[^n-Fh^m6$Ffe^nFi[^n@$2F:Fa\^n>Fa\^n,&Fa\^nF:FNF:3-Fbt6$F]_^nF^il-
Fh^pF`e^nC$>6$8(F]_^n-F`^m6%FbtF]_^nFai]n>F^i]n*&F^i]nF:Fef^nF:>Fa\^nF]f^n@'Fb[
^nF^i]n/Fe]^nF:*&F^i]nF:-FfvFf]^nF:*&F^i]nF:-.F^^em6#F^g^nF:F^e]nF^e]nF^e]nF_^e
m,
I'viareaF%F&,
I*listinputF9F&,
I&viporFIF&,
I)dDNA_rdt,&F`pF:%#r4GFNF&,
I"SFaejmF&,
I$viwF%F&,
I,listroutput7*F:F;F<F=F>F?FMFbpF&,
I$vq0$F][jmFeoF&,
I'dCO2dt,&*(F_pF:,&F:F:FgpFNF:FgpFNF:*&Fhg^nF:F[qF:F:F&
