MVR5
I)shareman=6"%&falseGE\[l#%%initGRF$F$6#%ACopyright~2005~by~John~Maplenut.GF$C$
@$4-%%typeG6$F"%*protectedGC&-%*unprotectG6$.%'pacmanG.%%withG@$4-%)assignedG6#
F7>&F76#F9-%%evalGFA>F9R6#'%(packageG<'%*procedureG%&tableG%%nameG%'stringG%'mo
duleGF$F)F$-&F"6#%%execG6$9$&9"6#;""#!""F$F$F$-%(protectG6%F8F6.F"%%NULLGF$6%F"
F7F9F$FRR6#%"NG6&%%findG%*checknameG%"nG%'resultGF)F$C'>8$R6#'%"FGFL6&%+shareta
bleG%)filenameGFbo%#shGF)F$C*>FeoR6%FioF]pFbo6%%"iG%"tG%#stGF$F$C%@%/9%.%'_Shar
eG>8%9&C&>F]q-%(convertG6$FTFM>8&-FK6#7#-%#opG6#Fip@$4-%'memberG6$F]q<#%0sharem
an/loadedGC&>Fbr6$FbrF]q@$-F=6#&Feq6#Q*ShareNameF$-%'printfG6$Q4Share~Library:~
%s|.|+F$Fir@$-F=6#&Feq6#Q(AuthorsF$C%>F]q&Fcs6#"""?(FeoFYFjs-%%nopsGFbs%%trueG>
F]q-%$catG6&%!GF]q%&~and~G&Fcs6#Feo-F]s6$Q.Authors:~%s|.|+F$F]q@$-F=6#&Feq6#Q,D
escriptionF$-F]s6$Q2Description:~%s|.|+F$F]u@%-F=6#&Feq6#Q-FunctionListF$>F]qFf
u>F]qF^q?(FeoFjsFjs-F]t6#F]qF^t>&F]qFft-Fbq6$F_v.FL-%%sortGF]vF$6#FbrF$>F[qFjp>
F]q-Fat6'Fct%*sharenameG%"/GFT%#.mG>Feq-RF$F$F$F$AT#F$F$6$F\pF]qF$>8'-%%copyG6#
F[q>Feq-%*traperrorG6#-%(readlibG6$FTF]q@%4-F/6$Feq.FK>Feq7#FT>Feq-F@FS-Feo6%FT
FdwFeqF$6%F[qFjvF7F$>F]qRF\o6%%&checkG%#nmGFepF$F$C&>Feo-FK6#72/%%pof~G.%$pofG/
%(_undistG.%'undistG/%)_CollatzG.%(CollatzG/%)TDTools~G.%(TDToolsG/%+No~on-line
G.%#IFG/%+See~?SigmaG.%(MatPadeG/%+See~?frobeG.%)normformG/%+FormalPoweG.%$FPSG
/%+DaubechiesG.%%daubG/%+See~?classG.%&classG/%+MACROC~:~CG.%'macroCG/%+MACROFO
RT:G.%)macroforG/%*_surfacesG.%)surfacesG/%*_partialsG.%)partialsG/%+The~polyno
G.%(polyconG/%(Wigner~G.%'WignerG>F]q-Fbq6$FTFbv>Feq-%*substringG6$F]q;Fjs"#5@%
-F_r6$Feq-%$mapG6$Fjq<#-%(indicesGFft&Feo6#FeqF]qF$F$F$>FdwFin@$-F=6#FjvC%>Feq-
Fjw6#-F]q6#FT@$4-F=FevC$-Fjw6#--Feo6#%%MVR5GF$>FbrFin>Fdw-Fjw6#-Feo6$FeqFU@%45/
Fdw%*lasterrorG/FdwFinFdwFgxF$6$F7FbrF$F$
