MVR5
I)shareman=6"%&falseGE\[l#%%execGR6#%"NG6%%%loadG%'resultG%"gG6#%ACopyright~200
5~by~John~Maplenut.GF$C%>8$R6#%"FG6'%*checknameG%+sharetableG%)filenameG%#shG%"
fGF$F$C,>F3RF)6%%&checkG%#nmG%#stGF$F$C&>F3-%&tableG6#72/%%pof~G.%$pofG/%(_undi
stG.%'undistG/%)_CollatzG.%(CollatzG/%)TDTools~G.%(TDToolsG/%+No~on-lineG.%#IFG
/%+See~?SigmaG.%(MatPadeG/%+See~?frobeG.%)normformG/%+FormalPoweG.%$FPSG/%+Daub
echiesG.%%daubG/%+See~?classG.%&classG/%+MACROC~:~CG.%'macroCG/%+MACROFORT:G.%)
macroforG/%*_surfacesG.%)surfacesG/%*_partialsG.%)partialsG/%+The~polynoG.%(pol
yconG/%(Wigner~G.%'WignerG>8%-%(convertG6$9$.%%nameG>8&-%*substringG6$Feq;""""#
5@%-%'memberG6$F]r-%$mapG6$%#opG<#-%(indicesG6#F3&F36#F]rFeqF$F$F$>FeqR6#%"TG6$
%"iG%"tGF$F$C$@%4-%)assignedG6#&T#6#Q*ShareNameF$>FeqFiqC&>Feq-Fgq6$T%%'stringG
@$4-F]t6#%0shareman/loadedG>F^u7"@$4-Ffr6$Feq<#-F[sF]uC&>F^u7$FfuFeq-%'printfG6
$Q4Share~Library:~%s|.|+F$F_t@$-F]t6#&F`t6#Q(AuthorsF$C%>Feq&Fav6#Fbr?(F3""#Fbr
-%%nopsGF`v%%trueG>Feq-%$catG6&%!GFeq%&~and~G&FavF_s-F[v6$Q.Authors:~%s|.|+F$Fe
q@$-F]t6#&F`t6#Q,DescriptionF$-F[v6$Q2Description:~%s|.|+F$Fjw@%-F]t6#&F`t6#Q-F
unctionListF$>FeqFcx>FeqFiq-%%sortG6#FeqF$F]u6&F;8'F<8(>%'_ShareGF`u>F]y-F36#Fi
q>F]r-F_w6'Faw%*sharenameG%"/GF]y%#.mG>F`t-RF$F$F$F$AF`tF$F$6$F:F]rF$>F\y-FG6#7
#-F[s6#F_y>F`t-%*traperrorG6#-%(readlibG6$F]yF]r@%4-%%typeG6$F`t.FG>F`t7#F]y>F`
t-&%'pacmanG6#%%withG6$F]y&9"6#;Fiv!""-Feq6#F`tF$Fcz6$F-Feq@$-F]t6#FfyC'>F]r-%*
interfaceG6#%*warnlevelG-Fh\l6#/Fj\l""!@$4-F]t6#%(grobnerG-Ffz6#-FizFb]l-Fh\l6#
/Fj\lF]r>Feq-Ffz6#-F36$FiqFj[l@%-F^[l6$Feq.%%listGFeq-Fe[lF^^lF$6$Ff[lFfyF$%%in
itGRF$F$F/F$C$@$4-F^[l6$F"%*protectedGC&-%*unprotectG6$.Ff[l.Fh[l@$4-F]t6#Ff[l>
Fe[l-%%evalGFg[l>Fh[lR6#'%(packageG<'%*procedureGFGF[rFit%'moduleGF$F/F$-&F"6#F
'F^^lF$F$F$-%(protectG6%Fc_lFb_l.F"-%'RETURNGF$F$6$Ff[lFh[lF$F$
